package load;

import org.apache.ignite.Ignite;
import org.apache.ignite.Ignition;
import org.apache.ignite.cache.query.SqlFieldsQuery;

import config.ClientConfigurationFactory;

/** This file was generated by Ignite Web Console (11/21/2019, 08:54) **/
public class LoadCaches {
    /**
     * <p>
     * Utility to load caches from database.
     * <p>
     * How to use:
     * <ul>
     *     <li>Start cluster.</li>
     *     <li>Start this utility and wait while load complete.</li>
     * </ul>
     * 
     * @param args Command line arguments, none required.
     * @throws Exception If failed.
     **/
    public static void main(String[] args) throws Exception {
        try (Ignite ignite = Ignition.start(ClientConfigurationFactory.createConfiguration())) {
            System.out.println(">>> Loading caches...");

            
            long start,end,total = 0;
			start = System.currentTimeMillis();
            System.out.println(">>> Loading cache: AdUserCache");
            ignite.cache("AdUserCache").loadCache(null);
            System.out.println("size of cache AdUserCache "+ignite.cache("AdUserCache").size());
            end = System.currentTimeMillis() - start;
            total+=end;
            System.out.println(end);
            System.out.println();
            
            start = System.currentTimeMillis();
            System.out.println(">>> Loading cache: CBpartnerCache");
            ignite.cache("CBpartnerCache").loadCache(null);
            end = System.currentTimeMillis() - start;
            total+=end;
            System.out.println(end);
            System.out.println();
            
            start = System.currentTimeMillis();
            System.out.println(">>> Loading cache: CInvoiceCache");
            ignite.cache("CInvoiceCache").loadCache(null);
            end = System.currentTimeMillis() - start;
            total+=end;
            System.out.println(end);
            System.out.println();

            start = System.currentTimeMillis();
            System.out.println(">>> Loading cache: CInvoicelineCache");
            ignite.cache("CInvoicelineCache").loadCache(null);
            end = System.currentTimeMillis() - start;
            total+=end;
            System.out.println(end);
            System.out.println();

            start = System.currentTimeMillis();
            System.out.println(">>> Loading cache: COrderCache");
            ignite.cache("COrderCache").loadCache(null);
            end = System.currentTimeMillis() - start;
            total+=end;
            System.out.println(end);
            System.out.println();

            start = System.currentTimeMillis();
            System.out.println(">>> Loading cache: COrderlineCache");
            ignite.cache("COrderlineCache").loadCache(null);
            end = System.currentTimeMillis() - start;
            total+=end;
            System.out.println(end);
            System.out.println();

            start = System.currentTimeMillis();
            System.out.println(">>> Loading cache: MAttributeCache");
            ignite.cache("MAttributeCache").loadCache(null);
            end = System.currentTimeMillis() - start;
            total+=end;
            System.out.println(end);
            System.out.println();

            start = System.currentTimeMillis();
            System.out.println(">>> Loading cache: MAttributeinstanceCache");
            ignite.cache("MAttributeinstanceCache").loadCache(null);
            end = System.currentTimeMillis() - start;
            total+=end;
            System.out.println(end);
            System.out.println();

            start = System.currentTimeMillis();
            System.out.println(">>> Loading cache: MInoutCache");
            ignite.cache("MInoutCache").loadCache(null);
            end = System.currentTimeMillis() - start;
            total+=end;
            System.out.println(end);
            System.out.println();

            start = System.currentTimeMillis();
            System.out.println(">>> Loading cache: MInoutlineCache");
            ignite.cache("MInoutlineCache").loadCache(null);
            end = System.currentTimeMillis() - start;
            total+=end;
            System.out.println(end);
            System.out.println();

            start = System.currentTimeMillis();
            System.out.println(">>> Loading cache: MProductCache");
            ignite.cache("MProductCache").loadCache(null);
            end = System.currentTimeMillis() - start;
            total+=end;
            System.out.println(end);
            System.out.println();

            start = System.currentTimeMillis();
            System.out.println(">>> Loading cache: XxListetauxvaleurCache");
            ignite.cache("XxListetauxvaleurCache").loadCache(null);
            end = System.currentTimeMillis() - start;
            total+=end;
            System.out.println(end);
            System.out.println();
            
            String sql = "";
			SqlFieldsQuery sqlQuery = new SqlFieldsQuery(sql );
			ignite.cache(ignite.cacheNames().stream().findAny().get()).query(sqlQuery );
            

            System.out.println(">>> All caches loaded! in : "+total+" ms");
        }
    }
}