package com.wanasis.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;

/**
 * CInvoice definition.
 * 
 * This file was generated by Ignite Web Console (11/21/2019, 08:54)
 **/
public class CInvoice implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for adClientId. */
    private long adClientId;

    /** Value for adOrgId. */
    private long adOrgId;

    /** Value for isactive. */
    private String isactive;

    /** Value for created. */
    private Date created;

    /** Value for createdby. */
    private long createdby;

    /** Value for updated. */
    private Date updated;

    /** Value for updatedby. */
    private long updatedby;

    /** Value for issotrx. */
    private String issotrx;

    /** Value for documentno. */
    private String documentno;

    /** Value for docstatus. */
    private String docstatus;

    /** Value for docaction. */
    private String docaction;

    /** Value for processing. */
    private String processing;

    /** Value for processed. */
    private String processed;

    /** Value for posted. */
    private String posted;

    /** Value for cDoctypeId. */
    private long cDoctypeId;

    /** Value for cDoctypetargetId. */
    private long cDoctypetargetId;

    /** Value for cOrderId. */
    private Long cOrderId;

    /** Value for description. */
    private String description;

    /** Value for isapproved. */
    private String isapproved;

    /** Value for istransferred. */
    private String istransferred;

    /** Value for isprinted. */
    private String isprinted;

    /** Value for salesrepId. */
    private Long salesrepId;

    /** Value for dateinvoiced. */
    private Date dateinvoiced;

    /** Value for dateprinted. */
    private Date dateprinted;

    /** Value for dateacct. */
    private Date dateacct;

    /** Value for cBpartnerId. */
    private long cBpartnerId;

    /** Value for cBpartnerLocationId. */
    private long cBpartnerLocationId;

    /** Value for poreference. */
    private String poreference;

    /** Value for isdiscountprinted. */
    private String isdiscountprinted;

    /** Value for dateordered. */
    private Date dateordered;

    /** Value for cCurrencyId. */
    private long cCurrencyId;

    /** Value for paymentrule. */
    private String paymentrule;

    /** Value for cPaymenttermId. */
    private long cPaymenttermId;

    /** Value for cChargeId. */
    private Long cChargeId;

    /** Value for chargeamt. */
    private BigDecimal chargeamt;

    /** Value for totallines. */
    private BigDecimal totallines;

    /** Value for grandtotal. */
    private BigDecimal grandtotal;

    /** Value for mPricelistId. */
    private long mPricelistId;

    /** Value for istaxincluded. */
    private String istaxincluded;

    /** Value for cCampaignId. */
    private Long cCampaignId;

    /** Value for cProjectId. */
    private Long cProjectId;

    /** Value for cActivityId. */
    private Long cActivityId;

    /** Value for ispaid. */
    private String ispaid;

    /** Value for cPaymentId. */
    private Long cPaymentId;

    /** Value for cCashlineId. */
    private Long cCashlineId;

    /** Value for createfrom. */
    private String createfrom;

    /** Value for generateto. */
    private String generateto;

    /** Value for sendemail. */
    private String sendemail;

    /** Value for adUserId. */
    private Long adUserId;

    /** Value for copyfrom. */
    private String copyfrom;

    /** Value for isselfservice. */
    private String isselfservice;

    /** Value for adOrgtrxId. */
    private Long adOrgtrxId;

    /** Value for user1Id. */
    private Long user1Id;

    /** Value for user2Id. */
    private Long user2Id;

    /** Value for cConversiontypeId. */
    private Long cConversiontypeId;

    /** Value for ispayschedulevalid. */
    private String ispayschedulevalid;

    /** Value for refInvoiceId. */
    private Long refInvoiceId;

    /** Value for isindispute. */
    private String isindispute;

    /** Value for zsubpaymentruleId. */
    private Long zsubpaymentruleId;

    /** Value for zbpinvoice. */
    private String zbpinvoice;

    /** Value for zPaymentcommunication. */
    private String zPaymentcommunication;

    /** Value for invoicecollectiontype. */
    private String invoicecollectiontype;

    /** Value for matchrequirementi. */
    private String matchrequirementi;

    /** Value for cBpBankaccountId. */
    private Long cBpBankaccountId;

    /** Value for isreturntrx. */
    private String isreturntrx;

    /** Value for cBpartnersrId. */
    private Long cBpartnersrId;

    /** Value for xxApplieddiscount. */
    private String xxApplieddiscount;

    /** Value for xxSealedinvoice. */
    private String xxSealedinvoice;

    /** Value for isdelivered. */
    private String isdelivered;

    /** Value for isarchived. */
    private String isarchived;

    /** Value for issms. */
    private String issms;

    /** Empty constructor. **/
    public CInvoice() {
        // No-op.
    }

    /** Full constructor. **/
    public CInvoice(long adClientId,
        long adOrgId,
        String isactive,
        Date created,
        long createdby,
        Date updated,
        long updatedby,
        String issotrx,
        String documentno,
        String docstatus,
        String docaction,
        String processing,
        String processed,
        String posted,
        long cDoctypeId,
        long cDoctypetargetId,
        Long cOrderId,
        String description,
        String isapproved,
        String istransferred,
        String isprinted,
        Long salesrepId,
        Date dateinvoiced,
        Date dateprinted,
        Date dateacct,
        long cBpartnerId,
        long cBpartnerLocationId,
        String poreference,
        String isdiscountprinted,
        Date dateordered,
        long cCurrencyId,
        String paymentrule,
        long cPaymenttermId,
        Long cChargeId,
        BigDecimal chargeamt,
        BigDecimal totallines,
        BigDecimal grandtotal,
        long mPricelistId,
        String istaxincluded,
        Long cCampaignId,
        Long cProjectId,
        Long cActivityId,
        String ispaid,
        Long cPaymentId,
        Long cCashlineId,
        String createfrom,
        String generateto,
        String sendemail,
        Long adUserId,
        String copyfrom,
        String isselfservice,
        Long adOrgtrxId,
        Long user1Id,
        Long user2Id,
        Long cConversiontypeId,
        String ispayschedulevalid,
        Long refInvoiceId,
        String isindispute,
        Long zsubpaymentruleId,
        String zbpinvoice,
        String zPaymentcommunication,
        String invoicecollectiontype,
        String matchrequirementi,
        Long cBpBankaccountId,
        String isreturntrx,
        Long cBpartnersrId,
        String xxApplieddiscount,
        String xxSealedinvoice,
        String isdelivered,
        String isarchived,
        String issms) {
        this.adClientId = adClientId;
        this.adOrgId = adOrgId;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.issotrx = issotrx;
        this.documentno = documentno;
        this.docstatus = docstatus;
        this.docaction = docaction;
        this.processing = processing;
        this.processed = processed;
        this.posted = posted;
        this.cDoctypeId = cDoctypeId;
        this.cDoctypetargetId = cDoctypetargetId;
        this.cOrderId = cOrderId;
        this.description = description;
        this.isapproved = isapproved;
        this.istransferred = istransferred;
        this.isprinted = isprinted;
        this.salesrepId = salesrepId;
        this.dateinvoiced = dateinvoiced;
        this.dateprinted = dateprinted;
        this.dateacct = dateacct;
        this.cBpartnerId = cBpartnerId;
        this.cBpartnerLocationId = cBpartnerLocationId;
        this.poreference = poreference;
        this.isdiscountprinted = isdiscountprinted;
        this.dateordered = dateordered;
        this.cCurrencyId = cCurrencyId;
        this.paymentrule = paymentrule;
        this.cPaymenttermId = cPaymenttermId;
        this.cChargeId = cChargeId;
        this.chargeamt = chargeamt;
        this.totallines = totallines;
        this.grandtotal = grandtotal;
        this.mPricelistId = mPricelistId;
        this.istaxincluded = istaxincluded;
        this.cCampaignId = cCampaignId;
        this.cProjectId = cProjectId;
        this.cActivityId = cActivityId;
        this.ispaid = ispaid;
        this.cPaymentId = cPaymentId;
        this.cCashlineId = cCashlineId;
        this.createfrom = createfrom;
        this.generateto = generateto;
        this.sendemail = sendemail;
        this.adUserId = adUserId;
        this.copyfrom = copyfrom;
        this.isselfservice = isselfservice;
        this.adOrgtrxId = adOrgtrxId;
        this.user1Id = user1Id;
        this.user2Id = user2Id;
        this.cConversiontypeId = cConversiontypeId;
        this.ispayschedulevalid = ispayschedulevalid;
        this.refInvoiceId = refInvoiceId;
        this.isindispute = isindispute;
        this.zsubpaymentruleId = zsubpaymentruleId;
        this.zbpinvoice = zbpinvoice;
        this.zPaymentcommunication = zPaymentcommunication;
        this.invoicecollectiontype = invoicecollectiontype;
        this.matchrequirementi = matchrequirementi;
        this.cBpBankaccountId = cBpBankaccountId;
        this.isreturntrx = isreturntrx;
        this.cBpartnersrId = cBpartnersrId;
        this.xxApplieddiscount = xxApplieddiscount;
        this.xxSealedinvoice = xxSealedinvoice;
        this.isdelivered = isdelivered;
        this.isarchived = isarchived;
        this.issms = issms;
    }

    /**
     * Gets adClientId
     * 
     * @return Value for adClientId.
     **/
    public long getAdClientId() {
        return adClientId;
    }

    /**
     * Sets adClientId
     * 
     * @param adClientId New value for adClientId.
     **/
    public void setAdClientId(long adClientId) {
        this.adClientId = adClientId;
    }

    /**
     * Gets adOrgId
     * 
     * @return Value for adOrgId.
     **/
    public long getAdOrgId() {
        return adOrgId;
    }

    /**
     * Sets adOrgId
     * 
     * @param adOrgId New value for adOrgId.
     **/
    public void setAdOrgId(long adOrgId) {
        this.adOrgId = adOrgId;
    }

    /**
     * Gets isactive
     * 
     * @return Value for isactive.
     **/
    public String getIsactive() {
        return isactive;
    }

    /**
     * Sets isactive
     * 
     * @param isactive New value for isactive.
     **/
    public void setIsactive(String isactive) {
        this.isactive = isactive;
    }

    /**
     * Gets created
     * 
     * @return Value for created.
     **/
    public Date getCreated() {
        return created;
    }

    /**
     * Sets created
     * 
     * @param created New value for created.
     **/
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * Gets createdby
     * 
     * @return Value for createdby.
     **/
    public long getCreatedby() {
        return createdby;
    }

    /**
     * Sets createdby
     * 
     * @param createdby New value for createdby.
     **/
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }

    /**
     * Gets updated
     * 
     * @return Value for updated.
     **/
    public Date getUpdated() {
        return updated;
    }

    /**
     * Sets updated
     * 
     * @param updated New value for updated.
     **/
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * Gets updatedby
     * 
     * @return Value for updatedby.
     **/
    public long getUpdatedby() {
        return updatedby;
    }

    /**
     * Sets updatedby
     * 
     * @param updatedby New value for updatedby.
     **/
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }

    /**
     * Gets issotrx
     * 
     * @return Value for issotrx.
     **/
    public String getIssotrx() {
        return issotrx;
    }

    /**
     * Sets issotrx
     * 
     * @param issotrx New value for issotrx.
     **/
    public void setIssotrx(String issotrx) {
        this.issotrx = issotrx;
    }

    /**
     * Gets documentno
     * 
     * @return Value for documentno.
     **/
    public String getDocumentno() {
        return documentno;
    }

    /**
     * Sets documentno
     * 
     * @param documentno New value for documentno.
     **/
    public void setDocumentno(String documentno) {
        this.documentno = documentno;
    }

    /**
     * Gets docstatus
     * 
     * @return Value for docstatus.
     **/
    public String getDocstatus() {
        return docstatus;
    }

    /**
     * Sets docstatus
     * 
     * @param docstatus New value for docstatus.
     **/
    public void setDocstatus(String docstatus) {
        this.docstatus = docstatus;
    }

    /**
     * Gets docaction
     * 
     * @return Value for docaction.
     **/
    public String getDocaction() {
        return docaction;
    }

    /**
     * Sets docaction
     * 
     * @param docaction New value for docaction.
     **/
    public void setDocaction(String docaction) {
        this.docaction = docaction;
    }

    /**
     * Gets processing
     * 
     * @return Value for processing.
     **/
    public String getProcessing() {
        return processing;
    }

    /**
     * Sets processing
     * 
     * @param processing New value for processing.
     **/
    public void setProcessing(String processing) {
        this.processing = processing;
    }

    /**
     * Gets processed
     * 
     * @return Value for processed.
     **/
    public String getProcessed() {
        return processed;
    }

    /**
     * Sets processed
     * 
     * @param processed New value for processed.
     **/
    public void setProcessed(String processed) {
        this.processed = processed;
    }

    /**
     * Gets posted
     * 
     * @return Value for posted.
     **/
    public String getPosted() {
        return posted;
    }

    /**
     * Sets posted
     * 
     * @param posted New value for posted.
     **/
    public void setPosted(String posted) {
        this.posted = posted;
    }

    /**
     * Gets cDoctypeId
     * 
     * @return Value for cDoctypeId.
     **/
    public long getCDoctypeId() {
        return cDoctypeId;
    }

    /**
     * Sets cDoctypeId
     * 
     * @param cDoctypeId New value for cDoctypeId.
     **/
    public void setCDoctypeId(long cDoctypeId) {
        this.cDoctypeId = cDoctypeId;
    }

    /**
     * Gets cDoctypetargetId
     * 
     * @return Value for cDoctypetargetId.
     **/
    public long getCDoctypetargetId() {
        return cDoctypetargetId;
    }

    /**
     * Sets cDoctypetargetId
     * 
     * @param cDoctypetargetId New value for cDoctypetargetId.
     **/
    public void setCDoctypetargetId(long cDoctypetargetId) {
        this.cDoctypetargetId = cDoctypetargetId;
    }

    /**
     * Gets cOrderId
     * 
     * @return Value for cOrderId.
     **/
    public Long getCOrderId() {
        return cOrderId;
    }

    /**
     * Sets cOrderId
     * 
     * @param cOrderId New value for cOrderId.
     **/
    public void setCOrderId(Long cOrderId) {
        this.cOrderId = cOrderId;
    }

    /**
     * Gets description
     * 
     * @return Value for description.
     **/
    public String getDescription() {
        return description;
    }

    /**
     * Sets description
     * 
     * @param description New value for description.
     **/
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Gets isapproved
     * 
     * @return Value for isapproved.
     **/
    public String getIsapproved() {
        return isapproved;
    }

    /**
     * Sets isapproved
     * 
     * @param isapproved New value for isapproved.
     **/
    public void setIsapproved(String isapproved) {
        this.isapproved = isapproved;
    }

    /**
     * Gets istransferred
     * 
     * @return Value for istransferred.
     **/
    public String getIstransferred() {
        return istransferred;
    }

    /**
     * Sets istransferred
     * 
     * @param istransferred New value for istransferred.
     **/
    public void setIstransferred(String istransferred) {
        this.istransferred = istransferred;
    }

    /**
     * Gets isprinted
     * 
     * @return Value for isprinted.
     **/
    public String getIsprinted() {
        return isprinted;
    }

    /**
     * Sets isprinted
     * 
     * @param isprinted New value for isprinted.
     **/
    public void setIsprinted(String isprinted) {
        this.isprinted = isprinted;
    }

    /**
     * Gets salesrepId
     * 
     * @return Value for salesrepId.
     **/
    public Long getSalesrepId() {
        return salesrepId;
    }

    /**
     * Sets salesrepId
     * 
     * @param salesrepId New value for salesrepId.
     **/
    public void setSalesrepId(Long salesrepId) {
        this.salesrepId = salesrepId;
    }

    /**
     * Gets dateinvoiced
     * 
     * @return Value for dateinvoiced.
     **/
    public Date getDateinvoiced() {
        return dateinvoiced;
    }

    /**
     * Sets dateinvoiced
     * 
     * @param dateinvoiced New value for dateinvoiced.
     **/
    public void setDateinvoiced(Date dateinvoiced) {
        this.dateinvoiced = dateinvoiced;
    }

    /**
     * Gets dateprinted
     * 
     * @return Value for dateprinted.
     **/
    public Date getDateprinted() {
        return dateprinted;
    }

    /**
     * Sets dateprinted
     * 
     * @param dateprinted New value for dateprinted.
     **/
    public void setDateprinted(Date dateprinted) {
        this.dateprinted = dateprinted;
    }

    /**
     * Gets dateacct
     * 
     * @return Value for dateacct.
     **/
    public Date getDateacct() {
        return dateacct;
    }

    /**
     * Sets dateacct
     * 
     * @param dateacct New value for dateacct.
     **/
    public void setDateacct(Date dateacct) {
        this.dateacct = dateacct;
    }

    /**
     * Gets cBpartnerId
     * 
     * @return Value for cBpartnerId.
     **/
    public long getCBpartnerId() {
        return cBpartnerId;
    }

    /**
     * Sets cBpartnerId
     * 
     * @param cBpartnerId New value for cBpartnerId.
     **/
    public void setCBpartnerId(long cBpartnerId) {
        this.cBpartnerId = cBpartnerId;
    }

    /**
     * Gets cBpartnerLocationId
     * 
     * @return Value for cBpartnerLocationId.
     **/
    public long getCBpartnerLocationId() {
        return cBpartnerLocationId;
    }

    /**
     * Sets cBpartnerLocationId
     * 
     * @param cBpartnerLocationId New value for cBpartnerLocationId.
     **/
    public void setCBpartnerLocationId(long cBpartnerLocationId) {
        this.cBpartnerLocationId = cBpartnerLocationId;
    }

    /**
     * Gets poreference
     * 
     * @return Value for poreference.
     **/
    public String getPoreference() {
        return poreference;
    }

    /**
     * Sets poreference
     * 
     * @param poreference New value for poreference.
     **/
    public void setPoreference(String poreference) {
        this.poreference = poreference;
    }

    /**
     * Gets isdiscountprinted
     * 
     * @return Value for isdiscountprinted.
     **/
    public String getIsdiscountprinted() {
        return isdiscountprinted;
    }

    /**
     * Sets isdiscountprinted
     * 
     * @param isdiscountprinted New value for isdiscountprinted.
     **/
    public void setIsdiscountprinted(String isdiscountprinted) {
        this.isdiscountprinted = isdiscountprinted;
    }

    /**
     * Gets dateordered
     * 
     * @return Value for dateordered.
     **/
    public Date getDateordered() {
        return dateordered;
    }

    /**
     * Sets dateordered
     * 
     * @param dateordered New value for dateordered.
     **/
    public void setDateordered(Date dateordered) {
        this.dateordered = dateordered;
    }

    /**
     * Gets cCurrencyId
     * 
     * @return Value for cCurrencyId.
     **/
    public long getCCurrencyId() {
        return cCurrencyId;
    }

    /**
     * Sets cCurrencyId
     * 
     * @param cCurrencyId New value for cCurrencyId.
     **/
    public void setCCurrencyId(long cCurrencyId) {
        this.cCurrencyId = cCurrencyId;
    }

    /**
     * Gets paymentrule
     * 
     * @return Value for paymentrule.
     **/
    public String getPaymentrule() {
        return paymentrule;
    }

    /**
     * Sets paymentrule
     * 
     * @param paymentrule New value for paymentrule.
     **/
    public void setPaymentrule(String paymentrule) {
        this.paymentrule = paymentrule;
    }

    /**
     * Gets cPaymenttermId
     * 
     * @return Value for cPaymenttermId.
     **/
    public long getCPaymenttermId() {
        return cPaymenttermId;
    }

    /**
     * Sets cPaymenttermId
     * 
     * @param cPaymenttermId New value for cPaymenttermId.
     **/
    public void setCPaymenttermId(long cPaymenttermId) {
        this.cPaymenttermId = cPaymenttermId;
    }

    /**
     * Gets cChargeId
     * 
     * @return Value for cChargeId.
     **/
    public Long getCChargeId() {
        return cChargeId;
    }

    /**
     * Sets cChargeId
     * 
     * @param cChargeId New value for cChargeId.
     **/
    public void setCChargeId(Long cChargeId) {
        this.cChargeId = cChargeId;
    }

    /**
     * Gets chargeamt
     * 
     * @return Value for chargeamt.
     **/
    public BigDecimal getChargeamt() {
        return chargeamt;
    }

    /**
     * Sets chargeamt
     * 
     * @param chargeamt New value for chargeamt.
     **/
    public void setChargeamt(BigDecimal chargeamt) {
        this.chargeamt = chargeamt;
    }

    /**
     * Gets totallines
     * 
     * @return Value for totallines.
     **/
    public BigDecimal getTotallines() {
        return totallines;
    }

    /**
     * Sets totallines
     * 
     * @param totallines New value for totallines.
     **/
    public void setTotallines(BigDecimal totallines) {
        this.totallines = totallines;
    }

    /**
     * Gets grandtotal
     * 
     * @return Value for grandtotal.
     **/
    public BigDecimal getGrandtotal() {
        return grandtotal;
    }

    /**
     * Sets grandtotal
     * 
     * @param grandtotal New value for grandtotal.
     **/
    public void setGrandtotal(BigDecimal grandtotal) {
        this.grandtotal = grandtotal;
    }

    /**
     * Gets mPricelistId
     * 
     * @return Value for mPricelistId.
     **/
    public long getMPricelistId() {
        return mPricelistId;
    }

    /**
     * Sets mPricelistId
     * 
     * @param mPricelistId New value for mPricelistId.
     **/
    public void setMPricelistId(long mPricelistId) {
        this.mPricelistId = mPricelistId;
    }

    /**
     * Gets istaxincluded
     * 
     * @return Value for istaxincluded.
     **/
    public String getIstaxincluded() {
        return istaxincluded;
    }

    /**
     * Sets istaxincluded
     * 
     * @param istaxincluded New value for istaxincluded.
     **/
    public void setIstaxincluded(String istaxincluded) {
        this.istaxincluded = istaxincluded;
    }

    /**
     * Gets cCampaignId
     * 
     * @return Value for cCampaignId.
     **/
    public Long getCCampaignId() {
        return cCampaignId;
    }

    /**
     * Sets cCampaignId
     * 
     * @param cCampaignId New value for cCampaignId.
     **/
    public void setCCampaignId(Long cCampaignId) {
        this.cCampaignId = cCampaignId;
    }

    /**
     * Gets cProjectId
     * 
     * @return Value for cProjectId.
     **/
    public Long getCProjectId() {
        return cProjectId;
    }

    /**
     * Sets cProjectId
     * 
     * @param cProjectId New value for cProjectId.
     **/
    public void setCProjectId(Long cProjectId) {
        this.cProjectId = cProjectId;
    }

    /**
     * Gets cActivityId
     * 
     * @return Value for cActivityId.
     **/
    public Long getCActivityId() {
        return cActivityId;
    }

    /**
     * Sets cActivityId
     * 
     * @param cActivityId New value for cActivityId.
     **/
    public void setCActivityId(Long cActivityId) {
        this.cActivityId = cActivityId;
    }

    /**
     * Gets ispaid
     * 
     * @return Value for ispaid.
     **/
    public String getIspaid() {
        return ispaid;
    }

    /**
     * Sets ispaid
     * 
     * @param ispaid New value for ispaid.
     **/
    public void setIspaid(String ispaid) {
        this.ispaid = ispaid;
    }

    /**
     * Gets cPaymentId
     * 
     * @return Value for cPaymentId.
     **/
    public Long getCPaymentId() {
        return cPaymentId;
    }

    /**
     * Sets cPaymentId
     * 
     * @param cPaymentId New value for cPaymentId.
     **/
    public void setCPaymentId(Long cPaymentId) {
        this.cPaymentId = cPaymentId;
    }

    /**
     * Gets cCashlineId
     * 
     * @return Value for cCashlineId.
     **/
    public Long getCCashlineId() {
        return cCashlineId;
    }

    /**
     * Sets cCashlineId
     * 
     * @param cCashlineId New value for cCashlineId.
     **/
    public void setCCashlineId(Long cCashlineId) {
        this.cCashlineId = cCashlineId;
    }

    /**
     * Gets createfrom
     * 
     * @return Value for createfrom.
     **/
    public String getCreatefrom() {
        return createfrom;
    }

    /**
     * Sets createfrom
     * 
     * @param createfrom New value for createfrom.
     **/
    public void setCreatefrom(String createfrom) {
        this.createfrom = createfrom;
    }

    /**
     * Gets generateto
     * 
     * @return Value for generateto.
     **/
    public String getGenerateto() {
        return generateto;
    }

    /**
     * Sets generateto
     * 
     * @param generateto New value for generateto.
     **/
    public void setGenerateto(String generateto) {
        this.generateto = generateto;
    }

    /**
     * Gets sendemail
     * 
     * @return Value for sendemail.
     **/
    public String getSendemail() {
        return sendemail;
    }

    /**
     * Sets sendemail
     * 
     * @param sendemail New value for sendemail.
     **/
    public void setSendemail(String sendemail) {
        this.sendemail = sendemail;
    }

    /**
     * Gets adUserId
     * 
     * @return Value for adUserId.
     **/
    public Long getAdUserId() {
        return adUserId;
    }

    /**
     * Sets adUserId
     * 
     * @param adUserId New value for adUserId.
     **/
    public void setAdUserId(Long adUserId) {
        this.adUserId = adUserId;
    }

    /**
     * Gets copyfrom
     * 
     * @return Value for copyfrom.
     **/
    public String getCopyfrom() {
        return copyfrom;
    }

    /**
     * Sets copyfrom
     * 
     * @param copyfrom New value for copyfrom.
     **/
    public void setCopyfrom(String copyfrom) {
        this.copyfrom = copyfrom;
    }

    /**
     * Gets isselfservice
     * 
     * @return Value for isselfservice.
     **/
    public String getIsselfservice() {
        return isselfservice;
    }

    /**
     * Sets isselfservice
     * 
     * @param isselfservice New value for isselfservice.
     **/
    public void setIsselfservice(String isselfservice) {
        this.isselfservice = isselfservice;
    }

    /**
     * Gets adOrgtrxId
     * 
     * @return Value for adOrgtrxId.
     **/
    public Long getAdOrgtrxId() {
        return adOrgtrxId;
    }

    /**
     * Sets adOrgtrxId
     * 
     * @param adOrgtrxId New value for adOrgtrxId.
     **/
    public void setAdOrgtrxId(Long adOrgtrxId) {
        this.adOrgtrxId = adOrgtrxId;
    }

    /**
     * Gets user1Id
     * 
     * @return Value for user1Id.
     **/
    public Long getUser1Id() {
        return user1Id;
    }

    /**
     * Sets user1Id
     * 
     * @param user1Id New value for user1Id.
     **/
    public void setUser1Id(Long user1Id) {
        this.user1Id = user1Id;
    }

    /**
     * Gets user2Id
     * 
     * @return Value for user2Id.
     **/
    public Long getUser2Id() {
        return user2Id;
    }

    /**
     * Sets user2Id
     * 
     * @param user2Id New value for user2Id.
     **/
    public void setUser2Id(Long user2Id) {
        this.user2Id = user2Id;
    }

    /**
     * Gets cConversiontypeId
     * 
     * @return Value for cConversiontypeId.
     **/
    public Long getCConversiontypeId() {
        return cConversiontypeId;
    }

    /**
     * Sets cConversiontypeId
     * 
     * @param cConversiontypeId New value for cConversiontypeId.
     **/
    public void setCConversiontypeId(Long cConversiontypeId) {
        this.cConversiontypeId = cConversiontypeId;
    }

    /**
     * Gets ispayschedulevalid
     * 
     * @return Value for ispayschedulevalid.
     **/
    public String getIspayschedulevalid() {
        return ispayschedulevalid;
    }

    /**
     * Sets ispayschedulevalid
     * 
     * @param ispayschedulevalid New value for ispayschedulevalid.
     **/
    public void setIspayschedulevalid(String ispayschedulevalid) {
        this.ispayschedulevalid = ispayschedulevalid;
    }

    /**
     * Gets refInvoiceId
     * 
     * @return Value for refInvoiceId.
     **/
    public Long getRefInvoiceId() {
        return refInvoiceId;
    }

    /**
     * Sets refInvoiceId
     * 
     * @param refInvoiceId New value for refInvoiceId.
     **/
    public void setRefInvoiceId(Long refInvoiceId) {
        this.refInvoiceId = refInvoiceId;
    }

    /**
     * Gets isindispute
     * 
     * @return Value for isindispute.
     **/
    public String getIsindispute() {
        return isindispute;
    }

    /**
     * Sets isindispute
     * 
     * @param isindispute New value for isindispute.
     **/
    public void setIsindispute(String isindispute) {
        this.isindispute = isindispute;
    }

    /**
     * Gets zsubpaymentruleId
     * 
     * @return Value for zsubpaymentruleId.
     **/
    public Long getZsubpaymentruleId() {
        return zsubpaymentruleId;
    }

    /**
     * Sets zsubpaymentruleId
     * 
     * @param zsubpaymentruleId New value for zsubpaymentruleId.
     **/
    public void setZsubpaymentruleId(Long zsubpaymentruleId) {
        this.zsubpaymentruleId = zsubpaymentruleId;
    }

    /**
     * Gets zbpinvoice
     * 
     * @return Value for zbpinvoice.
     **/
    public String getZbpinvoice() {
        return zbpinvoice;
    }

    /**
     * Sets zbpinvoice
     * 
     * @param zbpinvoice New value for zbpinvoice.
     **/
    public void setZbpinvoice(String zbpinvoice) {
        this.zbpinvoice = zbpinvoice;
    }

    /**
     * Gets zPaymentcommunication
     * 
     * @return Value for zPaymentcommunication.
     **/
    public String getZPaymentcommunication() {
        return zPaymentcommunication;
    }

    /**
     * Sets zPaymentcommunication
     * 
     * @param zPaymentcommunication New value for zPaymentcommunication.
     **/
    public void setZPaymentcommunication(String zPaymentcommunication) {
        this.zPaymentcommunication = zPaymentcommunication;
    }

    /**
     * Gets invoicecollectiontype
     * 
     * @return Value for invoicecollectiontype.
     **/
    public String getInvoicecollectiontype() {
        return invoicecollectiontype;
    }

    /**
     * Sets invoicecollectiontype
     * 
     * @param invoicecollectiontype New value for invoicecollectiontype.
     **/
    public void setInvoicecollectiontype(String invoicecollectiontype) {
        this.invoicecollectiontype = invoicecollectiontype;
    }

    /**
     * Gets matchrequirementi
     * 
     * @return Value for matchrequirementi.
     **/
    public String getMatchrequirementi() {
        return matchrequirementi;
    }

    /**
     * Sets matchrequirementi
     * 
     * @param matchrequirementi New value for matchrequirementi.
     **/
    public void setMatchrequirementi(String matchrequirementi) {
        this.matchrequirementi = matchrequirementi;
    }

    /**
     * Gets cBpBankaccountId
     * 
     * @return Value for cBpBankaccountId.
     **/
    public Long getCBpBankaccountId() {
        return cBpBankaccountId;
    }

    /**
     * Sets cBpBankaccountId
     * 
     * @param cBpBankaccountId New value for cBpBankaccountId.
     **/
    public void setCBpBankaccountId(Long cBpBankaccountId) {
        this.cBpBankaccountId = cBpBankaccountId;
    }

    /**
     * Gets isreturntrx
     * 
     * @return Value for isreturntrx.
     **/
    public String getIsreturntrx() {
        return isreturntrx;
    }

    /**
     * Sets isreturntrx
     * 
     * @param isreturntrx New value for isreturntrx.
     **/
    public void setIsreturntrx(String isreturntrx) {
        this.isreturntrx = isreturntrx;
    }

    /**
     * Gets cBpartnersrId
     * 
     * @return Value for cBpartnersrId.
     **/
    public Long getCBpartnersrId() {
        return cBpartnersrId;
    }

    /**
     * Sets cBpartnersrId
     * 
     * @param cBpartnersrId New value for cBpartnersrId.
     **/
    public void setCBpartnersrId(Long cBpartnersrId) {
        this.cBpartnersrId = cBpartnersrId;
    }

    /**
     * Gets xxApplieddiscount
     * 
     * @return Value for xxApplieddiscount.
     **/
    public String getXxApplieddiscount() {
        return xxApplieddiscount;
    }

    /**
     * Sets xxApplieddiscount
     * 
     * @param xxApplieddiscount New value for xxApplieddiscount.
     **/
    public void setXxApplieddiscount(String xxApplieddiscount) {
        this.xxApplieddiscount = xxApplieddiscount;
    }

    /**
     * Gets xxSealedinvoice
     * 
     * @return Value for xxSealedinvoice.
     **/
    public String getXxSealedinvoice() {
        return xxSealedinvoice;
    }

    /**
     * Sets xxSealedinvoice
     * 
     * @param xxSealedinvoice New value for xxSealedinvoice.
     **/
    public void setXxSealedinvoice(String xxSealedinvoice) {
        this.xxSealedinvoice = xxSealedinvoice;
    }

    /**
     * Gets isdelivered
     * 
     * @return Value for isdelivered.
     **/
    public String getIsdelivered() {
        return isdelivered;
    }

    /**
     * Sets isdelivered
     * 
     * @param isdelivered New value for isdelivered.
     **/
    public void setIsdelivered(String isdelivered) {
        this.isdelivered = isdelivered;
    }

    /**
     * Gets isarchived
     * 
     * @return Value for isarchived.
     **/
    public String getIsarchived() {
        return isarchived;
    }

    /**
     * Sets isarchived
     * 
     * @param isarchived New value for isarchived.
     **/
    public void setIsarchived(String isarchived) {
        this.isarchived = isarchived;
    }

    /**
     * Gets issms
     * 
     * @return Value for issms.
     **/
    public String getIssms() {
        return issms;
    }

    /**
     * Sets issms
     * 
     * @param issms New value for issms.
     **/
    public void setIssms(String issms) {
        this.issms = issms;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof CInvoice))
            return false;
        
        CInvoice that = (CInvoice)o;

        if (adClientId != that.adClientId)
            return false;
        

        if (adOrgId != that.adOrgId)
            return false;
        

        if (isactive != null ? !isactive.equals(that.isactive) : that.isactive != null)
            return false;
        

        if (created != null ? !created.equals(that.created) : that.created != null)
            return false;
        

        if (createdby != that.createdby)
            return false;
        

        if (updated != null ? !updated.equals(that.updated) : that.updated != null)
            return false;
        

        if (updatedby != that.updatedby)
            return false;
        

        if (issotrx != null ? !issotrx.equals(that.issotrx) : that.issotrx != null)
            return false;
        

        if (documentno != null ? !documentno.equals(that.documentno) : that.documentno != null)
            return false;
        

        if (docstatus != null ? !docstatus.equals(that.docstatus) : that.docstatus != null)
            return false;
        

        if (docaction != null ? !docaction.equals(that.docaction) : that.docaction != null)
            return false;
        

        if (processing != null ? !processing.equals(that.processing) : that.processing != null)
            return false;
        

        if (processed != null ? !processed.equals(that.processed) : that.processed != null)
            return false;
        

        if (posted != null ? !posted.equals(that.posted) : that.posted != null)
            return false;
        

        if (cDoctypeId != that.cDoctypeId)
            return false;
        

        if (cDoctypetargetId != that.cDoctypetargetId)
            return false;
        

        if (cOrderId != null ? !cOrderId.equals(that.cOrderId) : that.cOrderId != null)
            return false;
        

        if (description != null ? !description.equals(that.description) : that.description != null)
            return false;
        

        if (isapproved != null ? !isapproved.equals(that.isapproved) : that.isapproved != null)
            return false;
        

        if (istransferred != null ? !istransferred.equals(that.istransferred) : that.istransferred != null)
            return false;
        

        if (isprinted != null ? !isprinted.equals(that.isprinted) : that.isprinted != null)
            return false;
        

        if (salesrepId != null ? !salesrepId.equals(that.salesrepId) : that.salesrepId != null)
            return false;
        

        if (dateinvoiced != null ? !dateinvoiced.equals(that.dateinvoiced) : that.dateinvoiced != null)
            return false;
        

        if (dateprinted != null ? !dateprinted.equals(that.dateprinted) : that.dateprinted != null)
            return false;
        

        if (dateacct != null ? !dateacct.equals(that.dateacct) : that.dateacct != null)
            return false;
        

        if (cBpartnerId != that.cBpartnerId)
            return false;
        

        if (cBpartnerLocationId != that.cBpartnerLocationId)
            return false;
        

        if (poreference != null ? !poreference.equals(that.poreference) : that.poreference != null)
            return false;
        

        if (isdiscountprinted != null ? !isdiscountprinted.equals(that.isdiscountprinted) : that.isdiscountprinted != null)
            return false;
        

        if (dateordered != null ? !dateordered.equals(that.dateordered) : that.dateordered != null)
            return false;
        

        if (cCurrencyId != that.cCurrencyId)
            return false;
        

        if (paymentrule != null ? !paymentrule.equals(that.paymentrule) : that.paymentrule != null)
            return false;
        

        if (cPaymenttermId != that.cPaymenttermId)
            return false;
        

        if (cChargeId != null ? !cChargeId.equals(that.cChargeId) : that.cChargeId != null)
            return false;
        

        if (chargeamt != null ? !chargeamt.equals(that.chargeamt) : that.chargeamt != null)
            return false;
        

        if (totallines != null ? !totallines.equals(that.totallines) : that.totallines != null)
            return false;
        

        if (grandtotal != null ? !grandtotal.equals(that.grandtotal) : that.grandtotal != null)
            return false;
        

        if (mPricelistId != that.mPricelistId)
            return false;
        

        if (istaxincluded != null ? !istaxincluded.equals(that.istaxincluded) : that.istaxincluded != null)
            return false;
        

        if (cCampaignId != null ? !cCampaignId.equals(that.cCampaignId) : that.cCampaignId != null)
            return false;
        

        if (cProjectId != null ? !cProjectId.equals(that.cProjectId) : that.cProjectId != null)
            return false;
        

        if (cActivityId != null ? !cActivityId.equals(that.cActivityId) : that.cActivityId != null)
            return false;
        

        if (ispaid != null ? !ispaid.equals(that.ispaid) : that.ispaid != null)
            return false;
        

        if (cPaymentId != null ? !cPaymentId.equals(that.cPaymentId) : that.cPaymentId != null)
            return false;
        

        if (cCashlineId != null ? !cCashlineId.equals(that.cCashlineId) : that.cCashlineId != null)
            return false;
        

        if (createfrom != null ? !createfrom.equals(that.createfrom) : that.createfrom != null)
            return false;
        

        if (generateto != null ? !generateto.equals(that.generateto) : that.generateto != null)
            return false;
        

        if (sendemail != null ? !sendemail.equals(that.sendemail) : that.sendemail != null)
            return false;
        

        if (adUserId != null ? !adUserId.equals(that.adUserId) : that.adUserId != null)
            return false;
        

        if (copyfrom != null ? !copyfrom.equals(that.copyfrom) : that.copyfrom != null)
            return false;
        

        if (isselfservice != null ? !isselfservice.equals(that.isselfservice) : that.isselfservice != null)
            return false;
        

        if (adOrgtrxId != null ? !adOrgtrxId.equals(that.adOrgtrxId) : that.adOrgtrxId != null)
            return false;
        

        if (user1Id != null ? !user1Id.equals(that.user1Id) : that.user1Id != null)
            return false;
        

        if (user2Id != null ? !user2Id.equals(that.user2Id) : that.user2Id != null)
            return false;
        

        if (cConversiontypeId != null ? !cConversiontypeId.equals(that.cConversiontypeId) : that.cConversiontypeId != null)
            return false;
        

        if (ispayschedulevalid != null ? !ispayschedulevalid.equals(that.ispayschedulevalid) : that.ispayschedulevalid != null)
            return false;
        

        if (refInvoiceId != null ? !refInvoiceId.equals(that.refInvoiceId) : that.refInvoiceId != null)
            return false;
        

        if (isindispute != null ? !isindispute.equals(that.isindispute) : that.isindispute != null)
            return false;
        

        if (zsubpaymentruleId != null ? !zsubpaymentruleId.equals(that.zsubpaymentruleId) : that.zsubpaymentruleId != null)
            return false;
        

        if (zbpinvoice != null ? !zbpinvoice.equals(that.zbpinvoice) : that.zbpinvoice != null)
            return false;
        

        if (zPaymentcommunication != null ? !zPaymentcommunication.equals(that.zPaymentcommunication) : that.zPaymentcommunication != null)
            return false;
        

        if (invoicecollectiontype != null ? !invoicecollectiontype.equals(that.invoicecollectiontype) : that.invoicecollectiontype != null)
            return false;
        

        if (matchrequirementi != null ? !matchrequirementi.equals(that.matchrequirementi) : that.matchrequirementi != null)
            return false;
        

        if (cBpBankaccountId != null ? !cBpBankaccountId.equals(that.cBpBankaccountId) : that.cBpBankaccountId != null)
            return false;
        

        if (isreturntrx != null ? !isreturntrx.equals(that.isreturntrx) : that.isreturntrx != null)
            return false;
        

        if (cBpartnersrId != null ? !cBpartnersrId.equals(that.cBpartnersrId) : that.cBpartnersrId != null)
            return false;
        

        if (xxApplieddiscount != null ? !xxApplieddiscount.equals(that.xxApplieddiscount) : that.xxApplieddiscount != null)
            return false;
        

        if (xxSealedinvoice != null ? !xxSealedinvoice.equals(that.xxSealedinvoice) : that.xxSealedinvoice != null)
            return false;
        

        if (isdelivered != null ? !isdelivered.equals(that.isdelivered) : that.isdelivered != null)
            return false;
        

        if (isarchived != null ? !isarchived.equals(that.isarchived) : that.isarchived != null)
            return false;
        

        if (issms != null ? !issms.equals(that.issms) : that.issms != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = (int)(adClientId ^ (adClientId >>> 32));

        res = 31 * res + (int)(adOrgId ^ (adOrgId >>> 32));

        res = 31 * res + (isactive != null ? isactive.hashCode() : 0);

        res = 31 * res + (created != null ? created.hashCode() : 0);

        res = 31 * res + (int)(createdby ^ (createdby >>> 32));

        res = 31 * res + (updated != null ? updated.hashCode() : 0);

        res = 31 * res + (int)(updatedby ^ (updatedby >>> 32));

        res = 31 * res + (issotrx != null ? issotrx.hashCode() : 0);

        res = 31 * res + (documentno != null ? documentno.hashCode() : 0);

        res = 31 * res + (docstatus != null ? docstatus.hashCode() : 0);

        res = 31 * res + (docaction != null ? docaction.hashCode() : 0);

        res = 31 * res + (processing != null ? processing.hashCode() : 0);

        res = 31 * res + (processed != null ? processed.hashCode() : 0);

        res = 31 * res + (posted != null ? posted.hashCode() : 0);

        res = 31 * res + (int)(cDoctypeId ^ (cDoctypeId >>> 32));

        res = 31 * res + (int)(cDoctypetargetId ^ (cDoctypetargetId >>> 32));

        res = 31 * res + (cOrderId != null ? cOrderId.hashCode() : 0);

        res = 31 * res + (description != null ? description.hashCode() : 0);

        res = 31 * res + (isapproved != null ? isapproved.hashCode() : 0);

        res = 31 * res + (istransferred != null ? istransferred.hashCode() : 0);

        res = 31 * res + (isprinted != null ? isprinted.hashCode() : 0);

        res = 31 * res + (salesrepId != null ? salesrepId.hashCode() : 0);

        res = 31 * res + (dateinvoiced != null ? dateinvoiced.hashCode() : 0);

        res = 31 * res + (dateprinted != null ? dateprinted.hashCode() : 0);

        res = 31 * res + (dateacct != null ? dateacct.hashCode() : 0);

        res = 31 * res + (int)(cBpartnerId ^ (cBpartnerId >>> 32));

        res = 31 * res + (int)(cBpartnerLocationId ^ (cBpartnerLocationId >>> 32));

        res = 31 * res + (poreference != null ? poreference.hashCode() : 0);

        res = 31 * res + (isdiscountprinted != null ? isdiscountprinted.hashCode() : 0);

        res = 31 * res + (dateordered != null ? dateordered.hashCode() : 0);

        res = 31 * res + (int)(cCurrencyId ^ (cCurrencyId >>> 32));

        res = 31 * res + (paymentrule != null ? paymentrule.hashCode() : 0);

        res = 31 * res + (int)(cPaymenttermId ^ (cPaymenttermId >>> 32));

        res = 31 * res + (cChargeId != null ? cChargeId.hashCode() : 0);

        res = 31 * res + (chargeamt != null ? chargeamt.hashCode() : 0);

        res = 31 * res + (totallines != null ? totallines.hashCode() : 0);

        res = 31 * res + (grandtotal != null ? grandtotal.hashCode() : 0);

        res = 31 * res + (int)(mPricelistId ^ (mPricelistId >>> 32));

        res = 31 * res + (istaxincluded != null ? istaxincluded.hashCode() : 0);

        res = 31 * res + (cCampaignId != null ? cCampaignId.hashCode() : 0);

        res = 31 * res + (cProjectId != null ? cProjectId.hashCode() : 0);

        res = 31 * res + (cActivityId != null ? cActivityId.hashCode() : 0);

        res = 31 * res + (ispaid != null ? ispaid.hashCode() : 0);

        res = 31 * res + (cPaymentId != null ? cPaymentId.hashCode() : 0);

        res = 31 * res + (cCashlineId != null ? cCashlineId.hashCode() : 0);

        res = 31 * res + (createfrom != null ? createfrom.hashCode() : 0);

        res = 31 * res + (generateto != null ? generateto.hashCode() : 0);

        res = 31 * res + (sendemail != null ? sendemail.hashCode() : 0);

        res = 31 * res + (adUserId != null ? adUserId.hashCode() : 0);

        res = 31 * res + (copyfrom != null ? copyfrom.hashCode() : 0);

        res = 31 * res + (isselfservice != null ? isselfservice.hashCode() : 0);

        res = 31 * res + (adOrgtrxId != null ? adOrgtrxId.hashCode() : 0);

        res = 31 * res + (user1Id != null ? user1Id.hashCode() : 0);

        res = 31 * res + (user2Id != null ? user2Id.hashCode() : 0);

        res = 31 * res + (cConversiontypeId != null ? cConversiontypeId.hashCode() : 0);

        res = 31 * res + (ispayschedulevalid != null ? ispayschedulevalid.hashCode() : 0);

        res = 31 * res + (refInvoiceId != null ? refInvoiceId.hashCode() : 0);

        res = 31 * res + (isindispute != null ? isindispute.hashCode() : 0);

        res = 31 * res + (zsubpaymentruleId != null ? zsubpaymentruleId.hashCode() : 0);

        res = 31 * res + (zbpinvoice != null ? zbpinvoice.hashCode() : 0);

        res = 31 * res + (zPaymentcommunication != null ? zPaymentcommunication.hashCode() : 0);

        res = 31 * res + (invoicecollectiontype != null ? invoicecollectiontype.hashCode() : 0);

        res = 31 * res + (matchrequirementi != null ? matchrequirementi.hashCode() : 0);

        res = 31 * res + (cBpBankaccountId != null ? cBpBankaccountId.hashCode() : 0);

        res = 31 * res + (isreturntrx != null ? isreturntrx.hashCode() : 0);

        res = 31 * res + (cBpartnersrId != null ? cBpartnersrId.hashCode() : 0);

        res = 31 * res + (xxApplieddiscount != null ? xxApplieddiscount.hashCode() : 0);

        res = 31 * res + (xxSealedinvoice != null ? xxSealedinvoice.hashCode() : 0);

        res = 31 * res + (isdelivered != null ? isdelivered.hashCode() : 0);

        res = 31 * res + (isarchived != null ? isarchived.hashCode() : 0);

        res = 31 * res + (issms != null ? issms.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "CInvoice [" + 
            "adClientId=" + adClientId + ", " + 
            "adOrgId=" + adOrgId + ", " + 
            "isactive=" + isactive + ", " + 
            "created=" + created + ", " + 
            "createdby=" + createdby + ", " + 
            "updated=" + updated + ", " + 
            "updatedby=" + updatedby + ", " + 
            "issotrx=" + issotrx + ", " + 
            "documentno=" + documentno + ", " + 
            "docstatus=" + docstatus + ", " + 
            "docaction=" + docaction + ", " + 
            "processing=" + processing + ", " + 
            "processed=" + processed + ", " + 
            "posted=" + posted + ", " + 
            "cDoctypeId=" + cDoctypeId + ", " + 
            "cDoctypetargetId=" + cDoctypetargetId + ", " + 
            "cOrderId=" + cOrderId + ", " + 
            "description=" + description + ", " + 
            "isapproved=" + isapproved + ", " + 
            "istransferred=" + istransferred + ", " + 
            "isprinted=" + isprinted + ", " + 
            "salesrepId=" + salesrepId + ", " + 
            "dateinvoiced=" + dateinvoiced + ", " + 
            "dateprinted=" + dateprinted + ", " + 
            "dateacct=" + dateacct + ", " + 
            "cBpartnerId=" + cBpartnerId + ", " + 
            "cBpartnerLocationId=" + cBpartnerLocationId + ", " + 
            "poreference=" + poreference + ", " + 
            "isdiscountprinted=" + isdiscountprinted + ", " + 
            "dateordered=" + dateordered + ", " + 
            "cCurrencyId=" + cCurrencyId + ", " + 
            "paymentrule=" + paymentrule + ", " + 
            "cPaymenttermId=" + cPaymenttermId + ", " + 
            "cChargeId=" + cChargeId + ", " + 
            "chargeamt=" + chargeamt + ", " + 
            "totallines=" + totallines + ", " + 
            "grandtotal=" + grandtotal + ", " + 
            "mPricelistId=" + mPricelistId + ", " + 
            "istaxincluded=" + istaxincluded + ", " + 
            "cCampaignId=" + cCampaignId + ", " + 
            "cProjectId=" + cProjectId + ", " + 
            "cActivityId=" + cActivityId + ", " + 
            "ispaid=" + ispaid + ", " + 
            "cPaymentId=" + cPaymentId + ", " + 
            "cCashlineId=" + cCashlineId + ", " + 
            "createfrom=" + createfrom + ", " + 
            "generateto=" + generateto + ", " + 
            "sendemail=" + sendemail + ", " + 
            "adUserId=" + adUserId + ", " + 
            "copyfrom=" + copyfrom + ", " + 
            "isselfservice=" + isselfservice + ", " + 
            "adOrgtrxId=" + adOrgtrxId + ", " + 
            "user1Id=" + user1Id + ", " + 
            "user2Id=" + user2Id + ", " + 
            "cConversiontypeId=" + cConversiontypeId + ", " + 
            "ispayschedulevalid=" + ispayschedulevalid + ", " + 
            "refInvoiceId=" + refInvoiceId + ", " + 
            "isindispute=" + isindispute + ", " + 
            "zsubpaymentruleId=" + zsubpaymentruleId + ", " + 
            "zbpinvoice=" + zbpinvoice + ", " + 
            "zPaymentcommunication=" + zPaymentcommunication + ", " + 
            "invoicecollectiontype=" + invoicecollectiontype + ", " + 
            "matchrequirementi=" + matchrequirementi + ", " + 
            "cBpBankaccountId=" + cBpBankaccountId + ", " + 
            "isreturntrx=" + isreturntrx + ", " + 
            "cBpartnersrId=" + cBpartnersrId + ", " + 
            "xxApplieddiscount=" + xxApplieddiscount + ", " + 
            "xxSealedinvoice=" + xxSealedinvoice + ", " + 
            "isdelivered=" + isdelivered + ", " + 
            "isarchived=" + isarchived + ", " + 
            "issms=" + issms +
        "]";
    }
}