package com.wanasis.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;

/**
 * CInvoiceline definition.
 * 
 * This file was generated by Ignite Web Console (11/21/2019, 08:54)
 **/
public class CInvoiceline implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for adClientId. */
    private long adClientId;

    /** Value for adOrgId. */
    private long adOrgId;

    /** Value for isactive. */
    private String isactive;

    /** Value for created. */
    private Date created;

    /** Value for createdby. */
    private long createdby;

    /** Value for updated. */
    private Date updated;

    /** Value for updatedby. */
    private long updatedby;

    /** Value for cInvoiceId. */
    private long cInvoiceId;

    /** Value for cOrderlineId. */
    private Long cOrderlineId;

    /** Value for mInoutlineId. */
    private Long mInoutlineId;

    /** Value for line. */
    private long line;

    /** Value for description. */
    private String description;

    /** Value for mProductId. */
    private Long mProductId;

    /** Value for qtyinvoiced. */
    private BigDecimal qtyinvoiced;

    /** Value for pricelist. */
    private BigDecimal pricelist;

    /** Value for priceactual. */
    private BigDecimal priceactual;

    /** Value for pricelimit. */
    private BigDecimal pricelimit;

    /** Value for linenetamt. */
    private BigDecimal linenetamt;

    /** Value for cChargeId. */
    private Long cChargeId;

    /** Value for cUomId. */
    private Long cUomId;

    /** Value for cTaxId. */
    private Long cTaxId;

    /** Value for sResourceassignmentId. */
    private Long sResourceassignmentId;

    /** Value for aAssetId. */
    private Long aAssetId;

    /** Value for taxamt. */
    private BigDecimal taxamt;

    /** Value for mAttributesetinstanceId. */
    private Long mAttributesetinstanceId;

    /** Value for isdescription. */
    private String isdescription;

    /** Value for isprinted. */
    private String isprinted;

    /** Value for linetotalamt. */
    private BigDecimal linetotalamt;

    /** Value for refInvoicelineId. */
    private Long refInvoicelineId;

    /** Value for processed. */
    private String processed;

    /** Value for user1Id. */
    private Long user1Id;

    /** Value for user2Id. */
    private Long user2Id;

    /** Value for cProjectId. */
    private Long cProjectId;

    /** Value for qtyentered. */
    private BigDecimal qtyentered;

    /** Value for priceentered. */
    private BigDecimal priceentered;

    /** Value for zchargechange. */
    private String zchargechange;

    /** Value for adOrgtrxId. */
    private Long adOrgtrxId;

    /** Value for cActivityId. */
    private Long cActivityId;

    /** Value for cCampaignId. */
    private Long cCampaignId;

    /** Value for cProjectphaseId. */
    private Long cProjectphaseId;

    /** Value for cProjecttaskId. */
    private Long cProjecttaskId;

    /** Value for rramt. */
    private BigDecimal rramt;

    /** Value for rrstartdate. */
    private Date rrstartdate;

    /** Value for linedocstatus. */
    private String linedocstatus;

    /** Value for isassetaddition. */
    private String isassetaddition;

    /** Value for xxIsapplaydiscount. */
    private String xxIsapplaydiscount;

    /** Value for aCreateasset. */
    private String aCreateasset;

    /** Value for aProcessed. */
    private String aProcessed;

    /** Value for aCapvsexp. */
    private String aCapvsexp;

    /** Value for aAssetGroupId. */
    private Long aAssetGroupId;

    /** Value for repricing. */
    private String repricing;

    /** Value for xxBlinvoicelineId. */
    private Long xxBlinvoicelineId;

    /** Value for poDiscount. */
    private BigDecimal poDiscount;

    /** Value for ventilatecharge. */
    private String ventilatecharge;

    /** Value for isreward. */
    private String isreward;

    /** Empty constructor. **/
    public CInvoiceline() {
        // No-op.
    }

    /** Full constructor. **/
    public CInvoiceline(long adClientId,
        long adOrgId,
        String isactive,
        Date created,
        long createdby,
        Date updated,
        long updatedby,
        long cInvoiceId,
        Long cOrderlineId,
        Long mInoutlineId,
        long line,
        String description,
        Long mProductId,
        BigDecimal qtyinvoiced,
        BigDecimal pricelist,
        BigDecimal priceactual,
        BigDecimal pricelimit,
        BigDecimal linenetamt,
        Long cChargeId,
        Long cUomId,
        Long cTaxId,
        Long sResourceassignmentId,
        Long aAssetId,
        BigDecimal taxamt,
        Long mAttributesetinstanceId,
        String isdescription,
        String isprinted,
        BigDecimal linetotalamt,
        Long refInvoicelineId,
        String processed,
        Long user1Id,
        Long user2Id,
        Long cProjectId,
        BigDecimal qtyentered,
        BigDecimal priceentered,
        String zchargechange,
        Long adOrgtrxId,
        Long cActivityId,
        Long cCampaignId,
        Long cProjectphaseId,
        Long cProjecttaskId,
        BigDecimal rramt,
        Date rrstartdate,
        String linedocstatus,
        String isassetaddition,
        String xxIsapplaydiscount,
        String aCreateasset,
        String aProcessed,
        String aCapvsexp,
        Long aAssetGroupId,
        String repricing,
        Long xxBlinvoicelineId,
        BigDecimal poDiscount,
        String ventilatecharge,
        String isreward) {
        this.adClientId = adClientId;
        this.adOrgId = adOrgId;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.cInvoiceId = cInvoiceId;
        this.cOrderlineId = cOrderlineId;
        this.mInoutlineId = mInoutlineId;
        this.line = line;
        this.description = description;
        this.mProductId = mProductId;
        this.qtyinvoiced = qtyinvoiced;
        this.pricelist = pricelist;
        this.priceactual = priceactual;
        this.pricelimit = pricelimit;
        this.linenetamt = linenetamt;
        this.cChargeId = cChargeId;
        this.cUomId = cUomId;
        this.cTaxId = cTaxId;
        this.sResourceassignmentId = sResourceassignmentId;
        this.aAssetId = aAssetId;
        this.taxamt = taxamt;
        this.mAttributesetinstanceId = mAttributesetinstanceId;
        this.isdescription = isdescription;
        this.isprinted = isprinted;
        this.linetotalamt = linetotalamt;
        this.refInvoicelineId = refInvoicelineId;
        this.processed = processed;
        this.user1Id = user1Id;
        this.user2Id = user2Id;
        this.cProjectId = cProjectId;
        this.qtyentered = qtyentered;
        this.priceentered = priceentered;
        this.zchargechange = zchargechange;
        this.adOrgtrxId = adOrgtrxId;
        this.cActivityId = cActivityId;
        this.cCampaignId = cCampaignId;
        this.cProjectphaseId = cProjectphaseId;
        this.cProjecttaskId = cProjecttaskId;
        this.rramt = rramt;
        this.rrstartdate = rrstartdate;
        this.linedocstatus = linedocstatus;
        this.isassetaddition = isassetaddition;
        this.xxIsapplaydiscount = xxIsapplaydiscount;
        this.aCreateasset = aCreateasset;
        this.aProcessed = aProcessed;
        this.aCapvsexp = aCapvsexp;
        this.aAssetGroupId = aAssetGroupId;
        this.repricing = repricing;
        this.xxBlinvoicelineId = xxBlinvoicelineId;
        this.poDiscount = poDiscount;
        this.ventilatecharge = ventilatecharge;
        this.isreward = isreward;
    }

    /**
     * Gets adClientId
     * 
     * @return Value for adClientId.
     **/
    public long getAdClientId() {
        return adClientId;
    }

    /**
     * Sets adClientId
     * 
     * @param adClientId New value for adClientId.
     **/
    public void setAdClientId(long adClientId) {
        this.adClientId = adClientId;
    }

    /**
     * Gets adOrgId
     * 
     * @return Value for adOrgId.
     **/
    public long getAdOrgId() {
        return adOrgId;
    }

    /**
     * Sets adOrgId
     * 
     * @param adOrgId New value for adOrgId.
     **/
    public void setAdOrgId(long adOrgId) {
        this.adOrgId = adOrgId;
    }

    /**
     * Gets isactive
     * 
     * @return Value for isactive.
     **/
    public String getIsactive() {
        return isactive;
    }

    /**
     * Sets isactive
     * 
     * @param isactive New value for isactive.
     **/
    public void setIsactive(String isactive) {
        this.isactive = isactive;
    }

    /**
     * Gets created
     * 
     * @return Value for created.
     **/
    public Date getCreated() {
        return created;
    }

    /**
     * Sets created
     * 
     * @param created New value for created.
     **/
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * Gets createdby
     * 
     * @return Value for createdby.
     **/
    public long getCreatedby() {
        return createdby;
    }

    /**
     * Sets createdby
     * 
     * @param createdby New value for createdby.
     **/
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }

    /**
     * Gets updated
     * 
     * @return Value for updated.
     **/
    public Date getUpdated() {
        return updated;
    }

    /**
     * Sets updated
     * 
     * @param updated New value for updated.
     **/
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * Gets updatedby
     * 
     * @return Value for updatedby.
     **/
    public long getUpdatedby() {
        return updatedby;
    }

    /**
     * Sets updatedby
     * 
     * @param updatedby New value for updatedby.
     **/
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }

    /**
     * Gets cInvoiceId
     * 
     * @return Value for cInvoiceId.
     **/
    public long getCInvoiceId() {
        return cInvoiceId;
    }

    /**
     * Sets cInvoiceId
     * 
     * @param cInvoiceId New value for cInvoiceId.
     **/
    public void setCInvoiceId(long cInvoiceId) {
        this.cInvoiceId = cInvoiceId;
    }

    /**
     * Gets cOrderlineId
     * 
     * @return Value for cOrderlineId.
     **/
    public Long getCOrderlineId() {
        return cOrderlineId;
    }

    /**
     * Sets cOrderlineId
     * 
     * @param cOrderlineId New value for cOrderlineId.
     **/
    public void setCOrderlineId(Long cOrderlineId) {
        this.cOrderlineId = cOrderlineId;
    }

    /**
     * Gets mInoutlineId
     * 
     * @return Value for mInoutlineId.
     **/
    public Long getMInoutlineId() {
        return mInoutlineId;
    }

    /**
     * Sets mInoutlineId
     * 
     * @param mInoutlineId New value for mInoutlineId.
     **/
    public void setMInoutlineId(Long mInoutlineId) {
        this.mInoutlineId = mInoutlineId;
    }

    /**
     * Gets line
     * 
     * @return Value for line.
     **/
    public long getLine() {
        return line;
    }

    /**
     * Sets line
     * 
     * @param line New value for line.
     **/
    public void setLine(long line) {
        this.line = line;
    }

    /**
     * Gets description
     * 
     * @return Value for description.
     **/
    public String getDescription() {
        return description;
    }

    /**
     * Sets description
     * 
     * @param description New value for description.
     **/
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Gets mProductId
     * 
     * @return Value for mProductId.
     **/
    public Long getMProductId() {
        return mProductId;
    }

    /**
     * Sets mProductId
     * 
     * @param mProductId New value for mProductId.
     **/
    public void setMProductId(Long mProductId) {
        this.mProductId = mProductId;
    }

    /**
     * Gets qtyinvoiced
     * 
     * @return Value for qtyinvoiced.
     **/
    public BigDecimal getQtyinvoiced() {
        return qtyinvoiced;
    }

    /**
     * Sets qtyinvoiced
     * 
     * @param qtyinvoiced New value for qtyinvoiced.
     **/
    public void setQtyinvoiced(BigDecimal qtyinvoiced) {
        this.qtyinvoiced = qtyinvoiced;
    }

    /**
     * Gets pricelist
     * 
     * @return Value for pricelist.
     **/
    public BigDecimal getPricelist() {
        return pricelist;
    }

    /**
     * Sets pricelist
     * 
     * @param pricelist New value for pricelist.
     **/
    public void setPricelist(BigDecimal pricelist) {
        this.pricelist = pricelist;
    }

    /**
     * Gets priceactual
     * 
     * @return Value for priceactual.
     **/
    public BigDecimal getPriceactual() {
        return priceactual;
    }

    /**
     * Sets priceactual
     * 
     * @param priceactual New value for priceactual.
     **/
    public void setPriceactual(BigDecimal priceactual) {
        this.priceactual = priceactual;
    }

    /**
     * Gets pricelimit
     * 
     * @return Value for pricelimit.
     **/
    public BigDecimal getPricelimit() {
        return pricelimit;
    }

    /**
     * Sets pricelimit
     * 
     * @param pricelimit New value for pricelimit.
     **/
    public void setPricelimit(BigDecimal pricelimit) {
        this.pricelimit = pricelimit;
    }

    /**
     * Gets linenetamt
     * 
     * @return Value for linenetamt.
     **/
    public BigDecimal getLinenetamt() {
        return linenetamt;
    }

    /**
     * Sets linenetamt
     * 
     * @param linenetamt New value for linenetamt.
     **/
    public void setLinenetamt(BigDecimal linenetamt) {
        this.linenetamt = linenetamt;
    }

    /**
     * Gets cChargeId
     * 
     * @return Value for cChargeId.
     **/
    public Long getCChargeId() {
        return cChargeId;
    }

    /**
     * Sets cChargeId
     * 
     * @param cChargeId New value for cChargeId.
     **/
    public void setCChargeId(Long cChargeId) {
        this.cChargeId = cChargeId;
    }

    /**
     * Gets cUomId
     * 
     * @return Value for cUomId.
     **/
    public Long getCUomId() {
        return cUomId;
    }

    /**
     * Sets cUomId
     * 
     * @param cUomId New value for cUomId.
     **/
    public void setCUomId(Long cUomId) {
        this.cUomId = cUomId;
    }

    /**
     * Gets cTaxId
     * 
     * @return Value for cTaxId.
     **/
    public Long getCTaxId() {
        return cTaxId;
    }

    /**
     * Sets cTaxId
     * 
     * @param cTaxId New value for cTaxId.
     **/
    public void setCTaxId(Long cTaxId) {
        this.cTaxId = cTaxId;
    }

    /**
     * Gets sResourceassignmentId
     * 
     * @return Value for sResourceassignmentId.
     **/
    public Long getSResourceassignmentId() {
        return sResourceassignmentId;
    }

    /**
     * Sets sResourceassignmentId
     * 
     * @param sResourceassignmentId New value for sResourceassignmentId.
     **/
    public void setSResourceassignmentId(Long sResourceassignmentId) {
        this.sResourceassignmentId = sResourceassignmentId;
    }

    /**
     * Gets aAssetId
     * 
     * @return Value for aAssetId.
     **/
    public Long getAAssetId() {
        return aAssetId;
    }

    /**
     * Sets aAssetId
     * 
     * @param aAssetId New value for aAssetId.
     **/
    public void setAAssetId(Long aAssetId) {
        this.aAssetId = aAssetId;
    }

    /**
     * Gets taxamt
     * 
     * @return Value for taxamt.
     **/
    public BigDecimal getTaxamt() {
        return taxamt;
    }

    /**
     * Sets taxamt
     * 
     * @param taxamt New value for taxamt.
     **/
    public void setTaxamt(BigDecimal taxamt) {
        this.taxamt = taxamt;
    }

    /**
     * Gets mAttributesetinstanceId
     * 
     * @return Value for mAttributesetinstanceId.
     **/
    public Long getMAttributesetinstanceId() {
        return mAttributesetinstanceId;
    }

    /**
     * Sets mAttributesetinstanceId
     * 
     * @param mAttributesetinstanceId New value for mAttributesetinstanceId.
     **/
    public void setMAttributesetinstanceId(Long mAttributesetinstanceId) {
        this.mAttributesetinstanceId = mAttributesetinstanceId;
    }

    /**
     * Gets isdescription
     * 
     * @return Value for isdescription.
     **/
    public String getIsdescription() {
        return isdescription;
    }

    /**
     * Sets isdescription
     * 
     * @param isdescription New value for isdescription.
     **/
    public void setIsdescription(String isdescription) {
        this.isdescription = isdescription;
    }

    /**
     * Gets isprinted
     * 
     * @return Value for isprinted.
     **/
    public String getIsprinted() {
        return isprinted;
    }

    /**
     * Sets isprinted
     * 
     * @param isprinted New value for isprinted.
     **/
    public void setIsprinted(String isprinted) {
        this.isprinted = isprinted;
    }

    /**
     * Gets linetotalamt
     * 
     * @return Value for linetotalamt.
     **/
    public BigDecimal getLinetotalamt() {
        return linetotalamt;
    }

    /**
     * Sets linetotalamt
     * 
     * @param linetotalamt New value for linetotalamt.
     **/
    public void setLinetotalamt(BigDecimal linetotalamt) {
        this.linetotalamt = linetotalamt;
    }

    /**
     * Gets refInvoicelineId
     * 
     * @return Value for refInvoicelineId.
     **/
    public Long getRefInvoicelineId() {
        return refInvoicelineId;
    }

    /**
     * Sets refInvoicelineId
     * 
     * @param refInvoicelineId New value for refInvoicelineId.
     **/
    public void setRefInvoicelineId(Long refInvoicelineId) {
        this.refInvoicelineId = refInvoicelineId;
    }

    /**
     * Gets processed
     * 
     * @return Value for processed.
     **/
    public String getProcessed() {
        return processed;
    }

    /**
     * Sets processed
     * 
     * @param processed New value for processed.
     **/
    public void setProcessed(String processed) {
        this.processed = processed;
    }

    /**
     * Gets user1Id
     * 
     * @return Value for user1Id.
     **/
    public Long getUser1Id() {
        return user1Id;
    }

    /**
     * Sets user1Id
     * 
     * @param user1Id New value for user1Id.
     **/
    public void setUser1Id(Long user1Id) {
        this.user1Id = user1Id;
    }

    /**
     * Gets user2Id
     * 
     * @return Value for user2Id.
     **/
    public Long getUser2Id() {
        return user2Id;
    }

    /**
     * Sets user2Id
     * 
     * @param user2Id New value for user2Id.
     **/
    public void setUser2Id(Long user2Id) {
        this.user2Id = user2Id;
    }

    /**
     * Gets cProjectId
     * 
     * @return Value for cProjectId.
     **/
    public Long getCProjectId() {
        return cProjectId;
    }

    /**
     * Sets cProjectId
     * 
     * @param cProjectId New value for cProjectId.
     **/
    public void setCProjectId(Long cProjectId) {
        this.cProjectId = cProjectId;
    }

    /**
     * Gets qtyentered
     * 
     * @return Value for qtyentered.
     **/
    public BigDecimal getQtyentered() {
        return qtyentered;
    }

    /**
     * Sets qtyentered
     * 
     * @param qtyentered New value for qtyentered.
     **/
    public void setQtyentered(BigDecimal qtyentered) {
        this.qtyentered = qtyentered;
    }

    /**
     * Gets priceentered
     * 
     * @return Value for priceentered.
     **/
    public BigDecimal getPriceentered() {
        return priceentered;
    }

    /**
     * Sets priceentered
     * 
     * @param priceentered New value for priceentered.
     **/
    public void setPriceentered(BigDecimal priceentered) {
        this.priceentered = priceentered;
    }

    /**
     * Gets zchargechange
     * 
     * @return Value for zchargechange.
     **/
    public String getZchargechange() {
        return zchargechange;
    }

    /**
     * Sets zchargechange
     * 
     * @param zchargechange New value for zchargechange.
     **/
    public void setZchargechange(String zchargechange) {
        this.zchargechange = zchargechange;
    }

    /**
     * Gets adOrgtrxId
     * 
     * @return Value for adOrgtrxId.
     **/
    public Long getAdOrgtrxId() {
        return adOrgtrxId;
    }

    /**
     * Sets adOrgtrxId
     * 
     * @param adOrgtrxId New value for adOrgtrxId.
     **/
    public void setAdOrgtrxId(Long adOrgtrxId) {
        this.adOrgtrxId = adOrgtrxId;
    }

    /**
     * Gets cActivityId
     * 
     * @return Value for cActivityId.
     **/
    public Long getCActivityId() {
        return cActivityId;
    }

    /**
     * Sets cActivityId
     * 
     * @param cActivityId New value for cActivityId.
     **/
    public void setCActivityId(Long cActivityId) {
        this.cActivityId = cActivityId;
    }

    /**
     * Gets cCampaignId
     * 
     * @return Value for cCampaignId.
     **/
    public Long getCCampaignId() {
        return cCampaignId;
    }

    /**
     * Sets cCampaignId
     * 
     * @param cCampaignId New value for cCampaignId.
     **/
    public void setCCampaignId(Long cCampaignId) {
        this.cCampaignId = cCampaignId;
    }

    /**
     * Gets cProjectphaseId
     * 
     * @return Value for cProjectphaseId.
     **/
    public Long getCProjectphaseId() {
        return cProjectphaseId;
    }

    /**
     * Sets cProjectphaseId
     * 
     * @param cProjectphaseId New value for cProjectphaseId.
     **/
    public void setCProjectphaseId(Long cProjectphaseId) {
        this.cProjectphaseId = cProjectphaseId;
    }

    /**
     * Gets cProjecttaskId
     * 
     * @return Value for cProjecttaskId.
     **/
    public Long getCProjecttaskId() {
        return cProjecttaskId;
    }

    /**
     * Sets cProjecttaskId
     * 
     * @param cProjecttaskId New value for cProjecttaskId.
     **/
    public void setCProjecttaskId(Long cProjecttaskId) {
        this.cProjecttaskId = cProjecttaskId;
    }

    /**
     * Gets rramt
     * 
     * @return Value for rramt.
     **/
    public BigDecimal getRramt() {
        return rramt;
    }

    /**
     * Sets rramt
     * 
     * @param rramt New value for rramt.
     **/
    public void setRramt(BigDecimal rramt) {
        this.rramt = rramt;
    }

    /**
     * Gets rrstartdate
     * 
     * @return Value for rrstartdate.
     **/
    public Date getRrstartdate() {
        return rrstartdate;
    }

    /**
     * Sets rrstartdate
     * 
     * @param rrstartdate New value for rrstartdate.
     **/
    public void setRrstartdate(Date rrstartdate) {
        this.rrstartdate = rrstartdate;
    }

    /**
     * Gets linedocstatus
     * 
     * @return Value for linedocstatus.
     **/
    public String getLinedocstatus() {
        return linedocstatus;
    }

    /**
     * Sets linedocstatus
     * 
     * @param linedocstatus New value for linedocstatus.
     **/
    public void setLinedocstatus(String linedocstatus) {
        this.linedocstatus = linedocstatus;
    }

    /**
     * Gets isassetaddition
     * 
     * @return Value for isassetaddition.
     **/
    public String getIsassetaddition() {
        return isassetaddition;
    }

    /**
     * Sets isassetaddition
     * 
     * @param isassetaddition New value for isassetaddition.
     **/
    public void setIsassetaddition(String isassetaddition) {
        this.isassetaddition = isassetaddition;
    }

    /**
     * Gets xxIsapplaydiscount
     * 
     * @return Value for xxIsapplaydiscount.
     **/
    public String getXxIsapplaydiscount() {
        return xxIsapplaydiscount;
    }

    /**
     * Sets xxIsapplaydiscount
     * 
     * @param xxIsapplaydiscount New value for xxIsapplaydiscount.
     **/
    public void setXxIsapplaydiscount(String xxIsapplaydiscount) {
        this.xxIsapplaydiscount = xxIsapplaydiscount;
    }

    /**
     * Gets aCreateasset
     * 
     * @return Value for aCreateasset.
     **/
    public String getACreateasset() {
        return aCreateasset;
    }

    /**
     * Sets aCreateasset
     * 
     * @param aCreateasset New value for aCreateasset.
     **/
    public void setACreateasset(String aCreateasset) {
        this.aCreateasset = aCreateasset;
    }

    /**
     * Gets aProcessed
     * 
     * @return Value for aProcessed.
     **/
    public String getAProcessed() {
        return aProcessed;
    }

    /**
     * Sets aProcessed
     * 
     * @param aProcessed New value for aProcessed.
     **/
    public void setAProcessed(String aProcessed) {
        this.aProcessed = aProcessed;
    }

    /**
     * Gets aCapvsexp
     * 
     * @return Value for aCapvsexp.
     **/
    public String getACapvsexp() {
        return aCapvsexp;
    }

    /**
     * Sets aCapvsexp
     * 
     * @param aCapvsexp New value for aCapvsexp.
     **/
    public void setACapvsexp(String aCapvsexp) {
        this.aCapvsexp = aCapvsexp;
    }

    /**
     * Gets aAssetGroupId
     * 
     * @return Value for aAssetGroupId.
     **/
    public Long getAAssetGroupId() {
        return aAssetGroupId;
    }

    /**
     * Sets aAssetGroupId
     * 
     * @param aAssetGroupId New value for aAssetGroupId.
     **/
    public void setAAssetGroupId(Long aAssetGroupId) {
        this.aAssetGroupId = aAssetGroupId;
    }

    /**
     * Gets repricing
     * 
     * @return Value for repricing.
     **/
    public String getRepricing() {
        return repricing;
    }

    /**
     * Sets repricing
     * 
     * @param repricing New value for repricing.
     **/
    public void setRepricing(String repricing) {
        this.repricing = repricing;
    }

    /**
     * Gets xxBlinvoicelineId
     * 
     * @return Value for xxBlinvoicelineId.
     **/
    public Long getXxBlinvoicelineId() {
        return xxBlinvoicelineId;
    }

    /**
     * Sets xxBlinvoicelineId
     * 
     * @param xxBlinvoicelineId New value for xxBlinvoicelineId.
     **/
    public void setXxBlinvoicelineId(Long xxBlinvoicelineId) {
        this.xxBlinvoicelineId = xxBlinvoicelineId;
    }

    /**
     * Gets poDiscount
     * 
     * @return Value for poDiscount.
     **/
    public BigDecimal getPoDiscount() {
        return poDiscount;
    }

    /**
     * Sets poDiscount
     * 
     * @param poDiscount New value for poDiscount.
     **/
    public void setPoDiscount(BigDecimal poDiscount) {
        this.poDiscount = poDiscount;
    }

    /**
     * Gets ventilatecharge
     * 
     * @return Value for ventilatecharge.
     **/
    public String getVentilatecharge() {
        return ventilatecharge;
    }

    /**
     * Sets ventilatecharge
     * 
     * @param ventilatecharge New value for ventilatecharge.
     **/
    public void setVentilatecharge(String ventilatecharge) {
        this.ventilatecharge = ventilatecharge;
    }

    /**
     * Gets isreward
     * 
     * @return Value for isreward.
     **/
    public String getIsreward() {
        return isreward;
    }

    /**
     * Sets isreward
     * 
     * @param isreward New value for isreward.
     **/
    public void setIsreward(String isreward) {
        this.isreward = isreward;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof CInvoiceline))
            return false;
        
        CInvoiceline that = (CInvoiceline)o;

        if (adClientId != that.adClientId)
            return false;
        

        if (adOrgId != that.adOrgId)
            return false;
        

        if (isactive != null ? !isactive.equals(that.isactive) : that.isactive != null)
            return false;
        

        if (created != null ? !created.equals(that.created) : that.created != null)
            return false;
        

        if (createdby != that.createdby)
            return false;
        

        if (updated != null ? !updated.equals(that.updated) : that.updated != null)
            return false;
        

        if (updatedby != that.updatedby)
            return false;
        

        if (cInvoiceId != that.cInvoiceId)
            return false;
        

        if (cOrderlineId != null ? !cOrderlineId.equals(that.cOrderlineId) : that.cOrderlineId != null)
            return false;
        

        if (mInoutlineId != null ? !mInoutlineId.equals(that.mInoutlineId) : that.mInoutlineId != null)
            return false;
        

        if (line != that.line)
            return false;
        

        if (description != null ? !description.equals(that.description) : that.description != null)
            return false;
        

        if (mProductId != null ? !mProductId.equals(that.mProductId) : that.mProductId != null)
            return false;
        

        if (qtyinvoiced != null ? !qtyinvoiced.equals(that.qtyinvoiced) : that.qtyinvoiced != null)
            return false;
        

        if (pricelist != null ? !pricelist.equals(that.pricelist) : that.pricelist != null)
            return false;
        

        if (priceactual != null ? !priceactual.equals(that.priceactual) : that.priceactual != null)
            return false;
        

        if (pricelimit != null ? !pricelimit.equals(that.pricelimit) : that.pricelimit != null)
            return false;
        

        if (linenetamt != null ? !linenetamt.equals(that.linenetamt) : that.linenetamt != null)
            return false;
        

        if (cChargeId != null ? !cChargeId.equals(that.cChargeId) : that.cChargeId != null)
            return false;
        

        if (cUomId != null ? !cUomId.equals(that.cUomId) : that.cUomId != null)
            return false;
        

        if (cTaxId != null ? !cTaxId.equals(that.cTaxId) : that.cTaxId != null)
            return false;
        

        if (sResourceassignmentId != null ? !sResourceassignmentId.equals(that.sResourceassignmentId) : that.sResourceassignmentId != null)
            return false;
        

        if (aAssetId != null ? !aAssetId.equals(that.aAssetId) : that.aAssetId != null)
            return false;
        

        if (taxamt != null ? !taxamt.equals(that.taxamt) : that.taxamt != null)
            return false;
        

        if (mAttributesetinstanceId != null ? !mAttributesetinstanceId.equals(that.mAttributesetinstanceId) : that.mAttributesetinstanceId != null)
            return false;
        

        if (isdescription != null ? !isdescription.equals(that.isdescription) : that.isdescription != null)
            return false;
        

        if (isprinted != null ? !isprinted.equals(that.isprinted) : that.isprinted != null)
            return false;
        

        if (linetotalamt != null ? !linetotalamt.equals(that.linetotalamt) : that.linetotalamt != null)
            return false;
        

        if (refInvoicelineId != null ? !refInvoicelineId.equals(that.refInvoicelineId) : that.refInvoicelineId != null)
            return false;
        

        if (processed != null ? !processed.equals(that.processed) : that.processed != null)
            return false;
        

        if (user1Id != null ? !user1Id.equals(that.user1Id) : that.user1Id != null)
            return false;
        

        if (user2Id != null ? !user2Id.equals(that.user2Id) : that.user2Id != null)
            return false;
        

        if (cProjectId != null ? !cProjectId.equals(that.cProjectId) : that.cProjectId != null)
            return false;
        

        if (qtyentered != null ? !qtyentered.equals(that.qtyentered) : that.qtyentered != null)
            return false;
        

        if (priceentered != null ? !priceentered.equals(that.priceentered) : that.priceentered != null)
            return false;
        

        if (zchargechange != null ? !zchargechange.equals(that.zchargechange) : that.zchargechange != null)
            return false;
        

        if (adOrgtrxId != null ? !adOrgtrxId.equals(that.adOrgtrxId) : that.adOrgtrxId != null)
            return false;
        

        if (cActivityId != null ? !cActivityId.equals(that.cActivityId) : that.cActivityId != null)
            return false;
        

        if (cCampaignId != null ? !cCampaignId.equals(that.cCampaignId) : that.cCampaignId != null)
            return false;
        

        if (cProjectphaseId != null ? !cProjectphaseId.equals(that.cProjectphaseId) : that.cProjectphaseId != null)
            return false;
        

        if (cProjecttaskId != null ? !cProjecttaskId.equals(that.cProjecttaskId) : that.cProjecttaskId != null)
            return false;
        

        if (rramt != null ? !rramt.equals(that.rramt) : that.rramt != null)
            return false;
        

        if (rrstartdate != null ? !rrstartdate.equals(that.rrstartdate) : that.rrstartdate != null)
            return false;
        

        if (linedocstatus != null ? !linedocstatus.equals(that.linedocstatus) : that.linedocstatus != null)
            return false;
        

        if (isassetaddition != null ? !isassetaddition.equals(that.isassetaddition) : that.isassetaddition != null)
            return false;
        

        if (xxIsapplaydiscount != null ? !xxIsapplaydiscount.equals(that.xxIsapplaydiscount) : that.xxIsapplaydiscount != null)
            return false;
        

        if (aCreateasset != null ? !aCreateasset.equals(that.aCreateasset) : that.aCreateasset != null)
            return false;
        

        if (aProcessed != null ? !aProcessed.equals(that.aProcessed) : that.aProcessed != null)
            return false;
        

        if (aCapvsexp != null ? !aCapvsexp.equals(that.aCapvsexp) : that.aCapvsexp != null)
            return false;
        

        if (aAssetGroupId != null ? !aAssetGroupId.equals(that.aAssetGroupId) : that.aAssetGroupId != null)
            return false;
        

        if (repricing != null ? !repricing.equals(that.repricing) : that.repricing != null)
            return false;
        

        if (xxBlinvoicelineId != null ? !xxBlinvoicelineId.equals(that.xxBlinvoicelineId) : that.xxBlinvoicelineId != null)
            return false;
        

        if (poDiscount != null ? !poDiscount.equals(that.poDiscount) : that.poDiscount != null)
            return false;
        

        if (ventilatecharge != null ? !ventilatecharge.equals(that.ventilatecharge) : that.ventilatecharge != null)
            return false;
        

        if (isreward != null ? !isreward.equals(that.isreward) : that.isreward != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = (int)(adClientId ^ (adClientId >>> 32));

        res = 31 * res + (int)(adOrgId ^ (adOrgId >>> 32));

        res = 31 * res + (isactive != null ? isactive.hashCode() : 0);

        res = 31 * res + (created != null ? created.hashCode() : 0);

        res = 31 * res + (int)(createdby ^ (createdby >>> 32));

        res = 31 * res + (updated != null ? updated.hashCode() : 0);

        res = 31 * res + (int)(updatedby ^ (updatedby >>> 32));

        res = 31 * res + (int)(cInvoiceId ^ (cInvoiceId >>> 32));

        res = 31 * res + (cOrderlineId != null ? cOrderlineId.hashCode() : 0);

        res = 31 * res + (mInoutlineId != null ? mInoutlineId.hashCode() : 0);

        res = 31 * res + (int)(line ^ (line >>> 32));

        res = 31 * res + (description != null ? description.hashCode() : 0);

        res = 31 * res + (mProductId != null ? mProductId.hashCode() : 0);

        res = 31 * res + (qtyinvoiced != null ? qtyinvoiced.hashCode() : 0);

        res = 31 * res + (pricelist != null ? pricelist.hashCode() : 0);

        res = 31 * res + (priceactual != null ? priceactual.hashCode() : 0);

        res = 31 * res + (pricelimit != null ? pricelimit.hashCode() : 0);

        res = 31 * res + (linenetamt != null ? linenetamt.hashCode() : 0);

        res = 31 * res + (cChargeId != null ? cChargeId.hashCode() : 0);

        res = 31 * res + (cUomId != null ? cUomId.hashCode() : 0);

        res = 31 * res + (cTaxId != null ? cTaxId.hashCode() : 0);

        res = 31 * res + (sResourceassignmentId != null ? sResourceassignmentId.hashCode() : 0);

        res = 31 * res + (aAssetId != null ? aAssetId.hashCode() : 0);

        res = 31 * res + (taxamt != null ? taxamt.hashCode() : 0);

        res = 31 * res + (mAttributesetinstanceId != null ? mAttributesetinstanceId.hashCode() : 0);

        res = 31 * res + (isdescription != null ? isdescription.hashCode() : 0);

        res = 31 * res + (isprinted != null ? isprinted.hashCode() : 0);

        res = 31 * res + (linetotalamt != null ? linetotalamt.hashCode() : 0);

        res = 31 * res + (refInvoicelineId != null ? refInvoicelineId.hashCode() : 0);

        res = 31 * res + (processed != null ? processed.hashCode() : 0);

        res = 31 * res + (user1Id != null ? user1Id.hashCode() : 0);

        res = 31 * res + (user2Id != null ? user2Id.hashCode() : 0);

        res = 31 * res + (cProjectId != null ? cProjectId.hashCode() : 0);

        res = 31 * res + (qtyentered != null ? qtyentered.hashCode() : 0);

        res = 31 * res + (priceentered != null ? priceentered.hashCode() : 0);

        res = 31 * res + (zchargechange != null ? zchargechange.hashCode() : 0);

        res = 31 * res + (adOrgtrxId != null ? adOrgtrxId.hashCode() : 0);

        res = 31 * res + (cActivityId != null ? cActivityId.hashCode() : 0);

        res = 31 * res + (cCampaignId != null ? cCampaignId.hashCode() : 0);

        res = 31 * res + (cProjectphaseId != null ? cProjectphaseId.hashCode() : 0);

        res = 31 * res + (cProjecttaskId != null ? cProjecttaskId.hashCode() : 0);

        res = 31 * res + (rramt != null ? rramt.hashCode() : 0);

        res = 31 * res + (rrstartdate != null ? rrstartdate.hashCode() : 0);

        res = 31 * res + (linedocstatus != null ? linedocstatus.hashCode() : 0);

        res = 31 * res + (isassetaddition != null ? isassetaddition.hashCode() : 0);

        res = 31 * res + (xxIsapplaydiscount != null ? xxIsapplaydiscount.hashCode() : 0);

        res = 31 * res + (aCreateasset != null ? aCreateasset.hashCode() : 0);

        res = 31 * res + (aProcessed != null ? aProcessed.hashCode() : 0);

        res = 31 * res + (aCapvsexp != null ? aCapvsexp.hashCode() : 0);

        res = 31 * res + (aAssetGroupId != null ? aAssetGroupId.hashCode() : 0);

        res = 31 * res + (repricing != null ? repricing.hashCode() : 0);

        res = 31 * res + (xxBlinvoicelineId != null ? xxBlinvoicelineId.hashCode() : 0);

        res = 31 * res + (poDiscount != null ? poDiscount.hashCode() : 0);

        res = 31 * res + (ventilatecharge != null ? ventilatecharge.hashCode() : 0);

        res = 31 * res + (isreward != null ? isreward.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "CInvoiceline [" + 
            "adClientId=" + adClientId + ", " + 
            "adOrgId=" + adOrgId + ", " + 
            "isactive=" + isactive + ", " + 
            "created=" + created + ", " + 
            "createdby=" + createdby + ", " + 
            "updated=" + updated + ", " + 
            "updatedby=" + updatedby + ", " + 
            "cInvoiceId=" + cInvoiceId + ", " + 
            "cOrderlineId=" + cOrderlineId + ", " + 
            "mInoutlineId=" + mInoutlineId + ", " + 
            "line=" + line + ", " + 
            "description=" + description + ", " + 
            "mProductId=" + mProductId + ", " + 
            "qtyinvoiced=" + qtyinvoiced + ", " + 
            "pricelist=" + pricelist + ", " + 
            "priceactual=" + priceactual + ", " + 
            "pricelimit=" + pricelimit + ", " + 
            "linenetamt=" + linenetamt + ", " + 
            "cChargeId=" + cChargeId + ", " + 
            "cUomId=" + cUomId + ", " + 
            "cTaxId=" + cTaxId + ", " + 
            "sResourceassignmentId=" + sResourceassignmentId + ", " + 
            "aAssetId=" + aAssetId + ", " + 
            "taxamt=" + taxamt + ", " + 
            "mAttributesetinstanceId=" + mAttributesetinstanceId + ", " + 
            "isdescription=" + isdescription + ", " + 
            "isprinted=" + isprinted + ", " + 
            "linetotalamt=" + linetotalamt + ", " + 
            "refInvoicelineId=" + refInvoicelineId + ", " + 
            "processed=" + processed + ", " + 
            "user1Id=" + user1Id + ", " + 
            "user2Id=" + user2Id + ", " + 
            "cProjectId=" + cProjectId + ", " + 
            "qtyentered=" + qtyentered + ", " + 
            "priceentered=" + priceentered + ", " + 
            "zchargechange=" + zchargechange + ", " + 
            "adOrgtrxId=" + adOrgtrxId + ", " + 
            "cActivityId=" + cActivityId + ", " + 
            "cCampaignId=" + cCampaignId + ", " + 
            "cProjectphaseId=" + cProjectphaseId + ", " + 
            "cProjecttaskId=" + cProjecttaskId + ", " + 
            "rramt=" + rramt + ", " + 
            "rrstartdate=" + rrstartdate + ", " + 
            "linedocstatus=" + linedocstatus + ", " + 
            "isassetaddition=" + isassetaddition + ", " + 
            "xxIsapplaydiscount=" + xxIsapplaydiscount + ", " + 
            "aCreateasset=" + aCreateasset + ", " + 
            "aProcessed=" + aProcessed + ", " + 
            "aCapvsexp=" + aCapvsexp + ", " + 
            "aAssetGroupId=" + aAssetGroupId + ", " + 
            "repricing=" + repricing + ", " + 
            "xxBlinvoicelineId=" + xxBlinvoicelineId + ", " + 
            "poDiscount=" + poDiscount + ", " + 
            "ventilatecharge=" + ventilatecharge + ", " + 
            "isreward=" + isreward +
        "]";
    }
}