package com.wanasis.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;

/**
 * COrder definition.
 * 
 * This file was generated by Ignite Web Console (11/21/2019, 08:54)
 **/
public class COrder implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for adClientId. */
    private long adClientId;

    /** Value for adOrgId. */
    private long adOrgId;

    /** Value for isactive. */
    private String isactive;

    /** Value for created. */
    private Date created;

    /** Value for createdby. */
    private long createdby;

    /** Value for updated. */
    private Date updated;

    /** Value for updatedby. */
    private long updatedby;

    /** Value for issotrx. */
    private String issotrx;

    /** Value for documentno. */
    private String documentno;

    /** Value for docstatus. */
    private String docstatus;

    /** Value for docaction. */
    private String docaction;

    /** Value for processing. */
    private String processing;

    /** Value for processed. */
    private String processed;

    /** Value for cDoctypeId. */
    private long cDoctypeId;

    /** Value for cDoctypetargetId. */
    private long cDoctypetargetId;

    /** Value for description. */
    private String description;

    /** Value for isapproved. */
    private String isapproved;

    /** Value for iscreditapproved. */
    private String iscreditapproved;

    /** Value for isdelivered. */
    private String isdelivered;

    /** Value for isinvoiced. */
    private String isinvoiced;

    /** Value for isprinted. */
    private String isprinted;

    /** Value for istransferred. */
    private String istransferred;

    /** Value for isselected. */
    private String isselected;

    /** Value for salesrepId. */
    private long salesrepId;

    /** Value for dateordered. */
    private Date dateordered;

    /** Value for datepromised. */
    private Date datepromised;

    /** Value for dateprinted. */
    private Date dateprinted;

    /** Value for dateacct. */
    private Date dateacct;

    /** Value for cBpartnerId. */
    private long cBpartnerId;

    /** Value for cBpartnerLocationId. */
    private long cBpartnerLocationId;

    /** Value for poreference. */
    private String poreference;

    /** Value for isdiscountprinted. */
    private String isdiscountprinted;

    /** Value for cCurrencyId. */
    private long cCurrencyId;

    /** Value for paymentrule. */
    private String paymentrule;

    /** Value for cPaymenttermId. */
    private long cPaymenttermId;

    /** Value for invoicerule. */
    private String invoicerule;

    /** Value for deliveryrule. */
    private String deliveryrule;

    /** Value for freightcostrule. */
    private String freightcostrule;

    /** Value for freightamt. */
    private BigDecimal freightamt;

    /** Value for deliveryviarule. */
    private String deliveryviarule;

    /** Value for mShipperId. */
    private Long mShipperId;

    /** Value for cChargeId. */
    private Long cChargeId;

    /** Value for chargeamt. */
    private BigDecimal chargeamt;

    /** Value for priorityrule. */
    private String priorityrule;

    /** Value for totallines. */
    private BigDecimal totallines;

    /** Value for grandtotal. */
    private BigDecimal grandtotal;

    /** Value for mWarehouseId. */
    private long mWarehouseId;

    /** Value for mPricelistId. */
    private long mPricelistId;

    /** Value for istaxincluded. */
    private String istaxincluded;

    /** Value for cCampaignId. */
    private Long cCampaignId;

    /** Value for cProjectId. */
    private Long cProjectId;

    /** Value for cActivityId. */
    private Long cActivityId;

    /** Value for posted. */
    private String posted;

    /** Value for cPaymentId. */
    private Long cPaymentId;

    /** Value for cCashlineId. */
    private Long cCashlineId;

    /** Value for sendemail. */
    private String sendemail;

    /** Value for adUserId. */
    private Long adUserId;

    /** Value for copyfrom. */
    private String copyfrom;

    /** Value for isselfservice. */
    private String isselfservice;

    /** Value for adOrgtrxId. */
    private Long adOrgtrxId;

    /** Value for user1Id. */
    private Long user1Id;

    /** Value for user2Id. */
    private Long user2Id;

    /** Value for cConversiontypeId. */
    private Long cConversiontypeId;

    /** Value for billBpartnerId. */
    private long billBpartnerId;

    /** Value for billLocationId. */
    private long billLocationId;

    /** Value for billUserId. */
    private Long billUserId;

    /** Value for payBpartnerId. */
    private Long payBpartnerId;

    /** Value for payLocationId. */
    private Long payLocationId;

    /** Value for refOrderId. */
    private Long refOrderId;

    /** Value for isdropship. */
    private String isdropship;

    /** Value for description2. */
    private String description2;

    /** Value for testId. */
    private Long testId;

    /** Value for zcreatefromattribute. */
    private String zcreatefromattribute;

    /** Value for zTransportmode. */
    private String zTransportmode;

    /** Value for zIncotermsId. */
    private Long zIncotermsId;

    /** Value for zIscompleet. */
    private String zIscompleet;

    /** Value for volume. */
    private BigDecimal volume;

    /** Value for weight. */
    private BigDecimal weight;

    /** Value for cBpartnersrId. */
    private Long cBpartnersrId;

    /** Value for cBpBankaccountId. */
    private Long cBpBankaccountId;

    /** Value for isreturntrx. */
    private String isreturntrx;

    /** Value for mReturnpolicyId. */
    private Long mReturnpolicyId;

    /** Value for mRmacategoryId. */
    private Long mRmacategoryId;

    /** Value for origInoutId. */
    private Long origInoutId;

    /** Value for origOrderId. */
    private Long origOrderId;

    /** Value for zexplodesubcontractingorder. */
    private String zexplodesubcontractingorder;

    /** Value for isupdateable. */
    private String isupdateable;

    /** Value for createfrom. */
    private String createfrom;

    /** Value for xxApplieddiscount. */
    private String xxApplieddiscount;

    /** Value for withmodification. */
    private String withmodification;

    /** Value for xxCommandedelegue. */
    private String xxCommandedelegue;

    /** Value for xxIsretfromautrelogiciel. */
    private String xxIsretfromautrelogiciel;

    /** Value for isquotareturned. */
    private String isquotareturned;

    /** Value for xxReturnquota. */
    private String xxReturnquota;

    /** Value for globalDiscount. */
    private BigDecimal globalDiscount;

    /** Value for generateto. */
    private String generateto;

    /** Empty constructor. **/
    public COrder() {
        // No-op.
    }

    /** Full constructor. **/
    public COrder(long adClientId,
        long adOrgId,
        String isactive,
        Date created,
        long createdby,
        Date updated,
        long updatedby,
        String issotrx,
        String documentno,
        String docstatus,
        String docaction,
        String processing,
        String processed,
        long cDoctypeId,
        long cDoctypetargetId,
        String description,
        String isapproved,
        String iscreditapproved,
        String isdelivered,
        String isinvoiced,
        String isprinted,
        String istransferred,
        String isselected,
        long salesrepId,
        Date dateordered,
        Date datepromised,
        Date dateprinted,
        Date dateacct,
        long cBpartnerId,
        long cBpartnerLocationId,
        String poreference,
        String isdiscountprinted,
        long cCurrencyId,
        String paymentrule,
        long cPaymenttermId,
        String invoicerule,
        String deliveryrule,
        String freightcostrule,
        BigDecimal freightamt,
        String deliveryviarule,
        Long mShipperId,
        Long cChargeId,
        BigDecimal chargeamt,
        String priorityrule,
        BigDecimal totallines,
        BigDecimal grandtotal,
        long mWarehouseId,
        long mPricelistId,
        String istaxincluded,
        Long cCampaignId,
        Long cProjectId,
        Long cActivityId,
        String posted,
        Long cPaymentId,
        Long cCashlineId,
        String sendemail,
        Long adUserId,
        String copyfrom,
        String isselfservice,
        Long adOrgtrxId,
        Long user1Id,
        Long user2Id,
        Long cConversiontypeId,
        long billBpartnerId,
        long billLocationId,
        Long billUserId,
        Long payBpartnerId,
        Long payLocationId,
        Long refOrderId,
        String isdropship,
        String description2,
        Long testId,
        String zcreatefromattribute,
        String zTransportmode,
        Long zIncotermsId,
        String zIscompleet,
        BigDecimal volume,
        BigDecimal weight,
        Long cBpartnersrId,
        Long cBpBankaccountId,
        String isreturntrx,
        Long mReturnpolicyId,
        Long mRmacategoryId,
        Long origInoutId,
        Long origOrderId,
        String zexplodesubcontractingorder,
        String isupdateable,
        String createfrom,
        String xxApplieddiscount,
        String withmodification,
        String xxCommandedelegue,
        String xxIsretfromautrelogiciel,
        String isquotareturned,
        String xxReturnquota,
        BigDecimal globalDiscount,
        String generateto) {
        this.adClientId = adClientId;
        this.adOrgId = adOrgId;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.issotrx = issotrx;
        this.documentno = documentno;
        this.docstatus = docstatus;
        this.docaction = docaction;
        this.processing = processing;
        this.processed = processed;
        this.cDoctypeId = cDoctypeId;
        this.cDoctypetargetId = cDoctypetargetId;
        this.description = description;
        this.isapproved = isapproved;
        this.iscreditapproved = iscreditapproved;
        this.isdelivered = isdelivered;
        this.isinvoiced = isinvoiced;
        this.isprinted = isprinted;
        this.istransferred = istransferred;
        this.isselected = isselected;
        this.salesrepId = salesrepId;
        this.dateordered = dateordered;
        this.datepromised = datepromised;
        this.dateprinted = dateprinted;
        this.dateacct = dateacct;
        this.cBpartnerId = cBpartnerId;
        this.cBpartnerLocationId = cBpartnerLocationId;
        this.poreference = poreference;
        this.isdiscountprinted = isdiscountprinted;
        this.cCurrencyId = cCurrencyId;
        this.paymentrule = paymentrule;
        this.cPaymenttermId = cPaymenttermId;
        this.invoicerule = invoicerule;
        this.deliveryrule = deliveryrule;
        this.freightcostrule = freightcostrule;
        this.freightamt = freightamt;
        this.deliveryviarule = deliveryviarule;
        this.mShipperId = mShipperId;
        this.cChargeId = cChargeId;
        this.chargeamt = chargeamt;
        this.priorityrule = priorityrule;
        this.totallines = totallines;
        this.grandtotal = grandtotal;
        this.mWarehouseId = mWarehouseId;
        this.mPricelistId = mPricelistId;
        this.istaxincluded = istaxincluded;
        this.cCampaignId = cCampaignId;
        this.cProjectId = cProjectId;
        this.cActivityId = cActivityId;
        this.posted = posted;
        this.cPaymentId = cPaymentId;
        this.cCashlineId = cCashlineId;
        this.sendemail = sendemail;
        this.adUserId = adUserId;
        this.copyfrom = copyfrom;
        this.isselfservice = isselfservice;
        this.adOrgtrxId = adOrgtrxId;
        this.user1Id = user1Id;
        this.user2Id = user2Id;
        this.cConversiontypeId = cConversiontypeId;
        this.billBpartnerId = billBpartnerId;
        this.billLocationId = billLocationId;
        this.billUserId = billUserId;
        this.payBpartnerId = payBpartnerId;
        this.payLocationId = payLocationId;
        this.refOrderId = refOrderId;
        this.isdropship = isdropship;
        this.description2 = description2;
        this.testId = testId;
        this.zcreatefromattribute = zcreatefromattribute;
        this.zTransportmode = zTransportmode;
        this.zIncotermsId = zIncotermsId;
        this.zIscompleet = zIscompleet;
        this.volume = volume;
        this.weight = weight;
        this.cBpartnersrId = cBpartnersrId;
        this.cBpBankaccountId = cBpBankaccountId;
        this.isreturntrx = isreturntrx;
        this.mReturnpolicyId = mReturnpolicyId;
        this.mRmacategoryId = mRmacategoryId;
        this.origInoutId = origInoutId;
        this.origOrderId = origOrderId;
        this.zexplodesubcontractingorder = zexplodesubcontractingorder;
        this.isupdateable = isupdateable;
        this.createfrom = createfrom;
        this.xxApplieddiscount = xxApplieddiscount;
        this.withmodification = withmodification;
        this.xxCommandedelegue = xxCommandedelegue;
        this.xxIsretfromautrelogiciel = xxIsretfromautrelogiciel;
        this.isquotareturned = isquotareturned;
        this.xxReturnquota = xxReturnquota;
        this.globalDiscount = globalDiscount;
        this.generateto = generateto;
    }

    /**
     * Gets adClientId
     * 
     * @return Value for adClientId.
     **/
    public long getAdClientId() {
        return adClientId;
    }

    /**
     * Sets adClientId
     * 
     * @param adClientId New value for adClientId.
     **/
    public void setAdClientId(long adClientId) {
        this.adClientId = adClientId;
    }

    /**
     * Gets adOrgId
     * 
     * @return Value for adOrgId.
     **/
    public long getAdOrgId() {
        return adOrgId;
    }

    /**
     * Sets adOrgId
     * 
     * @param adOrgId New value for adOrgId.
     **/
    public void setAdOrgId(long adOrgId) {
        this.adOrgId = adOrgId;
    }

    /**
     * Gets isactive
     * 
     * @return Value for isactive.
     **/
    public String getIsactive() {
        return isactive;
    }

    /**
     * Sets isactive
     * 
     * @param isactive New value for isactive.
     **/
    public void setIsactive(String isactive) {
        this.isactive = isactive;
    }

    /**
     * Gets created
     * 
     * @return Value for created.
     **/
    public Date getCreated() {
        return created;
    }

    /**
     * Sets created
     * 
     * @param created New value for created.
     **/
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * Gets createdby
     * 
     * @return Value for createdby.
     **/
    public long getCreatedby() {
        return createdby;
    }

    /**
     * Sets createdby
     * 
     * @param createdby New value for createdby.
     **/
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }

    /**
     * Gets updated
     * 
     * @return Value for updated.
     **/
    public Date getUpdated() {
        return updated;
    }

    /**
     * Sets updated
     * 
     * @param updated New value for updated.
     **/
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * Gets updatedby
     * 
     * @return Value for updatedby.
     **/
    public long getUpdatedby() {
        return updatedby;
    }

    /**
     * Sets updatedby
     * 
     * @param updatedby New value for updatedby.
     **/
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }

    /**
     * Gets issotrx
     * 
     * @return Value for issotrx.
     **/
    public String getIssotrx() {
        return issotrx;
    }

    /**
     * Sets issotrx
     * 
     * @param issotrx New value for issotrx.
     **/
    public void setIssotrx(String issotrx) {
        this.issotrx = issotrx;
    }

    /**
     * Gets documentno
     * 
     * @return Value for documentno.
     **/
    public String getDocumentno() {
        return documentno;
    }

    /**
     * Sets documentno
     * 
     * @param documentno New value for documentno.
     **/
    public void setDocumentno(String documentno) {
        this.documentno = documentno;
    }

    /**
     * Gets docstatus
     * 
     * @return Value for docstatus.
     **/
    public String getDocstatus() {
        return docstatus;
    }

    /**
     * Sets docstatus
     * 
     * @param docstatus New value for docstatus.
     **/
    public void setDocstatus(String docstatus) {
        this.docstatus = docstatus;
    }

    /**
     * Gets docaction
     * 
     * @return Value for docaction.
     **/
    public String getDocaction() {
        return docaction;
    }

    /**
     * Sets docaction
     * 
     * @param docaction New value for docaction.
     **/
    public void setDocaction(String docaction) {
        this.docaction = docaction;
    }

    /**
     * Gets processing
     * 
     * @return Value for processing.
     **/
    public String getProcessing() {
        return processing;
    }

    /**
     * Sets processing
     * 
     * @param processing New value for processing.
     **/
    public void setProcessing(String processing) {
        this.processing = processing;
    }

    /**
     * Gets processed
     * 
     * @return Value for processed.
     **/
    public String getProcessed() {
        return processed;
    }

    /**
     * Sets processed
     * 
     * @param processed New value for processed.
     **/
    public void setProcessed(String processed) {
        this.processed = processed;
    }

    /**
     * Gets cDoctypeId
     * 
     * @return Value for cDoctypeId.
     **/
    public long getCDoctypeId() {
        return cDoctypeId;
    }

    /**
     * Sets cDoctypeId
     * 
     * @param cDoctypeId New value for cDoctypeId.
     **/
    public void setCDoctypeId(long cDoctypeId) {
        this.cDoctypeId = cDoctypeId;
    }

    /**
     * Gets cDoctypetargetId
     * 
     * @return Value for cDoctypetargetId.
     **/
    public long getCDoctypetargetId() {
        return cDoctypetargetId;
    }

    /**
     * Sets cDoctypetargetId
     * 
     * @param cDoctypetargetId New value for cDoctypetargetId.
     **/
    public void setCDoctypetargetId(long cDoctypetargetId) {
        this.cDoctypetargetId = cDoctypetargetId;
    }

    /**
     * Gets description
     * 
     * @return Value for description.
     **/
    public String getDescription() {
        return description;
    }

    /**
     * Sets description
     * 
     * @param description New value for description.
     **/
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Gets isapproved
     * 
     * @return Value for isapproved.
     **/
    public String getIsapproved() {
        return isapproved;
    }

    /**
     * Sets isapproved
     * 
     * @param isapproved New value for isapproved.
     **/
    public void setIsapproved(String isapproved) {
        this.isapproved = isapproved;
    }

    /**
     * Gets iscreditapproved
     * 
     * @return Value for iscreditapproved.
     **/
    public String getIscreditapproved() {
        return iscreditapproved;
    }

    /**
     * Sets iscreditapproved
     * 
     * @param iscreditapproved New value for iscreditapproved.
     **/
    public void setIscreditapproved(String iscreditapproved) {
        this.iscreditapproved = iscreditapproved;
    }

    /**
     * Gets isdelivered
     * 
     * @return Value for isdelivered.
     **/
    public String getIsdelivered() {
        return isdelivered;
    }

    /**
     * Sets isdelivered
     * 
     * @param isdelivered New value for isdelivered.
     **/
    public void setIsdelivered(String isdelivered) {
        this.isdelivered = isdelivered;
    }

    /**
     * Gets isinvoiced
     * 
     * @return Value for isinvoiced.
     **/
    public String getIsinvoiced() {
        return isinvoiced;
    }

    /**
     * Sets isinvoiced
     * 
     * @param isinvoiced New value for isinvoiced.
     **/
    public void setIsinvoiced(String isinvoiced) {
        this.isinvoiced = isinvoiced;
    }

    /**
     * Gets isprinted
     * 
     * @return Value for isprinted.
     **/
    public String getIsprinted() {
        return isprinted;
    }

    /**
     * Sets isprinted
     * 
     * @param isprinted New value for isprinted.
     **/
    public void setIsprinted(String isprinted) {
        this.isprinted = isprinted;
    }

    /**
     * Gets istransferred
     * 
     * @return Value for istransferred.
     **/
    public String getIstransferred() {
        return istransferred;
    }

    /**
     * Sets istransferred
     * 
     * @param istransferred New value for istransferred.
     **/
    public void setIstransferred(String istransferred) {
        this.istransferred = istransferred;
    }

    /**
     * Gets isselected
     * 
     * @return Value for isselected.
     **/
    public String getIsselected() {
        return isselected;
    }

    /**
     * Sets isselected
     * 
     * @param isselected New value for isselected.
     **/
    public void setIsselected(String isselected) {
        this.isselected = isselected;
    }

    /**
     * Gets salesrepId
     * 
     * @return Value for salesrepId.
     **/
    public long getSalesrepId() {
        return salesrepId;
    }

    /**
     * Sets salesrepId
     * 
     * @param salesrepId New value for salesrepId.
     **/
    public void setSalesrepId(long salesrepId) {
        this.salesrepId = salesrepId;
    }

    /**
     * Gets dateordered
     * 
     * @return Value for dateordered.
     **/
    public Date getDateordered() {
        return dateordered;
    }

    /**
     * Sets dateordered
     * 
     * @param dateordered New value for dateordered.
     **/
    public void setDateordered(Date dateordered) {
        this.dateordered = dateordered;
    }

    /**
     * Gets datepromised
     * 
     * @return Value for datepromised.
     **/
    public Date getDatepromised() {
        return datepromised;
    }

    /**
     * Sets datepromised
     * 
     * @param datepromised New value for datepromised.
     **/
    public void setDatepromised(Date datepromised) {
        this.datepromised = datepromised;
    }

    /**
     * Gets dateprinted
     * 
     * @return Value for dateprinted.
     **/
    public Date getDateprinted() {
        return dateprinted;
    }

    /**
     * Sets dateprinted
     * 
     * @param dateprinted New value for dateprinted.
     **/
    public void setDateprinted(Date dateprinted) {
        this.dateprinted = dateprinted;
    }

    /**
     * Gets dateacct
     * 
     * @return Value for dateacct.
     **/
    public Date getDateacct() {
        return dateacct;
    }

    /**
     * Sets dateacct
     * 
     * @param dateacct New value for dateacct.
     **/
    public void setDateacct(Date dateacct) {
        this.dateacct = dateacct;
    }

    /**
     * Gets cBpartnerId
     * 
     * @return Value for cBpartnerId.
     **/
    public long getCBpartnerId() {
        return cBpartnerId;
    }

    /**
     * Sets cBpartnerId
     * 
     * @param cBpartnerId New value for cBpartnerId.
     **/
    public void setCBpartnerId(long cBpartnerId) {
        this.cBpartnerId = cBpartnerId;
    }

    /**
     * Gets cBpartnerLocationId
     * 
     * @return Value for cBpartnerLocationId.
     **/
    public long getCBpartnerLocationId() {
        return cBpartnerLocationId;
    }

    /**
     * Sets cBpartnerLocationId
     * 
     * @param cBpartnerLocationId New value for cBpartnerLocationId.
     **/
    public void setCBpartnerLocationId(long cBpartnerLocationId) {
        this.cBpartnerLocationId = cBpartnerLocationId;
    }

    /**
     * Gets poreference
     * 
     * @return Value for poreference.
     **/
    public String getPoreference() {
        return poreference;
    }

    /**
     * Sets poreference
     * 
     * @param poreference New value for poreference.
     **/
    public void setPoreference(String poreference) {
        this.poreference = poreference;
    }

    /**
     * Gets isdiscountprinted
     * 
     * @return Value for isdiscountprinted.
     **/
    public String getIsdiscountprinted() {
        return isdiscountprinted;
    }

    /**
     * Sets isdiscountprinted
     * 
     * @param isdiscountprinted New value for isdiscountprinted.
     **/
    public void setIsdiscountprinted(String isdiscountprinted) {
        this.isdiscountprinted = isdiscountprinted;
    }

    /**
     * Gets cCurrencyId
     * 
     * @return Value for cCurrencyId.
     **/
    public long getCCurrencyId() {
        return cCurrencyId;
    }

    /**
     * Sets cCurrencyId
     * 
     * @param cCurrencyId New value for cCurrencyId.
     **/
    public void setCCurrencyId(long cCurrencyId) {
        this.cCurrencyId = cCurrencyId;
    }

    /**
     * Gets paymentrule
     * 
     * @return Value for paymentrule.
     **/
    public String getPaymentrule() {
        return paymentrule;
    }

    /**
     * Sets paymentrule
     * 
     * @param paymentrule New value for paymentrule.
     **/
    public void setPaymentrule(String paymentrule) {
        this.paymentrule = paymentrule;
    }

    /**
     * Gets cPaymenttermId
     * 
     * @return Value for cPaymenttermId.
     **/
    public long getCPaymenttermId() {
        return cPaymenttermId;
    }

    /**
     * Sets cPaymenttermId
     * 
     * @param cPaymenttermId New value for cPaymenttermId.
     **/
    public void setCPaymenttermId(long cPaymenttermId) {
        this.cPaymenttermId = cPaymenttermId;
    }

    /**
     * Gets invoicerule
     * 
     * @return Value for invoicerule.
     **/
    public String getInvoicerule() {
        return invoicerule;
    }

    /**
     * Sets invoicerule
     * 
     * @param invoicerule New value for invoicerule.
     **/
    public void setInvoicerule(String invoicerule) {
        this.invoicerule = invoicerule;
    }

    /**
     * Gets deliveryrule
     * 
     * @return Value for deliveryrule.
     **/
    public String getDeliveryrule() {
        return deliveryrule;
    }

    /**
     * Sets deliveryrule
     * 
     * @param deliveryrule New value for deliveryrule.
     **/
    public void setDeliveryrule(String deliveryrule) {
        this.deliveryrule = deliveryrule;
    }

    /**
     * Gets freightcostrule
     * 
     * @return Value for freightcostrule.
     **/
    public String getFreightcostrule() {
        return freightcostrule;
    }

    /**
     * Sets freightcostrule
     * 
     * @param freightcostrule New value for freightcostrule.
     **/
    public void setFreightcostrule(String freightcostrule) {
        this.freightcostrule = freightcostrule;
    }

    /**
     * Gets freightamt
     * 
     * @return Value for freightamt.
     **/
    public BigDecimal getFreightamt() {
        return freightamt;
    }

    /**
     * Sets freightamt
     * 
     * @param freightamt New value for freightamt.
     **/
    public void setFreightamt(BigDecimal freightamt) {
        this.freightamt = freightamt;
    }

    /**
     * Gets deliveryviarule
     * 
     * @return Value for deliveryviarule.
     **/
    public String getDeliveryviarule() {
        return deliveryviarule;
    }

    /**
     * Sets deliveryviarule
     * 
     * @param deliveryviarule New value for deliveryviarule.
     **/
    public void setDeliveryviarule(String deliveryviarule) {
        this.deliveryviarule = deliveryviarule;
    }

    /**
     * Gets mShipperId
     * 
     * @return Value for mShipperId.
     **/
    public Long getMShipperId() {
        return mShipperId;
    }

    /**
     * Sets mShipperId
     * 
     * @param mShipperId New value for mShipperId.
     **/
    public void setMShipperId(Long mShipperId) {
        this.mShipperId = mShipperId;
    }

    /**
     * Gets cChargeId
     * 
     * @return Value for cChargeId.
     **/
    public Long getCChargeId() {
        return cChargeId;
    }

    /**
     * Sets cChargeId
     * 
     * @param cChargeId New value for cChargeId.
     **/
    public void setCChargeId(Long cChargeId) {
        this.cChargeId = cChargeId;
    }

    /**
     * Gets chargeamt
     * 
     * @return Value for chargeamt.
     **/
    public BigDecimal getChargeamt() {
        return chargeamt;
    }

    /**
     * Sets chargeamt
     * 
     * @param chargeamt New value for chargeamt.
     **/
    public void setChargeamt(BigDecimal chargeamt) {
        this.chargeamt = chargeamt;
    }

    /**
     * Gets priorityrule
     * 
     * @return Value for priorityrule.
     **/
    public String getPriorityrule() {
        return priorityrule;
    }

    /**
     * Sets priorityrule
     * 
     * @param priorityrule New value for priorityrule.
     **/
    public void setPriorityrule(String priorityrule) {
        this.priorityrule = priorityrule;
    }

    /**
     * Gets totallines
     * 
     * @return Value for totallines.
     **/
    public BigDecimal getTotallines() {
        return totallines;
    }

    /**
     * Sets totallines
     * 
     * @param totallines New value for totallines.
     **/
    public void setTotallines(BigDecimal totallines) {
        this.totallines = totallines;
    }

    /**
     * Gets grandtotal
     * 
     * @return Value for grandtotal.
     **/
    public BigDecimal getGrandtotal() {
        return grandtotal;
    }

    /**
     * Sets grandtotal
     * 
     * @param grandtotal New value for grandtotal.
     **/
    public void setGrandtotal(BigDecimal grandtotal) {
        this.grandtotal = grandtotal;
    }

    /**
     * Gets mWarehouseId
     * 
     * @return Value for mWarehouseId.
     **/
    public long getMWarehouseId() {
        return mWarehouseId;
    }

    /**
     * Sets mWarehouseId
     * 
     * @param mWarehouseId New value for mWarehouseId.
     **/
    public void setMWarehouseId(long mWarehouseId) {
        this.mWarehouseId = mWarehouseId;
    }

    /**
     * Gets mPricelistId
     * 
     * @return Value for mPricelistId.
     **/
    public long getMPricelistId() {
        return mPricelistId;
    }

    /**
     * Sets mPricelistId
     * 
     * @param mPricelistId New value for mPricelistId.
     **/
    public void setMPricelistId(long mPricelistId) {
        this.mPricelistId = mPricelistId;
    }

    /**
     * Gets istaxincluded
     * 
     * @return Value for istaxincluded.
     **/
    public String getIstaxincluded() {
        return istaxincluded;
    }

    /**
     * Sets istaxincluded
     * 
     * @param istaxincluded New value for istaxincluded.
     **/
    public void setIstaxincluded(String istaxincluded) {
        this.istaxincluded = istaxincluded;
    }

    /**
     * Gets cCampaignId
     * 
     * @return Value for cCampaignId.
     **/
    public Long getCCampaignId() {
        return cCampaignId;
    }

    /**
     * Sets cCampaignId
     * 
     * @param cCampaignId New value for cCampaignId.
     **/
    public void setCCampaignId(Long cCampaignId) {
        this.cCampaignId = cCampaignId;
    }

    /**
     * Gets cProjectId
     * 
     * @return Value for cProjectId.
     **/
    public Long getCProjectId() {
        return cProjectId;
    }

    /**
     * Sets cProjectId
     * 
     * @param cProjectId New value for cProjectId.
     **/
    public void setCProjectId(Long cProjectId) {
        this.cProjectId = cProjectId;
    }

    /**
     * Gets cActivityId
     * 
     * @return Value for cActivityId.
     **/
    public Long getCActivityId() {
        return cActivityId;
    }

    /**
     * Sets cActivityId
     * 
     * @param cActivityId New value for cActivityId.
     **/
    public void setCActivityId(Long cActivityId) {
        this.cActivityId = cActivityId;
    }

    /**
     * Gets posted
     * 
     * @return Value for posted.
     **/
    public String getPosted() {
        return posted;
    }

    /**
     * Sets posted
     * 
     * @param posted New value for posted.
     **/
    public void setPosted(String posted) {
        this.posted = posted;
    }

    /**
     * Gets cPaymentId
     * 
     * @return Value for cPaymentId.
     **/
    public Long getCPaymentId() {
        return cPaymentId;
    }

    /**
     * Sets cPaymentId
     * 
     * @param cPaymentId New value for cPaymentId.
     **/
    public void setCPaymentId(Long cPaymentId) {
        this.cPaymentId = cPaymentId;
    }

    /**
     * Gets cCashlineId
     * 
     * @return Value for cCashlineId.
     **/
    public Long getCCashlineId() {
        return cCashlineId;
    }

    /**
     * Sets cCashlineId
     * 
     * @param cCashlineId New value for cCashlineId.
     **/
    public void setCCashlineId(Long cCashlineId) {
        this.cCashlineId = cCashlineId;
    }

    /**
     * Gets sendemail
     * 
     * @return Value for sendemail.
     **/
    public String getSendemail() {
        return sendemail;
    }

    /**
     * Sets sendemail
     * 
     * @param sendemail New value for sendemail.
     **/
    public void setSendemail(String sendemail) {
        this.sendemail = sendemail;
    }

    /**
     * Gets adUserId
     * 
     * @return Value for adUserId.
     **/
    public Long getAdUserId() {
        return adUserId;
    }

    /**
     * Sets adUserId
     * 
     * @param adUserId New value for adUserId.
     **/
    public void setAdUserId(Long adUserId) {
        this.adUserId = adUserId;
    }

    /**
     * Gets copyfrom
     * 
     * @return Value for copyfrom.
     **/
    public String getCopyfrom() {
        return copyfrom;
    }

    /**
     * Sets copyfrom
     * 
     * @param copyfrom New value for copyfrom.
     **/
    public void setCopyfrom(String copyfrom) {
        this.copyfrom = copyfrom;
    }

    /**
     * Gets isselfservice
     * 
     * @return Value for isselfservice.
     **/
    public String getIsselfservice() {
        return isselfservice;
    }

    /**
     * Sets isselfservice
     * 
     * @param isselfservice New value for isselfservice.
     **/
    public void setIsselfservice(String isselfservice) {
        this.isselfservice = isselfservice;
    }

    /**
     * Gets adOrgtrxId
     * 
     * @return Value for adOrgtrxId.
     **/
    public Long getAdOrgtrxId() {
        return adOrgtrxId;
    }

    /**
     * Sets adOrgtrxId
     * 
     * @param adOrgtrxId New value for adOrgtrxId.
     **/
    public void setAdOrgtrxId(Long adOrgtrxId) {
        this.adOrgtrxId = adOrgtrxId;
    }

    /**
     * Gets user1Id
     * 
     * @return Value for user1Id.
     **/
    public Long getUser1Id() {
        return user1Id;
    }

    /**
     * Sets user1Id
     * 
     * @param user1Id New value for user1Id.
     **/
    public void setUser1Id(Long user1Id) {
        this.user1Id = user1Id;
    }

    /**
     * Gets user2Id
     * 
     * @return Value for user2Id.
     **/
    public Long getUser2Id() {
        return user2Id;
    }

    /**
     * Sets user2Id
     * 
     * @param user2Id New value for user2Id.
     **/
    public void setUser2Id(Long user2Id) {
        this.user2Id = user2Id;
    }

    /**
     * Gets cConversiontypeId
     * 
     * @return Value for cConversiontypeId.
     **/
    public Long getCConversiontypeId() {
        return cConversiontypeId;
    }

    /**
     * Sets cConversiontypeId
     * 
     * @param cConversiontypeId New value for cConversiontypeId.
     **/
    public void setCConversiontypeId(Long cConversiontypeId) {
        this.cConversiontypeId = cConversiontypeId;
    }

    /**
     * Gets billBpartnerId
     * 
     * @return Value for billBpartnerId.
     **/
    public long getBillBpartnerId() {
        return billBpartnerId;
    }

    /**
     * Sets billBpartnerId
     * 
     * @param billBpartnerId New value for billBpartnerId.
     **/
    public void setBillBpartnerId(long billBpartnerId) {
        this.billBpartnerId = billBpartnerId;
    }

    /**
     * Gets billLocationId
     * 
     * @return Value for billLocationId.
     **/
    public long getBillLocationId() {
        return billLocationId;
    }

    /**
     * Sets billLocationId
     * 
     * @param billLocationId New value for billLocationId.
     **/
    public void setBillLocationId(long billLocationId) {
        this.billLocationId = billLocationId;
    }

    /**
     * Gets billUserId
     * 
     * @return Value for billUserId.
     **/
    public Long getBillUserId() {
        return billUserId;
    }

    /**
     * Sets billUserId
     * 
     * @param billUserId New value for billUserId.
     **/
    public void setBillUserId(Long billUserId) {
        this.billUserId = billUserId;
    }

    /**
     * Gets payBpartnerId
     * 
     * @return Value for payBpartnerId.
     **/
    public Long getPayBpartnerId() {
        return payBpartnerId;
    }

    /**
     * Sets payBpartnerId
     * 
     * @param payBpartnerId New value for payBpartnerId.
     **/
    public void setPayBpartnerId(Long payBpartnerId) {
        this.payBpartnerId = payBpartnerId;
    }

    /**
     * Gets payLocationId
     * 
     * @return Value for payLocationId.
     **/
    public Long getPayLocationId() {
        return payLocationId;
    }

    /**
     * Sets payLocationId
     * 
     * @param payLocationId New value for payLocationId.
     **/
    public void setPayLocationId(Long payLocationId) {
        this.payLocationId = payLocationId;
    }

    /**
     * Gets refOrderId
     * 
     * @return Value for refOrderId.
     **/
    public Long getRefOrderId() {
        return refOrderId;
    }

    /**
     * Sets refOrderId
     * 
     * @param refOrderId New value for refOrderId.
     **/
    public void setRefOrderId(Long refOrderId) {
        this.refOrderId = refOrderId;
    }

    /**
     * Gets isdropship
     * 
     * @return Value for isdropship.
     **/
    public String getIsdropship() {
        return isdropship;
    }

    /**
     * Sets isdropship
     * 
     * @param isdropship New value for isdropship.
     **/
    public void setIsdropship(String isdropship) {
        this.isdropship = isdropship;
    }

    /**
     * Gets description2
     * 
     * @return Value for description2.
     **/
    public String getDescription2() {
        return description2;
    }

    /**
     * Sets description2
     * 
     * @param description2 New value for description2.
     **/
    public void setDescription2(String description2) {
        this.description2 = description2;
    }

    /**
     * Gets testId
     * 
     * @return Value for testId.
     **/
    public Long getTestId() {
        return testId;
    }

    /**
     * Sets testId
     * 
     * @param testId New value for testId.
     **/
    public void setTestId(Long testId) {
        this.testId = testId;
    }

    /**
     * Gets zcreatefromattribute
     * 
     * @return Value for zcreatefromattribute.
     **/
    public String getZcreatefromattribute() {
        return zcreatefromattribute;
    }

    /**
     * Sets zcreatefromattribute
     * 
     * @param zcreatefromattribute New value for zcreatefromattribute.
     **/
    public void setZcreatefromattribute(String zcreatefromattribute) {
        this.zcreatefromattribute = zcreatefromattribute;
    }

    /**
     * Gets zTransportmode
     * 
     * @return Value for zTransportmode.
     **/
    public String getZTransportmode() {
        return zTransportmode;
    }

    /**
     * Sets zTransportmode
     * 
     * @param zTransportmode New value for zTransportmode.
     **/
    public void setZTransportmode(String zTransportmode) {
        this.zTransportmode = zTransportmode;
    }

    /**
     * Gets zIncotermsId
     * 
     * @return Value for zIncotermsId.
     **/
    public Long getZIncotermsId() {
        return zIncotermsId;
    }

    /**
     * Sets zIncotermsId
     * 
     * @param zIncotermsId New value for zIncotermsId.
     **/
    public void setZIncotermsId(Long zIncotermsId) {
        this.zIncotermsId = zIncotermsId;
    }

    /**
     * Gets zIscompleet
     * 
     * @return Value for zIscompleet.
     **/
    public String getZIscompleet() {
        return zIscompleet;
    }

    /**
     * Sets zIscompleet
     * 
     * @param zIscompleet New value for zIscompleet.
     **/
    public void setZIscompleet(String zIscompleet) {
        this.zIscompleet = zIscompleet;
    }

    /**
     * Gets volume
     * 
     * @return Value for volume.
     **/
    public BigDecimal getVolume() {
        return volume;
    }

    /**
     * Sets volume
     * 
     * @param volume New value for volume.
     **/
    public void setVolume(BigDecimal volume) {
        this.volume = volume;
    }

    /**
     * Gets weight
     * 
     * @return Value for weight.
     **/
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * Sets weight
     * 
     * @param weight New value for weight.
     **/
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * Gets cBpartnersrId
     * 
     * @return Value for cBpartnersrId.
     **/
    public Long getCBpartnersrId() {
        return cBpartnersrId;
    }

    /**
     * Sets cBpartnersrId
     * 
     * @param cBpartnersrId New value for cBpartnersrId.
     **/
    public void setCBpartnersrId(Long cBpartnersrId) {
        this.cBpartnersrId = cBpartnersrId;
    }

    /**
     * Gets cBpBankaccountId
     * 
     * @return Value for cBpBankaccountId.
     **/
    public Long getCBpBankaccountId() {
        return cBpBankaccountId;
    }

    /**
     * Sets cBpBankaccountId
     * 
     * @param cBpBankaccountId New value for cBpBankaccountId.
     **/
    public void setCBpBankaccountId(Long cBpBankaccountId) {
        this.cBpBankaccountId = cBpBankaccountId;
    }

    /**
     * Gets isreturntrx
     * 
     * @return Value for isreturntrx.
     **/
    public String getIsreturntrx() {
        return isreturntrx;
    }

    /**
     * Sets isreturntrx
     * 
     * @param isreturntrx New value for isreturntrx.
     **/
    public void setIsreturntrx(String isreturntrx) {
        this.isreturntrx = isreturntrx;
    }

    /**
     * Gets mReturnpolicyId
     * 
     * @return Value for mReturnpolicyId.
     **/
    public Long getMReturnpolicyId() {
        return mReturnpolicyId;
    }

    /**
     * Sets mReturnpolicyId
     * 
     * @param mReturnpolicyId New value for mReturnpolicyId.
     **/
    public void setMReturnpolicyId(Long mReturnpolicyId) {
        this.mReturnpolicyId = mReturnpolicyId;
    }

    /**
     * Gets mRmacategoryId
     * 
     * @return Value for mRmacategoryId.
     **/
    public Long getMRmacategoryId() {
        return mRmacategoryId;
    }

    /**
     * Sets mRmacategoryId
     * 
     * @param mRmacategoryId New value for mRmacategoryId.
     **/
    public void setMRmacategoryId(Long mRmacategoryId) {
        this.mRmacategoryId = mRmacategoryId;
    }

    /**
     * Gets origInoutId
     * 
     * @return Value for origInoutId.
     **/
    public Long getOrigInoutId() {
        return origInoutId;
    }

    /**
     * Sets origInoutId
     * 
     * @param origInoutId New value for origInoutId.
     **/
    public void setOrigInoutId(Long origInoutId) {
        this.origInoutId = origInoutId;
    }

    /**
     * Gets origOrderId
     * 
     * @return Value for origOrderId.
     **/
    public Long getOrigOrderId() {
        return origOrderId;
    }

    /**
     * Sets origOrderId
     * 
     * @param origOrderId New value for origOrderId.
     **/
    public void setOrigOrderId(Long origOrderId) {
        this.origOrderId = origOrderId;
    }

    /**
     * Gets zexplodesubcontractingorder
     * 
     * @return Value for zexplodesubcontractingorder.
     **/
    public String getZexplodesubcontractingorder() {
        return zexplodesubcontractingorder;
    }

    /**
     * Sets zexplodesubcontractingorder
     * 
     * @param zexplodesubcontractingorder New value for zexplodesubcontractingorder.
     **/
    public void setZexplodesubcontractingorder(String zexplodesubcontractingorder) {
        this.zexplodesubcontractingorder = zexplodesubcontractingorder;
    }

    /**
     * Gets isupdateable
     * 
     * @return Value for isupdateable.
     **/
    public String getIsupdateable() {
        return isupdateable;
    }

    /**
     * Sets isupdateable
     * 
     * @param isupdateable New value for isupdateable.
     **/
    public void setIsupdateable(String isupdateable) {
        this.isupdateable = isupdateable;
    }

    /**
     * Gets createfrom
     * 
     * @return Value for createfrom.
     **/
    public String getCreatefrom() {
        return createfrom;
    }

    /**
     * Sets createfrom
     * 
     * @param createfrom New value for createfrom.
     **/
    public void setCreatefrom(String createfrom) {
        this.createfrom = createfrom;
    }

    /**
     * Gets xxApplieddiscount
     * 
     * @return Value for xxApplieddiscount.
     **/
    public String getXxApplieddiscount() {
        return xxApplieddiscount;
    }

    /**
     * Sets xxApplieddiscount
     * 
     * @param xxApplieddiscount New value for xxApplieddiscount.
     **/
    public void setXxApplieddiscount(String xxApplieddiscount) {
        this.xxApplieddiscount = xxApplieddiscount;
    }

    /**
     * Gets withmodification
     * 
     * @return Value for withmodification.
     **/
    public String getWithmodification() {
        return withmodification;
    }

    /**
     * Sets withmodification
     * 
     * @param withmodification New value for withmodification.
     **/
    public void setWithmodification(String withmodification) {
        this.withmodification = withmodification;
    }

    /**
     * Gets xxCommandedelegue
     * 
     * @return Value for xxCommandedelegue.
     **/
    public String getXxCommandedelegue() {
        return xxCommandedelegue;
    }

    /**
     * Sets xxCommandedelegue
     * 
     * @param xxCommandedelegue New value for xxCommandedelegue.
     **/
    public void setXxCommandedelegue(String xxCommandedelegue) {
        this.xxCommandedelegue = xxCommandedelegue;
    }

    /**
     * Gets xxIsretfromautrelogiciel
     * 
     * @return Value for xxIsretfromautrelogiciel.
     **/
    public String getXxIsretfromautrelogiciel() {
        return xxIsretfromautrelogiciel;
    }

    /**
     * Sets xxIsretfromautrelogiciel
     * 
     * @param xxIsretfromautrelogiciel New value for xxIsretfromautrelogiciel.
     **/
    public void setXxIsretfromautrelogiciel(String xxIsretfromautrelogiciel) {
        this.xxIsretfromautrelogiciel = xxIsretfromautrelogiciel;
    }

    /**
     * Gets isquotareturned
     * 
     * @return Value for isquotareturned.
     **/
    public String getIsquotareturned() {
        return isquotareturned;
    }

    /**
     * Sets isquotareturned
     * 
     * @param isquotareturned New value for isquotareturned.
     **/
    public void setIsquotareturned(String isquotareturned) {
        this.isquotareturned = isquotareturned;
    }

    /**
     * Gets xxReturnquota
     * 
     * @return Value for xxReturnquota.
     **/
    public String getXxReturnquota() {
        return xxReturnquota;
    }

    /**
     * Sets xxReturnquota
     * 
     * @param xxReturnquota New value for xxReturnquota.
     **/
    public void setXxReturnquota(String xxReturnquota) {
        this.xxReturnquota = xxReturnquota;
    }

    /**
     * Gets globalDiscount
     * 
     * @return Value for globalDiscount.
     **/
    public BigDecimal getGlobalDiscount() {
        return globalDiscount;
    }

    /**
     * Sets globalDiscount
     * 
     * @param globalDiscount New value for globalDiscount.
     **/
    public void setGlobalDiscount(BigDecimal globalDiscount) {
        this.globalDiscount = globalDiscount;
    }

    /**
     * Gets generateto
     * 
     * @return Value for generateto.
     **/
    public String getGenerateto() {
        return generateto;
    }

    /**
     * Sets generateto
     * 
     * @param generateto New value for generateto.
     **/
    public void setGenerateto(String generateto) {
        this.generateto = generateto;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof COrder))
            return false;
        
        COrder that = (COrder)o;

        if (adClientId != that.adClientId)
            return false;
        

        if (adOrgId != that.adOrgId)
            return false;
        

        if (isactive != null ? !isactive.equals(that.isactive) : that.isactive != null)
            return false;
        

        if (created != null ? !created.equals(that.created) : that.created != null)
            return false;
        

        if (createdby != that.createdby)
            return false;
        

        if (updated != null ? !updated.equals(that.updated) : that.updated != null)
            return false;
        

        if (updatedby != that.updatedby)
            return false;
        

        if (issotrx != null ? !issotrx.equals(that.issotrx) : that.issotrx != null)
            return false;
        

        if (documentno != null ? !documentno.equals(that.documentno) : that.documentno != null)
            return false;
        

        if (docstatus != null ? !docstatus.equals(that.docstatus) : that.docstatus != null)
            return false;
        

        if (docaction != null ? !docaction.equals(that.docaction) : that.docaction != null)
            return false;
        

        if (processing != null ? !processing.equals(that.processing) : that.processing != null)
            return false;
        

        if (processed != null ? !processed.equals(that.processed) : that.processed != null)
            return false;
        

        if (cDoctypeId != that.cDoctypeId)
            return false;
        

        if (cDoctypetargetId != that.cDoctypetargetId)
            return false;
        

        if (description != null ? !description.equals(that.description) : that.description != null)
            return false;
        

        if (isapproved != null ? !isapproved.equals(that.isapproved) : that.isapproved != null)
            return false;
        

        if (iscreditapproved != null ? !iscreditapproved.equals(that.iscreditapproved) : that.iscreditapproved != null)
            return false;
        

        if (isdelivered != null ? !isdelivered.equals(that.isdelivered) : that.isdelivered != null)
            return false;
        

        if (isinvoiced != null ? !isinvoiced.equals(that.isinvoiced) : that.isinvoiced != null)
            return false;
        

        if (isprinted != null ? !isprinted.equals(that.isprinted) : that.isprinted != null)
            return false;
        

        if (istransferred != null ? !istransferred.equals(that.istransferred) : that.istransferred != null)
            return false;
        

        if (isselected != null ? !isselected.equals(that.isselected) : that.isselected != null)
            return false;
        

        if (salesrepId != that.salesrepId)
            return false;
        

        if (dateordered != null ? !dateordered.equals(that.dateordered) : that.dateordered != null)
            return false;
        

        if (datepromised != null ? !datepromised.equals(that.datepromised) : that.datepromised != null)
            return false;
        

        if (dateprinted != null ? !dateprinted.equals(that.dateprinted) : that.dateprinted != null)
            return false;
        

        if (dateacct != null ? !dateacct.equals(that.dateacct) : that.dateacct != null)
            return false;
        

        if (cBpartnerId != that.cBpartnerId)
            return false;
        

        if (cBpartnerLocationId != that.cBpartnerLocationId)
            return false;
        

        if (poreference != null ? !poreference.equals(that.poreference) : that.poreference != null)
            return false;
        

        if (isdiscountprinted != null ? !isdiscountprinted.equals(that.isdiscountprinted) : that.isdiscountprinted != null)
            return false;
        

        if (cCurrencyId != that.cCurrencyId)
            return false;
        

        if (paymentrule != null ? !paymentrule.equals(that.paymentrule) : that.paymentrule != null)
            return false;
        

        if (cPaymenttermId != that.cPaymenttermId)
            return false;
        

        if (invoicerule != null ? !invoicerule.equals(that.invoicerule) : that.invoicerule != null)
            return false;
        

        if (deliveryrule != null ? !deliveryrule.equals(that.deliveryrule) : that.deliveryrule != null)
            return false;
        

        if (freightcostrule != null ? !freightcostrule.equals(that.freightcostrule) : that.freightcostrule != null)
            return false;
        

        if (freightamt != null ? !freightamt.equals(that.freightamt) : that.freightamt != null)
            return false;
        

        if (deliveryviarule != null ? !deliveryviarule.equals(that.deliveryviarule) : that.deliveryviarule != null)
            return false;
        

        if (mShipperId != null ? !mShipperId.equals(that.mShipperId) : that.mShipperId != null)
            return false;
        

        if (cChargeId != null ? !cChargeId.equals(that.cChargeId) : that.cChargeId != null)
            return false;
        

        if (chargeamt != null ? !chargeamt.equals(that.chargeamt) : that.chargeamt != null)
            return false;
        

        if (priorityrule != null ? !priorityrule.equals(that.priorityrule) : that.priorityrule != null)
            return false;
        

        if (totallines != null ? !totallines.equals(that.totallines) : that.totallines != null)
            return false;
        

        if (grandtotal != null ? !grandtotal.equals(that.grandtotal) : that.grandtotal != null)
            return false;
        

        if (mWarehouseId != that.mWarehouseId)
            return false;
        

        if (mPricelistId != that.mPricelistId)
            return false;
        

        if (istaxincluded != null ? !istaxincluded.equals(that.istaxincluded) : that.istaxincluded != null)
            return false;
        

        if (cCampaignId != null ? !cCampaignId.equals(that.cCampaignId) : that.cCampaignId != null)
            return false;
        

        if (cProjectId != null ? !cProjectId.equals(that.cProjectId) : that.cProjectId != null)
            return false;
        

        if (cActivityId != null ? !cActivityId.equals(that.cActivityId) : that.cActivityId != null)
            return false;
        

        if (posted != null ? !posted.equals(that.posted) : that.posted != null)
            return false;
        

        if (cPaymentId != null ? !cPaymentId.equals(that.cPaymentId) : that.cPaymentId != null)
            return false;
        

        if (cCashlineId != null ? !cCashlineId.equals(that.cCashlineId) : that.cCashlineId != null)
            return false;
        

        if (sendemail != null ? !sendemail.equals(that.sendemail) : that.sendemail != null)
            return false;
        

        if (adUserId != null ? !adUserId.equals(that.adUserId) : that.adUserId != null)
            return false;
        

        if (copyfrom != null ? !copyfrom.equals(that.copyfrom) : that.copyfrom != null)
            return false;
        

        if (isselfservice != null ? !isselfservice.equals(that.isselfservice) : that.isselfservice != null)
            return false;
        

        if (adOrgtrxId != null ? !adOrgtrxId.equals(that.adOrgtrxId) : that.adOrgtrxId != null)
            return false;
        

        if (user1Id != null ? !user1Id.equals(that.user1Id) : that.user1Id != null)
            return false;
        

        if (user2Id != null ? !user2Id.equals(that.user2Id) : that.user2Id != null)
            return false;
        

        if (cConversiontypeId != null ? !cConversiontypeId.equals(that.cConversiontypeId) : that.cConversiontypeId != null)
            return false;
        

        if (billBpartnerId != that.billBpartnerId)
            return false;
        

        if (billLocationId != that.billLocationId)
            return false;
        

        if (billUserId != null ? !billUserId.equals(that.billUserId) : that.billUserId != null)
            return false;
        

        if (payBpartnerId != null ? !payBpartnerId.equals(that.payBpartnerId) : that.payBpartnerId != null)
            return false;
        

        if (payLocationId != null ? !payLocationId.equals(that.payLocationId) : that.payLocationId != null)
            return false;
        

        if (refOrderId != null ? !refOrderId.equals(that.refOrderId) : that.refOrderId != null)
            return false;
        

        if (isdropship != null ? !isdropship.equals(that.isdropship) : that.isdropship != null)
            return false;
        

        if (description2 != null ? !description2.equals(that.description2) : that.description2 != null)
            return false;
        

        if (testId != null ? !testId.equals(that.testId) : that.testId != null)
            return false;
        

        if (zcreatefromattribute != null ? !zcreatefromattribute.equals(that.zcreatefromattribute) : that.zcreatefromattribute != null)
            return false;
        

        if (zTransportmode != null ? !zTransportmode.equals(that.zTransportmode) : that.zTransportmode != null)
            return false;
        

        if (zIncotermsId != null ? !zIncotermsId.equals(that.zIncotermsId) : that.zIncotermsId != null)
            return false;
        

        if (zIscompleet != null ? !zIscompleet.equals(that.zIscompleet) : that.zIscompleet != null)
            return false;
        

        if (volume != null ? !volume.equals(that.volume) : that.volume != null)
            return false;
        

        if (weight != null ? !weight.equals(that.weight) : that.weight != null)
            return false;
        

        if (cBpartnersrId != null ? !cBpartnersrId.equals(that.cBpartnersrId) : that.cBpartnersrId != null)
            return false;
        

        if (cBpBankaccountId != null ? !cBpBankaccountId.equals(that.cBpBankaccountId) : that.cBpBankaccountId != null)
            return false;
        

        if (isreturntrx != null ? !isreturntrx.equals(that.isreturntrx) : that.isreturntrx != null)
            return false;
        

        if (mReturnpolicyId != null ? !mReturnpolicyId.equals(that.mReturnpolicyId) : that.mReturnpolicyId != null)
            return false;
        

        if (mRmacategoryId != null ? !mRmacategoryId.equals(that.mRmacategoryId) : that.mRmacategoryId != null)
            return false;
        

        if (origInoutId != null ? !origInoutId.equals(that.origInoutId) : that.origInoutId != null)
            return false;
        

        if (origOrderId != null ? !origOrderId.equals(that.origOrderId) : that.origOrderId != null)
            return false;
        

        if (zexplodesubcontractingorder != null ? !zexplodesubcontractingorder.equals(that.zexplodesubcontractingorder) : that.zexplodesubcontractingorder != null)
            return false;
        

        if (isupdateable != null ? !isupdateable.equals(that.isupdateable) : that.isupdateable != null)
            return false;
        

        if (createfrom != null ? !createfrom.equals(that.createfrom) : that.createfrom != null)
            return false;
        

        if (xxApplieddiscount != null ? !xxApplieddiscount.equals(that.xxApplieddiscount) : that.xxApplieddiscount != null)
            return false;
        

        if (withmodification != null ? !withmodification.equals(that.withmodification) : that.withmodification != null)
            return false;
        

        if (xxCommandedelegue != null ? !xxCommandedelegue.equals(that.xxCommandedelegue) : that.xxCommandedelegue != null)
            return false;
        

        if (xxIsretfromautrelogiciel != null ? !xxIsretfromautrelogiciel.equals(that.xxIsretfromautrelogiciel) : that.xxIsretfromautrelogiciel != null)
            return false;
        

        if (isquotareturned != null ? !isquotareturned.equals(that.isquotareturned) : that.isquotareturned != null)
            return false;
        

        if (xxReturnquota != null ? !xxReturnquota.equals(that.xxReturnquota) : that.xxReturnquota != null)
            return false;
        

        if (globalDiscount != null ? !globalDiscount.equals(that.globalDiscount) : that.globalDiscount != null)
            return false;
        

        if (generateto != null ? !generateto.equals(that.generateto) : that.generateto != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = (int)(adClientId ^ (adClientId >>> 32));

        res = 31 * res + (int)(adOrgId ^ (adOrgId >>> 32));

        res = 31 * res + (isactive != null ? isactive.hashCode() : 0);

        res = 31 * res + (created != null ? created.hashCode() : 0);

        res = 31 * res + (int)(createdby ^ (createdby >>> 32));

        res = 31 * res + (updated != null ? updated.hashCode() : 0);

        res = 31 * res + (int)(updatedby ^ (updatedby >>> 32));

        res = 31 * res + (issotrx != null ? issotrx.hashCode() : 0);

        res = 31 * res + (documentno != null ? documentno.hashCode() : 0);

        res = 31 * res + (docstatus != null ? docstatus.hashCode() : 0);

        res = 31 * res + (docaction != null ? docaction.hashCode() : 0);

        res = 31 * res + (processing != null ? processing.hashCode() : 0);

        res = 31 * res + (processed != null ? processed.hashCode() : 0);

        res = 31 * res + (int)(cDoctypeId ^ (cDoctypeId >>> 32));

        res = 31 * res + (int)(cDoctypetargetId ^ (cDoctypetargetId >>> 32));

        res = 31 * res + (description != null ? description.hashCode() : 0);

        res = 31 * res + (isapproved != null ? isapproved.hashCode() : 0);

        res = 31 * res + (iscreditapproved != null ? iscreditapproved.hashCode() : 0);

        res = 31 * res + (isdelivered != null ? isdelivered.hashCode() : 0);

        res = 31 * res + (isinvoiced != null ? isinvoiced.hashCode() : 0);

        res = 31 * res + (isprinted != null ? isprinted.hashCode() : 0);

        res = 31 * res + (istransferred != null ? istransferred.hashCode() : 0);

        res = 31 * res + (isselected != null ? isselected.hashCode() : 0);

        res = 31 * res + (int)(salesrepId ^ (salesrepId >>> 32));

        res = 31 * res + (dateordered != null ? dateordered.hashCode() : 0);

        res = 31 * res + (datepromised != null ? datepromised.hashCode() : 0);

        res = 31 * res + (dateprinted != null ? dateprinted.hashCode() : 0);

        res = 31 * res + (dateacct != null ? dateacct.hashCode() : 0);

        res = 31 * res + (int)(cBpartnerId ^ (cBpartnerId >>> 32));

        res = 31 * res + (int)(cBpartnerLocationId ^ (cBpartnerLocationId >>> 32));

        res = 31 * res + (poreference != null ? poreference.hashCode() : 0);

        res = 31 * res + (isdiscountprinted != null ? isdiscountprinted.hashCode() : 0);

        res = 31 * res + (int)(cCurrencyId ^ (cCurrencyId >>> 32));

        res = 31 * res + (paymentrule != null ? paymentrule.hashCode() : 0);

        res = 31 * res + (int)(cPaymenttermId ^ (cPaymenttermId >>> 32));

        res = 31 * res + (invoicerule != null ? invoicerule.hashCode() : 0);

        res = 31 * res + (deliveryrule != null ? deliveryrule.hashCode() : 0);

        res = 31 * res + (freightcostrule != null ? freightcostrule.hashCode() : 0);

        res = 31 * res + (freightamt != null ? freightamt.hashCode() : 0);

        res = 31 * res + (deliveryviarule != null ? deliveryviarule.hashCode() : 0);

        res = 31 * res + (mShipperId != null ? mShipperId.hashCode() : 0);

        res = 31 * res + (cChargeId != null ? cChargeId.hashCode() : 0);

        res = 31 * res + (chargeamt != null ? chargeamt.hashCode() : 0);

        res = 31 * res + (priorityrule != null ? priorityrule.hashCode() : 0);

        res = 31 * res + (totallines != null ? totallines.hashCode() : 0);

        res = 31 * res + (grandtotal != null ? grandtotal.hashCode() : 0);

        res = 31 * res + (int)(mWarehouseId ^ (mWarehouseId >>> 32));

        res = 31 * res + (int)(mPricelistId ^ (mPricelistId >>> 32));

        res = 31 * res + (istaxincluded != null ? istaxincluded.hashCode() : 0);

        res = 31 * res + (cCampaignId != null ? cCampaignId.hashCode() : 0);

        res = 31 * res + (cProjectId != null ? cProjectId.hashCode() : 0);

        res = 31 * res + (cActivityId != null ? cActivityId.hashCode() : 0);

        res = 31 * res + (posted != null ? posted.hashCode() : 0);

        res = 31 * res + (cPaymentId != null ? cPaymentId.hashCode() : 0);

        res = 31 * res + (cCashlineId != null ? cCashlineId.hashCode() : 0);

        res = 31 * res + (sendemail != null ? sendemail.hashCode() : 0);

        res = 31 * res + (adUserId != null ? adUserId.hashCode() : 0);

        res = 31 * res + (copyfrom != null ? copyfrom.hashCode() : 0);

        res = 31 * res + (isselfservice != null ? isselfservice.hashCode() : 0);

        res = 31 * res + (adOrgtrxId != null ? adOrgtrxId.hashCode() : 0);

        res = 31 * res + (user1Id != null ? user1Id.hashCode() : 0);

        res = 31 * res + (user2Id != null ? user2Id.hashCode() : 0);

        res = 31 * res + (cConversiontypeId != null ? cConversiontypeId.hashCode() : 0);

        res = 31 * res + (int)(billBpartnerId ^ (billBpartnerId >>> 32));

        res = 31 * res + (int)(billLocationId ^ (billLocationId >>> 32));

        res = 31 * res + (billUserId != null ? billUserId.hashCode() : 0);

        res = 31 * res + (payBpartnerId != null ? payBpartnerId.hashCode() : 0);

        res = 31 * res + (payLocationId != null ? payLocationId.hashCode() : 0);

        res = 31 * res + (refOrderId != null ? refOrderId.hashCode() : 0);

        res = 31 * res + (isdropship != null ? isdropship.hashCode() : 0);

        res = 31 * res + (description2 != null ? description2.hashCode() : 0);

        res = 31 * res + (testId != null ? testId.hashCode() : 0);

        res = 31 * res + (zcreatefromattribute != null ? zcreatefromattribute.hashCode() : 0);

        res = 31 * res + (zTransportmode != null ? zTransportmode.hashCode() : 0);

        res = 31 * res + (zIncotermsId != null ? zIncotermsId.hashCode() : 0);

        res = 31 * res + (zIscompleet != null ? zIscompleet.hashCode() : 0);

        res = 31 * res + (volume != null ? volume.hashCode() : 0);

        res = 31 * res + (weight != null ? weight.hashCode() : 0);

        res = 31 * res + (cBpartnersrId != null ? cBpartnersrId.hashCode() : 0);

        res = 31 * res + (cBpBankaccountId != null ? cBpBankaccountId.hashCode() : 0);

        res = 31 * res + (isreturntrx != null ? isreturntrx.hashCode() : 0);

        res = 31 * res + (mReturnpolicyId != null ? mReturnpolicyId.hashCode() : 0);

        res = 31 * res + (mRmacategoryId != null ? mRmacategoryId.hashCode() : 0);

        res = 31 * res + (origInoutId != null ? origInoutId.hashCode() : 0);

        res = 31 * res + (origOrderId != null ? origOrderId.hashCode() : 0);

        res = 31 * res + (zexplodesubcontractingorder != null ? zexplodesubcontractingorder.hashCode() : 0);

        res = 31 * res + (isupdateable != null ? isupdateable.hashCode() : 0);

        res = 31 * res + (createfrom != null ? createfrom.hashCode() : 0);

        res = 31 * res + (xxApplieddiscount != null ? xxApplieddiscount.hashCode() : 0);

        res = 31 * res + (withmodification != null ? withmodification.hashCode() : 0);

        res = 31 * res + (xxCommandedelegue != null ? xxCommandedelegue.hashCode() : 0);

        res = 31 * res + (xxIsretfromautrelogiciel != null ? xxIsretfromautrelogiciel.hashCode() : 0);

        res = 31 * res + (isquotareturned != null ? isquotareturned.hashCode() : 0);

        res = 31 * res + (xxReturnquota != null ? xxReturnquota.hashCode() : 0);

        res = 31 * res + (globalDiscount != null ? globalDiscount.hashCode() : 0);

        res = 31 * res + (generateto != null ? generateto.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "COrder [" + 
            "adClientId=" + adClientId + ", " + 
            "adOrgId=" + adOrgId + ", " + 
            "isactive=" + isactive + ", " + 
            "created=" + created + ", " + 
            "createdby=" + createdby + ", " + 
            "updated=" + updated + ", " + 
            "updatedby=" + updatedby + ", " + 
            "issotrx=" + issotrx + ", " + 
            "documentno=" + documentno + ", " + 
            "docstatus=" + docstatus + ", " + 
            "docaction=" + docaction + ", " + 
            "processing=" + processing + ", " + 
            "processed=" + processed + ", " + 
            "cDoctypeId=" + cDoctypeId + ", " + 
            "cDoctypetargetId=" + cDoctypetargetId + ", " + 
            "description=" + description + ", " + 
            "isapproved=" + isapproved + ", " + 
            "iscreditapproved=" + iscreditapproved + ", " + 
            "isdelivered=" + isdelivered + ", " + 
            "isinvoiced=" + isinvoiced + ", " + 
            "isprinted=" + isprinted + ", " + 
            "istransferred=" + istransferred + ", " + 
            "isselected=" + isselected + ", " + 
            "salesrepId=" + salesrepId + ", " + 
            "dateordered=" + dateordered + ", " + 
            "datepromised=" + datepromised + ", " + 
            "dateprinted=" + dateprinted + ", " + 
            "dateacct=" + dateacct + ", " + 
            "cBpartnerId=" + cBpartnerId + ", " + 
            "cBpartnerLocationId=" + cBpartnerLocationId + ", " + 
            "poreference=" + poreference + ", " + 
            "isdiscountprinted=" + isdiscountprinted + ", " + 
            "cCurrencyId=" + cCurrencyId + ", " + 
            "paymentrule=" + paymentrule + ", " + 
            "cPaymenttermId=" + cPaymenttermId + ", " + 
            "invoicerule=" + invoicerule + ", " + 
            "deliveryrule=" + deliveryrule + ", " + 
            "freightcostrule=" + freightcostrule + ", " + 
            "freightamt=" + freightamt + ", " + 
            "deliveryviarule=" + deliveryviarule + ", " + 
            "mShipperId=" + mShipperId + ", " + 
            "cChargeId=" + cChargeId + ", " + 
            "chargeamt=" + chargeamt + ", " + 
            "priorityrule=" + priorityrule + ", " + 
            "totallines=" + totallines + ", " + 
            "grandtotal=" + grandtotal + ", " + 
            "mWarehouseId=" + mWarehouseId + ", " + 
            "mPricelistId=" + mPricelistId + ", " + 
            "istaxincluded=" + istaxincluded + ", " + 
            "cCampaignId=" + cCampaignId + ", " + 
            "cProjectId=" + cProjectId + ", " + 
            "cActivityId=" + cActivityId + ", " + 
            "posted=" + posted + ", " + 
            "cPaymentId=" + cPaymentId + ", " + 
            "cCashlineId=" + cCashlineId + ", " + 
            "sendemail=" + sendemail + ", " + 
            "adUserId=" + adUserId + ", " + 
            "copyfrom=" + copyfrom + ", " + 
            "isselfservice=" + isselfservice + ", " + 
            "adOrgtrxId=" + adOrgtrxId + ", " + 
            "user1Id=" + user1Id + ", " + 
            "user2Id=" + user2Id + ", " + 
            "cConversiontypeId=" + cConversiontypeId + ", " + 
            "billBpartnerId=" + billBpartnerId + ", " + 
            "billLocationId=" + billLocationId + ", " + 
            "billUserId=" + billUserId + ", " + 
            "payBpartnerId=" + payBpartnerId + ", " + 
            "payLocationId=" + payLocationId + ", " + 
            "refOrderId=" + refOrderId + ", " + 
            "isdropship=" + isdropship + ", " + 
            "description2=" + description2 + ", " + 
            "testId=" + testId + ", " + 
            "zcreatefromattribute=" + zcreatefromattribute + ", " + 
            "zTransportmode=" + zTransportmode + ", " + 
            "zIncotermsId=" + zIncotermsId + ", " + 
            "zIscompleet=" + zIscompleet + ", " + 
            "volume=" + volume + ", " + 
            "weight=" + weight + ", " + 
            "cBpartnersrId=" + cBpartnersrId + ", " + 
            "cBpBankaccountId=" + cBpBankaccountId + ", " + 
            "isreturntrx=" + isreturntrx + ", " + 
            "mReturnpolicyId=" + mReturnpolicyId + ", " + 
            "mRmacategoryId=" + mRmacategoryId + ", " + 
            "origInoutId=" + origInoutId + ", " + 
            "origOrderId=" + origOrderId + ", " + 
            "zexplodesubcontractingorder=" + zexplodesubcontractingorder + ", " + 
            "isupdateable=" + isupdateable + ", " + 
            "createfrom=" + createfrom + ", " + 
            "xxApplieddiscount=" + xxApplieddiscount + ", " + 
            "withmodification=" + withmodification + ", " + 
            "xxCommandedelegue=" + xxCommandedelegue + ", " + 
            "xxIsretfromautrelogiciel=" + xxIsretfromautrelogiciel + ", " + 
            "isquotareturned=" + isquotareturned + ", " + 
            "xxReturnquota=" + xxReturnquota + ", " + 
            "globalDiscount=" + globalDiscount + ", " + 
            "generateto=" + generateto +
        "]";
    }
}