package com.wanasis.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;

/**
 * MAttributeinstance definition.
 * 
 * This file was generated by Ignite Web Console (11/21/2019, 08:54)
 **/
public class MAttributeinstance implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for adClientId. */
    private long adClientId;

    /** Value for adOrgId. */
    private long adOrgId;

    /** Value for isactive. */
    private String isactive;

    /** Value for created. */
    private Date created;

    /** Value for createdby. */
    private long createdby;

    /** Value for updated. */
    private Date updated;

    /** Value for updatedby. */
    private long updatedby;

    /** Value for mAttributevalueId. */
    private Long mAttributevalueId;

    /** Value for value. */
    private String value;

    /** Value for valuenumber. */
    private BigDecimal valuenumber;

    /** Value for valuedate. */
    private Date valuedate;

    /** Empty constructor. **/
    public MAttributeinstance() {
        // No-op.
    }

    /** Full constructor. **/
    public MAttributeinstance(long adClientId,
        long adOrgId,
        String isactive,
        Date created,
        long createdby,
        Date updated,
        long updatedby,
        Long mAttributevalueId,
        String value,
        BigDecimal valuenumber,
        Date valuedate) {
        this.adClientId = adClientId;
        this.adOrgId = adOrgId;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.mAttributevalueId = mAttributevalueId;
        this.value = value;
        this.valuenumber = valuenumber;
        this.valuedate = valuedate;
    }

    /**
     * Gets adClientId
     * 
     * @return Value for adClientId.
     **/
    public long getAdClientId() {
        return adClientId;
    }

    /**
     * Sets adClientId
     * 
     * @param adClientId New value for adClientId.
     **/
    public void setAdClientId(long adClientId) {
        this.adClientId = adClientId;
    }

    /**
     * Gets adOrgId
     * 
     * @return Value for adOrgId.
     **/
    public long getAdOrgId() {
        return adOrgId;
    }

    /**
     * Sets adOrgId
     * 
     * @param adOrgId New value for adOrgId.
     **/
    public void setAdOrgId(long adOrgId) {
        this.adOrgId = adOrgId;
    }

    /**
     * Gets isactive
     * 
     * @return Value for isactive.
     **/
    public String getIsactive() {
        return isactive;
    }

    /**
     * Sets isactive
     * 
     * @param isactive New value for isactive.
     **/
    public void setIsactive(String isactive) {
        this.isactive = isactive;
    }

    /**
     * Gets created
     * 
     * @return Value for created.
     **/
    public Date getCreated() {
        return created;
    }

    /**
     * Sets created
     * 
     * @param created New value for created.
     **/
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * Gets createdby
     * 
     * @return Value for createdby.
     **/
    public long getCreatedby() {
        return createdby;
    }

    /**
     * Sets createdby
     * 
     * @param createdby New value for createdby.
     **/
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }

    /**
     * Gets updated
     * 
     * @return Value for updated.
     **/
    public Date getUpdated() {
        return updated;
    }

    /**
     * Sets updated
     * 
     * @param updated New value for updated.
     **/
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * Gets updatedby
     * 
     * @return Value for updatedby.
     **/
    public long getUpdatedby() {
        return updatedby;
    }

    /**
     * Sets updatedby
     * 
     * @param updatedby New value for updatedby.
     **/
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }

    /**
     * Gets mAttributevalueId
     * 
     * @return Value for mAttributevalueId.
     **/
    public Long getMAttributevalueId() {
        return mAttributevalueId;
    }

    /**
     * Sets mAttributevalueId
     * 
     * @param mAttributevalueId New value for mAttributevalueId.
     **/
    public void setMAttributevalueId(Long mAttributevalueId) {
        this.mAttributevalueId = mAttributevalueId;
    }

    /**
     * Gets value
     * 
     * @return Value for value.
     **/
    public String getValue() {
        return value;
    }

    /**
     * Sets value
     * 
     * @param value New value for value.
     **/
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets valuenumber
     * 
     * @return Value for valuenumber.
     **/
    public BigDecimal getValuenumber() {
        return valuenumber;
    }

    /**
     * Sets valuenumber
     * 
     * @param valuenumber New value for valuenumber.
     **/
    public void setValuenumber(BigDecimal valuenumber) {
        this.valuenumber = valuenumber;
    }

    /**
     * Gets valuedate
     * 
     * @return Value for valuedate.
     **/
    public Date getValuedate() {
        return valuedate;
    }

    /**
     * Sets valuedate
     * 
     * @param valuedate New value for valuedate.
     **/
    public void setValuedate(Date valuedate) {
        this.valuedate = valuedate;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof MAttributeinstance))
            return false;
        
        MAttributeinstance that = (MAttributeinstance)o;

        if (adClientId != that.adClientId)
            return false;
        

        if (adOrgId != that.adOrgId)
            return false;
        

        if (isactive != null ? !isactive.equals(that.isactive) : that.isactive != null)
            return false;
        

        if (created != null ? !created.equals(that.created) : that.created != null)
            return false;
        

        if (createdby != that.createdby)
            return false;
        

        if (updated != null ? !updated.equals(that.updated) : that.updated != null)
            return false;
        

        if (updatedby != that.updatedby)
            return false;
        

        if (mAttributevalueId != null ? !mAttributevalueId.equals(that.mAttributevalueId) : that.mAttributevalueId != null)
            return false;
        

        if (value != null ? !value.equals(that.value) : that.value != null)
            return false;
        

        if (valuenumber != null ? !valuenumber.equals(that.valuenumber) : that.valuenumber != null)
            return false;
        

        if (valuedate != null ? !valuedate.equals(that.valuedate) : that.valuedate != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = (int)(adClientId ^ (adClientId >>> 32));

        res = 31 * res + (int)(adOrgId ^ (adOrgId >>> 32));

        res = 31 * res + (isactive != null ? isactive.hashCode() : 0);

        res = 31 * res + (created != null ? created.hashCode() : 0);

        res = 31 * res + (int)(createdby ^ (createdby >>> 32));

        res = 31 * res + (updated != null ? updated.hashCode() : 0);

        res = 31 * res + (int)(updatedby ^ (updatedby >>> 32));

        res = 31 * res + (mAttributevalueId != null ? mAttributevalueId.hashCode() : 0);

        res = 31 * res + (value != null ? value.hashCode() : 0);

        res = 31 * res + (valuenumber != null ? valuenumber.hashCode() : 0);

        res = 31 * res + (valuedate != null ? valuedate.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "MAttributeinstance [" + 
            "adClientId=" + adClientId + ", " + 
            "adOrgId=" + adOrgId + ", " + 
            "isactive=" + isactive + ", " + 
            "created=" + created + ", " + 
            "createdby=" + createdby + ", " + 
            "updated=" + updated + ", " + 
            "updatedby=" + updatedby + ", " + 
            "mAttributevalueId=" + mAttributevalueId + ", " + 
            "value=" + value + ", " + 
            "valuenumber=" + valuenumber + ", " + 
            "valuedate=" + valuedate +
        "]";
    }
}