package com.wanasis.model;

import java.io.Serializable;
import java.sql.Date;

/**
 * MAttribute definition.
 * 
 * This file was generated by Ignite Web Console (11/21/2019, 08:54)
 **/
public class MAttribute implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for adClientId. */
    private long adClientId;

    /** Value for adOrgId. */
    private long adOrgId;

    /** Value for isactive. */
    private String isactive;

    /** Value for created. */
    private Date created;

    /** Value for createdby. */
    private long createdby;

    /** Value for updated. */
    private Date updated;

    /** Value for updatedby. */
    private long updatedby;

    /** Value for name. */
    private String name;

    /** Value for description. */
    private String description;

    /** Value for ismandatory. */
    private String ismandatory;

    /** Value for isinstanceattribute. */
    private String isinstanceattribute;

    /** Value for mAttributesearchId. */
    private Long mAttributesearchId;

    /** Value for attributevaluetype. */
    private String attributevaluetype;

    /** Value for prefix. */
    private String prefix;

    /** Value for suffix. */
    private String suffix;

    /** Empty constructor. **/
    public MAttribute() {
        // No-op.
    }

    /** Full constructor. **/
    public MAttribute(long adClientId,
        long adOrgId,
        String isactive,
        Date created,
        long createdby,
        Date updated,
        long updatedby,
        String name,
        String description,
        String ismandatory,
        String isinstanceattribute,
        Long mAttributesearchId,
        String attributevaluetype,
        String prefix,
        String suffix) {
        this.adClientId = adClientId;
        this.adOrgId = adOrgId;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.name = name;
        this.description = description;
        this.ismandatory = ismandatory;
        this.isinstanceattribute = isinstanceattribute;
        this.mAttributesearchId = mAttributesearchId;
        this.attributevaluetype = attributevaluetype;
        this.prefix = prefix;
        this.suffix = suffix;
    }

    /**
     * Gets adClientId
     * 
     * @return Value for adClientId.
     **/
    public long getAdClientId() {
        return adClientId;
    }

    /**
     * Sets adClientId
     * 
     * @param adClientId New value for adClientId.
     **/
    public void setAdClientId(long adClientId) {
        this.adClientId = adClientId;
    }

    /**
     * Gets adOrgId
     * 
     * @return Value for adOrgId.
     **/
    public long getAdOrgId() {
        return adOrgId;
    }

    /**
     * Sets adOrgId
     * 
     * @param adOrgId New value for adOrgId.
     **/
    public void setAdOrgId(long adOrgId) {
        this.adOrgId = adOrgId;
    }

    /**
     * Gets isactive
     * 
     * @return Value for isactive.
     **/
    public String getIsactive() {
        return isactive;
    }

    /**
     * Sets isactive
     * 
     * @param isactive New value for isactive.
     **/
    public void setIsactive(String isactive) {
        this.isactive = isactive;
    }

    /**
     * Gets created
     * 
     * @return Value for created.
     **/
    public Date getCreated() {
        return created;
    }

    /**
     * Sets created
     * 
     * @param created New value for created.
     **/
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * Gets createdby
     * 
     * @return Value for createdby.
     **/
    public long getCreatedby() {
        return createdby;
    }

    /**
     * Sets createdby
     * 
     * @param createdby New value for createdby.
     **/
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }

    /**
     * Gets updated
     * 
     * @return Value for updated.
     **/
    public Date getUpdated() {
        return updated;
    }

    /**
     * Sets updated
     * 
     * @param updated New value for updated.
     **/
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * Gets updatedby
     * 
     * @return Value for updatedby.
     **/
    public long getUpdatedby() {
        return updatedby;
    }

    /**
     * Sets updatedby
     * 
     * @param updatedby New value for updatedby.
     **/
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }

    /**
     * Gets name
     * 
     * @return Value for name.
     **/
    public String getName() {
        return name;
    }

    /**
     * Sets name
     * 
     * @param name New value for name.
     **/
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets description
     * 
     * @return Value for description.
     **/
    public String getDescription() {
        return description;
    }

    /**
     * Sets description
     * 
     * @param description New value for description.
     **/
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Gets ismandatory
     * 
     * @return Value for ismandatory.
     **/
    public String getIsmandatory() {
        return ismandatory;
    }

    /**
     * Sets ismandatory
     * 
     * @param ismandatory New value for ismandatory.
     **/
    public void setIsmandatory(String ismandatory) {
        this.ismandatory = ismandatory;
    }

    /**
     * Gets isinstanceattribute
     * 
     * @return Value for isinstanceattribute.
     **/
    public String getIsinstanceattribute() {
        return isinstanceattribute;
    }

    /**
     * Sets isinstanceattribute
     * 
     * @param isinstanceattribute New value for isinstanceattribute.
     **/
    public void setIsinstanceattribute(String isinstanceattribute) {
        this.isinstanceattribute = isinstanceattribute;
    }

    /**
     * Gets mAttributesearchId
     * 
     * @return Value for mAttributesearchId.
     **/
    public Long getMAttributesearchId() {
        return mAttributesearchId;
    }

    /**
     * Sets mAttributesearchId
     * 
     * @param mAttributesearchId New value for mAttributesearchId.
     **/
    public void setMAttributesearchId(Long mAttributesearchId) {
        this.mAttributesearchId = mAttributesearchId;
    }

    /**
     * Gets attributevaluetype
     * 
     * @return Value for attributevaluetype.
     **/
    public String getAttributevaluetype() {
        return attributevaluetype;
    }

    /**
     * Sets attributevaluetype
     * 
     * @param attributevaluetype New value for attributevaluetype.
     **/
    public void setAttributevaluetype(String attributevaluetype) {
        this.attributevaluetype = attributevaluetype;
    }

    /**
     * Gets prefix
     * 
     * @return Value for prefix.
     **/
    public String getPrefix() {
        return prefix;
    }

    /**
     * Sets prefix
     * 
     * @param prefix New value for prefix.
     **/
    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }

    /**
     * Gets suffix
     * 
     * @return Value for suffix.
     **/
    public String getSuffix() {
        return suffix;
    }

    /**
     * Sets suffix
     * 
     * @param suffix New value for suffix.
     **/
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof MAttribute))
            return false;
        
        MAttribute that = (MAttribute)o;

        if (adClientId != that.adClientId)
            return false;
        

        if (adOrgId != that.adOrgId)
            return false;
        

        if (isactive != null ? !isactive.equals(that.isactive) : that.isactive != null)
            return false;
        

        if (created != null ? !created.equals(that.created) : that.created != null)
            return false;
        

        if (createdby != that.createdby)
            return false;
        

        if (updated != null ? !updated.equals(that.updated) : that.updated != null)
            return false;
        

        if (updatedby != that.updatedby)
            return false;
        

        if (name != null ? !name.equals(that.name) : that.name != null)
            return false;
        

        if (description != null ? !description.equals(that.description) : that.description != null)
            return false;
        

        if (ismandatory != null ? !ismandatory.equals(that.ismandatory) : that.ismandatory != null)
            return false;
        

        if (isinstanceattribute != null ? !isinstanceattribute.equals(that.isinstanceattribute) : that.isinstanceattribute != null)
            return false;
        

        if (mAttributesearchId != null ? !mAttributesearchId.equals(that.mAttributesearchId) : that.mAttributesearchId != null)
            return false;
        

        if (attributevaluetype != null ? !attributevaluetype.equals(that.attributevaluetype) : that.attributevaluetype != null)
            return false;
        

        if (prefix != null ? !prefix.equals(that.prefix) : that.prefix != null)
            return false;
        

        if (suffix != null ? !suffix.equals(that.suffix) : that.suffix != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = (int)(adClientId ^ (adClientId >>> 32));

        res = 31 * res + (int)(adOrgId ^ (adOrgId >>> 32));

        res = 31 * res + (isactive != null ? isactive.hashCode() : 0);

        res = 31 * res + (created != null ? created.hashCode() : 0);

        res = 31 * res + (int)(createdby ^ (createdby >>> 32));

        res = 31 * res + (updated != null ? updated.hashCode() : 0);

        res = 31 * res + (int)(updatedby ^ (updatedby >>> 32));

        res = 31 * res + (name != null ? name.hashCode() : 0);

        res = 31 * res + (description != null ? description.hashCode() : 0);

        res = 31 * res + (ismandatory != null ? ismandatory.hashCode() : 0);

        res = 31 * res + (isinstanceattribute != null ? isinstanceattribute.hashCode() : 0);

        res = 31 * res + (mAttributesearchId != null ? mAttributesearchId.hashCode() : 0);

        res = 31 * res + (attributevaluetype != null ? attributevaluetype.hashCode() : 0);

        res = 31 * res + (prefix != null ? prefix.hashCode() : 0);

        res = 31 * res + (suffix != null ? suffix.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "MAttribute [" + 
            "adClientId=" + adClientId + ", " + 
            "adOrgId=" + adOrgId + ", " + 
            "isactive=" + isactive + ", " + 
            "created=" + created + ", " + 
            "createdby=" + createdby + ", " + 
            "updated=" + updated + ", " + 
            "updatedby=" + updatedby + ", " + 
            "name=" + name + ", " + 
            "description=" + description + ", " + 
            "ismandatory=" + ismandatory + ", " + 
            "isinstanceattribute=" + isinstanceattribute + ", " + 
            "mAttributesearchId=" + mAttributesearchId + ", " + 
            "attributevaluetype=" + attributevaluetype + ", " + 
            "prefix=" + prefix + ", " + 
            "suffix=" + suffix +
        "]";
    }
}