package com.wanasis.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;

/**
 * MInout definition.
 * 
 * This file was generated by Ignite Web Console (11/21/2019, 08:54)
 **/
public class MInout implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for adClientId. */
    private long adClientId;

    /** Value for adOrgId. */
    private long adOrgId;

    /** Value for isactive. */
    private String isactive;

    /** Value for created. */
    private Date created;

    /** Value for createdby. */
    private long createdby;

    /** Value for updated. */
    private Date updated;

    /** Value for updatedby. */
    private long updatedby;

    /** Value for issotrx. */
    private String issotrx;

    /** Value for documentno. */
    private String documentno;

    /** Value for docaction. */
    private String docaction;

    /** Value for docstatus. */
    private String docstatus;

    /** Value for posted. */
    private String posted;

    /** Value for processing. */
    private String processing;

    /** Value for processed. */
    private String processed;

    /** Value for cDoctypeId. */
    private long cDoctypeId;

    /** Value for description. */
    private String description;

    /** Value for cOrderId. */
    private Long cOrderId;

    /** Value for dateordered. */
    private Date dateordered;

    /** Value for isprinted. */
    private String isprinted;

    /** Value for movementtype. */
    private String movementtype;

    /** Value for movementdate. */
    private Date movementdate;

    /** Value for dateacct. */
    private Date dateacct;

    /** Value for cBpartnerId. */
    private long cBpartnerId;

    /** Value for cBpartnerLocationId. */
    private long cBpartnerLocationId;

    /** Value for mWarehouseId. */
    private long mWarehouseId;

    /** Value for poreference. */
    private String poreference;

    /** Value for deliveryrule. */
    private String deliveryrule;

    /** Value for freightcostrule. */
    private String freightcostrule;

    /** Value for freightamt. */
    private BigDecimal freightamt;

    /** Value for deliveryviarule. */
    private String deliveryviarule;

    /** Value for mShipperId. */
    private Long mShipperId;

    /** Value for cChargeId. */
    private Long cChargeId;

    /** Value for chargeamt. */
    private BigDecimal chargeamt;

    /** Value for priorityrule. */
    private String priorityrule;

    /** Value for dateprinted. */
    private Date dateprinted;

    /** Value for cInvoiceId. */
    private Long cInvoiceId;

    /** Value for createfrom. */
    private String createfrom;

    /** Value for generateto. */
    private String generateto;

    /** Value for sendemail. */
    private String sendemail;

    /** Value for adUserId. */
    private Long adUserId;

    /** Value for salesrepId. */
    private Long salesrepId;

    /** Value for nopackages. */
    private Long nopackages;

    /** Value for pickdate. */
    private Date pickdate;

    /** Value for shipdate. */
    private Date shipdate;

    /** Value for trackingno. */
    private String trackingno;

    /** Value for adOrgtrxId. */
    private Long adOrgtrxId;

    /** Value for cProjectId. */
    private Long cProjectId;

    /** Value for cCampaignId. */
    private Long cCampaignId;

    /** Value for cActivityId. */
    private Long cActivityId;

    /** Value for user1Id. */
    private Long user1Id;

    /** Value for user2Id. */
    private Long user2Id;

    /** Value for datereceived. */
    private Date datereceived;

    /** Value for isintransit. */
    private String isintransit;

    /** Value for refInoutId. */
    private Long refInoutId;

    /** Value for createconfirm. */
    private String createconfirm;

    /** Value for createpackage. */
    private String createpackage;

    /** Value for isapproved. */
    private String isapproved;

    /** Value for isindispute. */
    private String isindispute;

    /** Value for zNaturetrans. */
    private String zNaturetrans;

    /** Value for zRegimetrans. */
    private String zRegimetrans;

    /** Value for matchrequirementr. */
    private String matchrequirementr;

    /** Value for volume. */
    private BigDecimal volume;

    /** Value for weight. */
    private BigDecimal weight;

    /** Value for isreturntrx. */
    private String isreturntrx;

    /** Value for xxControleurId. */
    private Long xxControleurId;

    /** Value for xxPreparateurId. */
    private Long xxPreparateurId;

    /** Value for islivqr. */
    private String islivqr;

    /** Value for xxEmbaleurId. */
    private Long xxEmbaleurId;

    /** Value for batchdocumentno. */
    private String batchdocumentno;

    /** Value for xxSachet. */
    private Long xxSachet;

    /** Value for xxBag. */
    private Long xxBag;

    /** Value for isprintapproved. */
    private String isprintapproved;

    /** Value for xxControleurChId. */
    private Long xxControleurChId;

    /** Value for xxEmbaleurChId. */
    private Long xxEmbaleurChId;

    /** Value for xxPreparateurChId. */
    private Long xxPreparateurChId;

    /** Value for xxCoCh. */
    private Long xxCoCh;

    /** Value for xxCvCh. */
    private Long xxCvCh;

    /** Value for xxSachetCh. */
    private Long xxSachetCh;

    /** Value for xxBacCh. */
    private Long xxBacCh;

    /** Value for isrectified. */
    private String isrectified;

    /** Value for isarchived. */
    private String isarchived;

    /** Value for motifRectif. */
    private String motifRectif;

    /** Value for isrectifiedafter. */
    private String isrectifiedafter;

    /** Value for poreferenceCh. */
    private String poreferenceCh;

    /** Value for mWarehouseChId. */
    private Long mWarehouseChId;

    /** Value for salesrepChId. */
    private Long salesrepChId;

    /** Value for docactionCh. */
    private String docactionCh;

    /** Value for isrectifiedafterCh. */
    private String isrectifiedafterCh;

    /** Value for isrectifiedCh. */
    private String isrectifiedCh;

    /** Value for isarchivedCh. */
    private String isarchivedCh;

    /** Value for motifRectifCh. */
    private String motifRectifCh;

    /** Value for xxIsdejaservi. */
    private String xxIsdejaservi;

    /** Value for etiquete. */
    private String etiquete;

    /** Value for iscontrolormodified. */
    private String iscontrolormodified;

    /** Value for ispreparatormodified. */
    private String ispreparatormodified;

    /** Value for mPicktableId. */
    private Long mPicktableId;

    /** Value for pickstatus. */
    private String pickstatus;

    /** Value for xxControleur2ChId. */
    private Long xxControleur2ChId;

    /** Value for iscontrolor2modified. */
    private String iscontrolor2modified;

    /** Value for modifNonDeclarer. */
    private String modifNonDeclarer;

    /** Value for generatemovement. */
    private String generatemovement;

    /** Value for xxCloseorder. */
    private String xxCloseorder;

    /** Empty constructor. **/
    public MInout() {
        // No-op.
    }

    /** Full constructor. **/
    public MInout(long adClientId,
        long adOrgId,
        String isactive,
        Date created,
        long createdby,
        Date updated,
        long updatedby,
        String issotrx,
        String documentno,
        String docaction,
        String docstatus,
        String posted,
        String processing,
        String processed,
        long cDoctypeId,
        String description,
        Long cOrderId,
        Date dateordered,
        String isprinted,
        String movementtype,
        Date movementdate,
        Date dateacct,
        long cBpartnerId,
        long cBpartnerLocationId,
        long mWarehouseId,
        String poreference,
        String deliveryrule,
        String freightcostrule,
        BigDecimal freightamt,
        String deliveryviarule,
        Long mShipperId,
        Long cChargeId,
        BigDecimal chargeamt,
        String priorityrule,
        Date dateprinted,
        Long cInvoiceId,
        String createfrom,
        String generateto,
        String sendemail,
        Long adUserId,
        Long salesrepId,
        Long nopackages,
        Date pickdate,
        Date shipdate,
        String trackingno,
        Long adOrgtrxId,
        Long cProjectId,
        Long cCampaignId,
        Long cActivityId,
        Long user1Id,
        Long user2Id,
        Date datereceived,
        String isintransit,
        Long refInoutId,
        String createconfirm,
        String createpackage,
        String isapproved,
        String isindispute,
        String zNaturetrans,
        String zRegimetrans,
        String matchrequirementr,
        BigDecimal volume,
        BigDecimal weight,
        String isreturntrx,
        Long xxControleurId,
        Long xxPreparateurId,
        String islivqr,
        Long xxEmbaleurId,
        String batchdocumentno,
        Long xxSachet,
        Long xxBag,
        String isprintapproved,
        Long xxControleurChId,
        Long xxEmbaleurChId,
        Long xxPreparateurChId,
        Long xxCoCh,
        Long xxCvCh,
        Long xxSachetCh,
        Long xxBacCh,
        String isrectified,
        String isarchived,
        String motifRectif,
        String isrectifiedafter,
        String poreferenceCh,
        Long mWarehouseChId,
        Long salesrepChId,
        String docactionCh,
        String isrectifiedafterCh,
        String isrectifiedCh,
        String isarchivedCh,
        String motifRectifCh,
        String xxIsdejaservi,
        String etiquete,
        String iscontrolormodified,
        String ispreparatormodified,
        Long mPicktableId,
        String pickstatus,
        Long xxControleur2ChId,
        String iscontrolor2modified,
        String modifNonDeclarer,
        String generatemovement,
        String xxCloseorder) {
        this.adClientId = adClientId;
        this.adOrgId = adOrgId;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.issotrx = issotrx;
        this.documentno = documentno;
        this.docaction = docaction;
        this.docstatus = docstatus;
        this.posted = posted;
        this.processing = processing;
        this.processed = processed;
        this.cDoctypeId = cDoctypeId;
        this.description = description;
        this.cOrderId = cOrderId;
        this.dateordered = dateordered;
        this.isprinted = isprinted;
        this.movementtype = movementtype;
        this.movementdate = movementdate;
        this.dateacct = dateacct;
        this.cBpartnerId = cBpartnerId;
        this.cBpartnerLocationId = cBpartnerLocationId;
        this.mWarehouseId = mWarehouseId;
        this.poreference = poreference;
        this.deliveryrule = deliveryrule;
        this.freightcostrule = freightcostrule;
        this.freightamt = freightamt;
        this.deliveryviarule = deliveryviarule;
        this.mShipperId = mShipperId;
        this.cChargeId = cChargeId;
        this.chargeamt = chargeamt;
        this.priorityrule = priorityrule;
        this.dateprinted = dateprinted;
        this.cInvoiceId = cInvoiceId;
        this.createfrom = createfrom;
        this.generateto = generateto;
        this.sendemail = sendemail;
        this.adUserId = adUserId;
        this.salesrepId = salesrepId;
        this.nopackages = nopackages;
        this.pickdate = pickdate;
        this.shipdate = shipdate;
        this.trackingno = trackingno;
        this.adOrgtrxId = adOrgtrxId;
        this.cProjectId = cProjectId;
        this.cCampaignId = cCampaignId;
        this.cActivityId = cActivityId;
        this.user1Id = user1Id;
        this.user2Id = user2Id;
        this.datereceived = datereceived;
        this.isintransit = isintransit;
        this.refInoutId = refInoutId;
        this.createconfirm = createconfirm;
        this.createpackage = createpackage;
        this.isapproved = isapproved;
        this.isindispute = isindispute;
        this.zNaturetrans = zNaturetrans;
        this.zRegimetrans = zRegimetrans;
        this.matchrequirementr = matchrequirementr;
        this.volume = volume;
        this.weight = weight;
        this.isreturntrx = isreturntrx;
        this.xxControleurId = xxControleurId;
        this.xxPreparateurId = xxPreparateurId;
        this.islivqr = islivqr;
        this.xxEmbaleurId = xxEmbaleurId;
        this.batchdocumentno = batchdocumentno;
        this.xxSachet = xxSachet;
        this.xxBag = xxBag;
        this.isprintapproved = isprintapproved;
        this.xxControleurChId = xxControleurChId;
        this.xxEmbaleurChId = xxEmbaleurChId;
        this.xxPreparateurChId = xxPreparateurChId;
        this.xxCoCh = xxCoCh;
        this.xxCvCh = xxCvCh;
        this.xxSachetCh = xxSachetCh;
        this.xxBacCh = xxBacCh;
        this.isrectified = isrectified;
        this.isarchived = isarchived;
        this.motifRectif = motifRectif;
        this.isrectifiedafter = isrectifiedafter;
        this.poreferenceCh = poreferenceCh;
        this.mWarehouseChId = mWarehouseChId;
        this.salesrepChId = salesrepChId;
        this.docactionCh = docactionCh;
        this.isrectifiedafterCh = isrectifiedafterCh;
        this.isrectifiedCh = isrectifiedCh;
        this.isarchivedCh = isarchivedCh;
        this.motifRectifCh = motifRectifCh;
        this.xxIsdejaservi = xxIsdejaservi;
        this.etiquete = etiquete;
        this.iscontrolormodified = iscontrolormodified;
        this.ispreparatormodified = ispreparatormodified;
        this.mPicktableId = mPicktableId;
        this.pickstatus = pickstatus;
        this.xxControleur2ChId = xxControleur2ChId;
        this.iscontrolor2modified = iscontrolor2modified;
        this.modifNonDeclarer = modifNonDeclarer;
        this.generatemovement = generatemovement;
        this.xxCloseorder = xxCloseorder;
    }

    /**
     * Gets adClientId
     * 
     * @return Value for adClientId.
     **/
    public long getAdClientId() {
        return adClientId;
    }

    /**
     * Sets adClientId
     * 
     * @param adClientId New value for adClientId.
     **/
    public void setAdClientId(long adClientId) {
        this.adClientId = adClientId;
    }

    /**
     * Gets adOrgId
     * 
     * @return Value for adOrgId.
     **/
    public long getAdOrgId() {
        return adOrgId;
    }

    /**
     * Sets adOrgId
     * 
     * @param adOrgId New value for adOrgId.
     **/
    public void setAdOrgId(long adOrgId) {
        this.adOrgId = adOrgId;
    }

    /**
     * Gets isactive
     * 
     * @return Value for isactive.
     **/
    public String getIsactive() {
        return isactive;
    }

    /**
     * Sets isactive
     * 
     * @param isactive New value for isactive.
     **/
    public void setIsactive(String isactive) {
        this.isactive = isactive;
    }

    /**
     * Gets created
     * 
     * @return Value for created.
     **/
    public Date getCreated() {
        return created;
    }

    /**
     * Sets created
     * 
     * @param created New value for created.
     **/
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * Gets createdby
     * 
     * @return Value for createdby.
     **/
    public long getCreatedby() {
        return createdby;
    }

    /**
     * Sets createdby
     * 
     * @param createdby New value for createdby.
     **/
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }

    /**
     * Gets updated
     * 
     * @return Value for updated.
     **/
    public Date getUpdated() {
        return updated;
    }

    /**
     * Sets updated
     * 
     * @param updated New value for updated.
     **/
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * Gets updatedby
     * 
     * @return Value for updatedby.
     **/
    public long getUpdatedby() {
        return updatedby;
    }

    /**
     * Sets updatedby
     * 
     * @param updatedby New value for updatedby.
     **/
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }

    /**
     * Gets issotrx
     * 
     * @return Value for issotrx.
     **/
    public String getIssotrx() {
        return issotrx;
    }

    /**
     * Sets issotrx
     * 
     * @param issotrx New value for issotrx.
     **/
    public void setIssotrx(String issotrx) {
        this.issotrx = issotrx;
    }

    /**
     * Gets documentno
     * 
     * @return Value for documentno.
     **/
    public String getDocumentno() {
        return documentno;
    }

    /**
     * Sets documentno
     * 
     * @param documentno New value for documentno.
     **/
    public void setDocumentno(String documentno) {
        this.documentno = documentno;
    }

    /**
     * Gets docaction
     * 
     * @return Value for docaction.
     **/
    public String getDocaction() {
        return docaction;
    }

    /**
     * Sets docaction
     * 
     * @param docaction New value for docaction.
     **/
    public void setDocaction(String docaction) {
        this.docaction = docaction;
    }

    /**
     * Gets docstatus
     * 
     * @return Value for docstatus.
     **/
    public String getDocstatus() {
        return docstatus;
    }

    /**
     * Sets docstatus
     * 
     * @param docstatus New value for docstatus.
     **/
    public void setDocstatus(String docstatus) {
        this.docstatus = docstatus;
    }

    /**
     * Gets posted
     * 
     * @return Value for posted.
     **/
    public String getPosted() {
        return posted;
    }

    /**
     * Sets posted
     * 
     * @param posted New value for posted.
     **/
    public void setPosted(String posted) {
        this.posted = posted;
    }

    /**
     * Gets processing
     * 
     * @return Value for processing.
     **/
    public String getProcessing() {
        return processing;
    }

    /**
     * Sets processing
     * 
     * @param processing New value for processing.
     **/
    public void setProcessing(String processing) {
        this.processing = processing;
    }

    /**
     * Gets processed
     * 
     * @return Value for processed.
     **/
    public String getProcessed() {
        return processed;
    }

    /**
     * Sets processed
     * 
     * @param processed New value for processed.
     **/
    public void setProcessed(String processed) {
        this.processed = processed;
    }

    /**
     * Gets cDoctypeId
     * 
     * @return Value for cDoctypeId.
     **/
    public long getCDoctypeId() {
        return cDoctypeId;
    }

    /**
     * Sets cDoctypeId
     * 
     * @param cDoctypeId New value for cDoctypeId.
     **/
    public void setCDoctypeId(long cDoctypeId) {
        this.cDoctypeId = cDoctypeId;
    }

    /**
     * Gets description
     * 
     * @return Value for description.
     **/
    public String getDescription() {
        return description;
    }

    /**
     * Sets description
     * 
     * @param description New value for description.
     **/
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Gets cOrderId
     * 
     * @return Value for cOrderId.
     **/
    public Long getCOrderId() {
        return cOrderId;
    }

    /**
     * Sets cOrderId
     * 
     * @param cOrderId New value for cOrderId.
     **/
    public void setCOrderId(Long cOrderId) {
        this.cOrderId = cOrderId;
    }

    /**
     * Gets dateordered
     * 
     * @return Value for dateordered.
     **/
    public Date getDateordered() {
        return dateordered;
    }

    /**
     * Sets dateordered
     * 
     * @param dateordered New value for dateordered.
     **/
    public void setDateordered(Date dateordered) {
        this.dateordered = dateordered;
    }

    /**
     * Gets isprinted
     * 
     * @return Value for isprinted.
     **/
    public String getIsprinted() {
        return isprinted;
    }

    /**
     * Sets isprinted
     * 
     * @param isprinted New value for isprinted.
     **/
    public void setIsprinted(String isprinted) {
        this.isprinted = isprinted;
    }

    /**
     * Gets movementtype
     * 
     * @return Value for movementtype.
     **/
    public String getMovementtype() {
        return movementtype;
    }

    /**
     * Sets movementtype
     * 
     * @param movementtype New value for movementtype.
     **/
    public void setMovementtype(String movementtype) {
        this.movementtype = movementtype;
    }

    /**
     * Gets movementdate
     * 
     * @return Value for movementdate.
     **/
    public Date getMovementdate() {
        return movementdate;
    }

    /**
     * Sets movementdate
     * 
     * @param movementdate New value for movementdate.
     **/
    public void setMovementdate(Date movementdate) {
        this.movementdate = movementdate;
    }

    /**
     * Gets dateacct
     * 
     * @return Value for dateacct.
     **/
    public Date getDateacct() {
        return dateacct;
    }

    /**
     * Sets dateacct
     * 
     * @param dateacct New value for dateacct.
     **/
    public void setDateacct(Date dateacct) {
        this.dateacct = dateacct;
    }

    /**
     * Gets cBpartnerId
     * 
     * @return Value for cBpartnerId.
     **/
    public long getCBpartnerId() {
        return cBpartnerId;
    }

    /**
     * Sets cBpartnerId
     * 
     * @param cBpartnerId New value for cBpartnerId.
     **/
    public void setCBpartnerId(long cBpartnerId) {
        this.cBpartnerId = cBpartnerId;
    }

    /**
     * Gets cBpartnerLocationId
     * 
     * @return Value for cBpartnerLocationId.
     **/
    public long getCBpartnerLocationId() {
        return cBpartnerLocationId;
    }

    /**
     * Sets cBpartnerLocationId
     * 
     * @param cBpartnerLocationId New value for cBpartnerLocationId.
     **/
    public void setCBpartnerLocationId(long cBpartnerLocationId) {
        this.cBpartnerLocationId = cBpartnerLocationId;
    }

    /**
     * Gets mWarehouseId
     * 
     * @return Value for mWarehouseId.
     **/
    public long getMWarehouseId() {
        return mWarehouseId;
    }

    /**
     * Sets mWarehouseId
     * 
     * @param mWarehouseId New value for mWarehouseId.
     **/
    public void setMWarehouseId(long mWarehouseId) {
        this.mWarehouseId = mWarehouseId;
    }

    /**
     * Gets poreference
     * 
     * @return Value for poreference.
     **/
    public String getPoreference() {
        return poreference;
    }

    /**
     * Sets poreference
     * 
     * @param poreference New value for poreference.
     **/
    public void setPoreference(String poreference) {
        this.poreference = poreference;
    }

    /**
     * Gets deliveryrule
     * 
     * @return Value for deliveryrule.
     **/
    public String getDeliveryrule() {
        return deliveryrule;
    }

    /**
     * Sets deliveryrule
     * 
     * @param deliveryrule New value for deliveryrule.
     **/
    public void setDeliveryrule(String deliveryrule) {
        this.deliveryrule = deliveryrule;
    }

    /**
     * Gets freightcostrule
     * 
     * @return Value for freightcostrule.
     **/
    public String getFreightcostrule() {
        return freightcostrule;
    }

    /**
     * Sets freightcostrule
     * 
     * @param freightcostrule New value for freightcostrule.
     **/
    public void setFreightcostrule(String freightcostrule) {
        this.freightcostrule = freightcostrule;
    }

    /**
     * Gets freightamt
     * 
     * @return Value for freightamt.
     **/
    public BigDecimal getFreightamt() {
        return freightamt;
    }

    /**
     * Sets freightamt
     * 
     * @param freightamt New value for freightamt.
     **/
    public void setFreightamt(BigDecimal freightamt) {
        this.freightamt = freightamt;
    }

    /**
     * Gets deliveryviarule
     * 
     * @return Value for deliveryviarule.
     **/
    public String getDeliveryviarule() {
        return deliveryviarule;
    }

    /**
     * Sets deliveryviarule
     * 
     * @param deliveryviarule New value for deliveryviarule.
     **/
    public void setDeliveryviarule(String deliveryviarule) {
        this.deliveryviarule = deliveryviarule;
    }

    /**
     * Gets mShipperId
     * 
     * @return Value for mShipperId.
     **/
    public Long getMShipperId() {
        return mShipperId;
    }

    /**
     * Sets mShipperId
     * 
     * @param mShipperId New value for mShipperId.
     **/
    public void setMShipperId(Long mShipperId) {
        this.mShipperId = mShipperId;
    }

    /**
     * Gets cChargeId
     * 
     * @return Value for cChargeId.
     **/
    public Long getCChargeId() {
        return cChargeId;
    }

    /**
     * Sets cChargeId
     * 
     * @param cChargeId New value for cChargeId.
     **/
    public void setCChargeId(Long cChargeId) {
        this.cChargeId = cChargeId;
    }

    /**
     * Gets chargeamt
     * 
     * @return Value for chargeamt.
     **/
    public BigDecimal getChargeamt() {
        return chargeamt;
    }

    /**
     * Sets chargeamt
     * 
     * @param chargeamt New value for chargeamt.
     **/
    public void setChargeamt(BigDecimal chargeamt) {
        this.chargeamt = chargeamt;
    }

    /**
     * Gets priorityrule
     * 
     * @return Value for priorityrule.
     **/
    public String getPriorityrule() {
        return priorityrule;
    }

    /**
     * Sets priorityrule
     * 
     * @param priorityrule New value for priorityrule.
     **/
    public void setPriorityrule(String priorityrule) {
        this.priorityrule = priorityrule;
    }

    /**
     * Gets dateprinted
     * 
     * @return Value for dateprinted.
     **/
    public Date getDateprinted() {
        return dateprinted;
    }

    /**
     * Sets dateprinted
     * 
     * @param dateprinted New value for dateprinted.
     **/
    public void setDateprinted(Date dateprinted) {
        this.dateprinted = dateprinted;
    }

    /**
     * Gets cInvoiceId
     * 
     * @return Value for cInvoiceId.
     **/
    public Long getCInvoiceId() {
        return cInvoiceId;
    }

    /**
     * Sets cInvoiceId
     * 
     * @param cInvoiceId New value for cInvoiceId.
     **/
    public void setCInvoiceId(Long cInvoiceId) {
        this.cInvoiceId = cInvoiceId;
    }

    /**
     * Gets createfrom
     * 
     * @return Value for createfrom.
     **/
    public String getCreatefrom() {
        return createfrom;
    }

    /**
     * Sets createfrom
     * 
     * @param createfrom New value for createfrom.
     **/
    public void setCreatefrom(String createfrom) {
        this.createfrom = createfrom;
    }

    /**
     * Gets generateto
     * 
     * @return Value for generateto.
     **/
    public String getGenerateto() {
        return generateto;
    }

    /**
     * Sets generateto
     * 
     * @param generateto New value for generateto.
     **/
    public void setGenerateto(String generateto) {
        this.generateto = generateto;
    }

    /**
     * Gets sendemail
     * 
     * @return Value for sendemail.
     **/
    public String getSendemail() {
        return sendemail;
    }

    /**
     * Sets sendemail
     * 
     * @param sendemail New value for sendemail.
     **/
    public void setSendemail(String sendemail) {
        this.sendemail = sendemail;
    }

    /**
     * Gets adUserId
     * 
     * @return Value for adUserId.
     **/
    public Long getAdUserId() {
        return adUserId;
    }

    /**
     * Sets adUserId
     * 
     * @param adUserId New value for adUserId.
     **/
    public void setAdUserId(Long adUserId) {
        this.adUserId = adUserId;
    }

    /**
     * Gets salesrepId
     * 
     * @return Value for salesrepId.
     **/
    public Long getSalesrepId() {
        return salesrepId;
    }

    /**
     * Sets salesrepId
     * 
     * @param salesrepId New value for salesrepId.
     **/
    public void setSalesrepId(Long salesrepId) {
        this.salesrepId = salesrepId;
    }

    /**
     * Gets nopackages
     * 
     * @return Value for nopackages.
     **/
    public Long getNopackages() {
        return nopackages;
    }

    /**
     * Sets nopackages
     * 
     * @param nopackages New value for nopackages.
     **/
    public void setNopackages(Long nopackages) {
        this.nopackages = nopackages;
    }

    /**
     * Gets pickdate
     * 
     * @return Value for pickdate.
     **/
    public Date getPickdate() {
        return pickdate;
    }

    /**
     * Sets pickdate
     * 
     * @param pickdate New value for pickdate.
     **/
    public void setPickdate(Date pickdate) {
        this.pickdate = pickdate;
    }

    /**
     * Gets shipdate
     * 
     * @return Value for shipdate.
     **/
    public Date getShipdate() {
        return shipdate;
    }

    /**
     * Sets shipdate
     * 
     * @param shipdate New value for shipdate.
     **/
    public void setShipdate(Date shipdate) {
        this.shipdate = shipdate;
    }

    /**
     * Gets trackingno
     * 
     * @return Value for trackingno.
     **/
    public String getTrackingno() {
        return trackingno;
    }

    /**
     * Sets trackingno
     * 
     * @param trackingno New value for trackingno.
     **/
    public void setTrackingno(String trackingno) {
        this.trackingno = trackingno;
    }

    /**
     * Gets adOrgtrxId
     * 
     * @return Value for adOrgtrxId.
     **/
    public Long getAdOrgtrxId() {
        return adOrgtrxId;
    }

    /**
     * Sets adOrgtrxId
     * 
     * @param adOrgtrxId New value for adOrgtrxId.
     **/
    public void setAdOrgtrxId(Long adOrgtrxId) {
        this.adOrgtrxId = adOrgtrxId;
    }

    /**
     * Gets cProjectId
     * 
     * @return Value for cProjectId.
     **/
    public Long getCProjectId() {
        return cProjectId;
    }

    /**
     * Sets cProjectId
     * 
     * @param cProjectId New value for cProjectId.
     **/
    public void setCProjectId(Long cProjectId) {
        this.cProjectId = cProjectId;
    }

    /**
     * Gets cCampaignId
     * 
     * @return Value for cCampaignId.
     **/
    public Long getCCampaignId() {
        return cCampaignId;
    }

    /**
     * Sets cCampaignId
     * 
     * @param cCampaignId New value for cCampaignId.
     **/
    public void setCCampaignId(Long cCampaignId) {
        this.cCampaignId = cCampaignId;
    }

    /**
     * Gets cActivityId
     * 
     * @return Value for cActivityId.
     **/
    public Long getCActivityId() {
        return cActivityId;
    }

    /**
     * Sets cActivityId
     * 
     * @param cActivityId New value for cActivityId.
     **/
    public void setCActivityId(Long cActivityId) {
        this.cActivityId = cActivityId;
    }

    /**
     * Gets user1Id
     * 
     * @return Value for user1Id.
     **/
    public Long getUser1Id() {
        return user1Id;
    }

    /**
     * Sets user1Id
     * 
     * @param user1Id New value for user1Id.
     **/
    public void setUser1Id(Long user1Id) {
        this.user1Id = user1Id;
    }

    /**
     * Gets user2Id
     * 
     * @return Value for user2Id.
     **/
    public Long getUser2Id() {
        return user2Id;
    }

    /**
     * Sets user2Id
     * 
     * @param user2Id New value for user2Id.
     **/
    public void setUser2Id(Long user2Id) {
        this.user2Id = user2Id;
    }

    /**
     * Gets datereceived
     * 
     * @return Value for datereceived.
     **/
    public Date getDatereceived() {
        return datereceived;
    }

    /**
     * Sets datereceived
     * 
     * @param datereceived New value for datereceived.
     **/
    public void setDatereceived(Date datereceived) {
        this.datereceived = datereceived;
    }

    /**
     * Gets isintransit
     * 
     * @return Value for isintransit.
     **/
    public String getIsintransit() {
        return isintransit;
    }

    /**
     * Sets isintransit
     * 
     * @param isintransit New value for isintransit.
     **/
    public void setIsintransit(String isintransit) {
        this.isintransit = isintransit;
    }

    /**
     * Gets refInoutId
     * 
     * @return Value for refInoutId.
     **/
    public Long getRefInoutId() {
        return refInoutId;
    }

    /**
     * Sets refInoutId
     * 
     * @param refInoutId New value for refInoutId.
     **/
    public void setRefInoutId(Long refInoutId) {
        this.refInoutId = refInoutId;
    }

    /**
     * Gets createconfirm
     * 
     * @return Value for createconfirm.
     **/
    public String getCreateconfirm() {
        return createconfirm;
    }

    /**
     * Sets createconfirm
     * 
     * @param createconfirm New value for createconfirm.
     **/
    public void setCreateconfirm(String createconfirm) {
        this.createconfirm = createconfirm;
    }

    /**
     * Gets createpackage
     * 
     * @return Value for createpackage.
     **/
    public String getCreatepackage() {
        return createpackage;
    }

    /**
     * Sets createpackage
     * 
     * @param createpackage New value for createpackage.
     **/
    public void setCreatepackage(String createpackage) {
        this.createpackage = createpackage;
    }

    /**
     * Gets isapproved
     * 
     * @return Value for isapproved.
     **/
    public String getIsapproved() {
        return isapproved;
    }

    /**
     * Sets isapproved
     * 
     * @param isapproved New value for isapproved.
     **/
    public void setIsapproved(String isapproved) {
        this.isapproved = isapproved;
    }

    /**
     * Gets isindispute
     * 
     * @return Value for isindispute.
     **/
    public String getIsindispute() {
        return isindispute;
    }

    /**
     * Sets isindispute
     * 
     * @param isindispute New value for isindispute.
     **/
    public void setIsindispute(String isindispute) {
        this.isindispute = isindispute;
    }

    /**
     * Gets zNaturetrans
     * 
     * @return Value for zNaturetrans.
     **/
    public String getZNaturetrans() {
        return zNaturetrans;
    }

    /**
     * Sets zNaturetrans
     * 
     * @param zNaturetrans New value for zNaturetrans.
     **/
    public void setZNaturetrans(String zNaturetrans) {
        this.zNaturetrans = zNaturetrans;
    }

    /**
     * Gets zRegimetrans
     * 
     * @return Value for zRegimetrans.
     **/
    public String getZRegimetrans() {
        return zRegimetrans;
    }

    /**
     * Sets zRegimetrans
     * 
     * @param zRegimetrans New value for zRegimetrans.
     **/
    public void setZRegimetrans(String zRegimetrans) {
        this.zRegimetrans = zRegimetrans;
    }

    /**
     * Gets matchrequirementr
     * 
     * @return Value for matchrequirementr.
     **/
    public String getMatchrequirementr() {
        return matchrequirementr;
    }

    /**
     * Sets matchrequirementr
     * 
     * @param matchrequirementr New value for matchrequirementr.
     **/
    public void setMatchrequirementr(String matchrequirementr) {
        this.matchrequirementr = matchrequirementr;
    }

    /**
     * Gets volume
     * 
     * @return Value for volume.
     **/
    public BigDecimal getVolume() {
        return volume;
    }

    /**
     * Sets volume
     * 
     * @param volume New value for volume.
     **/
    public void setVolume(BigDecimal volume) {
        this.volume = volume;
    }

    /**
     * Gets weight
     * 
     * @return Value for weight.
     **/
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * Sets weight
     * 
     * @param weight New value for weight.
     **/
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * Gets isreturntrx
     * 
     * @return Value for isreturntrx.
     **/
    public String getIsreturntrx() {
        return isreturntrx;
    }

    /**
     * Sets isreturntrx
     * 
     * @param isreturntrx New value for isreturntrx.
     **/
    public void setIsreturntrx(String isreturntrx) {
        this.isreturntrx = isreturntrx;
    }

    /**
     * Gets xxControleurId
     * 
     * @return Value for xxControleurId.
     **/
    public Long getXxControleurId() {
        return xxControleurId;
    }

    /**
     * Sets xxControleurId
     * 
     * @param xxControleurId New value for xxControleurId.
     **/
    public void setXxControleurId(Long xxControleurId) {
        this.xxControleurId = xxControleurId;
    }

    /**
     * Gets xxPreparateurId
     * 
     * @return Value for xxPreparateurId.
     **/
    public Long getXxPreparateurId() {
        return xxPreparateurId;
    }

    /**
     * Sets xxPreparateurId
     * 
     * @param xxPreparateurId New value for xxPreparateurId.
     **/
    public void setXxPreparateurId(Long xxPreparateurId) {
        this.xxPreparateurId = xxPreparateurId;
    }

    /**
     * Gets islivqr
     * 
     * @return Value for islivqr.
     **/
    public String getIslivqr() {
        return islivqr;
    }

    /**
     * Sets islivqr
     * 
     * @param islivqr New value for islivqr.
     **/
    public void setIslivqr(String islivqr) {
        this.islivqr = islivqr;
    }

    /**
     * Gets xxEmbaleurId
     * 
     * @return Value for xxEmbaleurId.
     **/
    public Long getXxEmbaleurId() {
        return xxEmbaleurId;
    }

    /**
     * Sets xxEmbaleurId
     * 
     * @param xxEmbaleurId New value for xxEmbaleurId.
     **/
    public void setXxEmbaleurId(Long xxEmbaleurId) {
        this.xxEmbaleurId = xxEmbaleurId;
    }

    /**
     * Gets batchdocumentno
     * 
     * @return Value for batchdocumentno.
     **/
    public String getBatchdocumentno() {
        return batchdocumentno;
    }

    /**
     * Sets batchdocumentno
     * 
     * @param batchdocumentno New value for batchdocumentno.
     **/
    public void setBatchdocumentno(String batchdocumentno) {
        this.batchdocumentno = batchdocumentno;
    }

    /**
     * Gets xxSachet
     * 
     * @return Value for xxSachet.
     **/
    public Long getXxSachet() {
        return xxSachet;
    }

    /**
     * Sets xxSachet
     * 
     * @param xxSachet New value for xxSachet.
     **/
    public void setXxSachet(Long xxSachet) {
        this.xxSachet = xxSachet;
    }

    /**
     * Gets xxBag
     * 
     * @return Value for xxBag.
     **/
    public Long getXxBag() {
        return xxBag;
    }

    /**
     * Sets xxBag
     * 
     * @param xxBag New value for xxBag.
     **/
    public void setXxBag(Long xxBag) {
        this.xxBag = xxBag;
    }

    /**
     * Gets isprintapproved
     * 
     * @return Value for isprintapproved.
     **/
    public String getIsprintapproved() {
        return isprintapproved;
    }

    /**
     * Sets isprintapproved
     * 
     * @param isprintapproved New value for isprintapproved.
     **/
    public void setIsprintapproved(String isprintapproved) {
        this.isprintapproved = isprintapproved;
    }

    /**
     * Gets xxControleurChId
     * 
     * @return Value for xxControleurChId.
     **/
    public Long getXxControleurChId() {
        return xxControleurChId;
    }

    /**
     * Sets xxControleurChId
     * 
     * @param xxControleurChId New value for xxControleurChId.
     **/
    public void setXxControleurChId(Long xxControleurChId) {
        this.xxControleurChId = xxControleurChId;
    }

    /**
     * Gets xxEmbaleurChId
     * 
     * @return Value for xxEmbaleurChId.
     **/
    public Long getXxEmbaleurChId() {
        return xxEmbaleurChId;
    }

    /**
     * Sets xxEmbaleurChId
     * 
     * @param xxEmbaleurChId New value for xxEmbaleurChId.
     **/
    public void setXxEmbaleurChId(Long xxEmbaleurChId) {
        this.xxEmbaleurChId = xxEmbaleurChId;
    }

    /**
     * Gets xxPreparateurChId
     * 
     * @return Value for xxPreparateurChId.
     **/
    public Long getXxPreparateurChId() {
        return xxPreparateurChId;
    }

    /**
     * Sets xxPreparateurChId
     * 
     * @param xxPreparateurChId New value for xxPreparateurChId.
     **/
    public void setXxPreparateurChId(Long xxPreparateurChId) {
        this.xxPreparateurChId = xxPreparateurChId;
    }

    /**
     * Gets xxCoCh
     * 
     * @return Value for xxCoCh.
     **/
    public Long getXxCoCh() {
        return xxCoCh;
    }

    /**
     * Sets xxCoCh
     * 
     * @param xxCoCh New value for xxCoCh.
     **/
    public void setXxCoCh(Long xxCoCh) {
        this.xxCoCh = xxCoCh;
    }

    /**
     * Gets xxCvCh
     * 
     * @return Value for xxCvCh.
     **/
    public Long getXxCvCh() {
        return xxCvCh;
    }

    /**
     * Sets xxCvCh
     * 
     * @param xxCvCh New value for xxCvCh.
     **/
    public void setXxCvCh(Long xxCvCh) {
        this.xxCvCh = xxCvCh;
    }

    /**
     * Gets xxSachetCh
     * 
     * @return Value for xxSachetCh.
     **/
    public Long getXxSachetCh() {
        return xxSachetCh;
    }

    /**
     * Sets xxSachetCh
     * 
     * @param xxSachetCh New value for xxSachetCh.
     **/
    public void setXxSachetCh(Long xxSachetCh) {
        this.xxSachetCh = xxSachetCh;
    }

    /**
     * Gets xxBacCh
     * 
     * @return Value for xxBacCh.
     **/
    public Long getXxBacCh() {
        return xxBacCh;
    }

    /**
     * Sets xxBacCh
     * 
     * @param xxBacCh New value for xxBacCh.
     **/
    public void setXxBacCh(Long xxBacCh) {
        this.xxBacCh = xxBacCh;
    }

    /**
     * Gets isrectified
     * 
     * @return Value for isrectified.
     **/
    public String getIsrectified() {
        return isrectified;
    }

    /**
     * Sets isrectified
     * 
     * @param isrectified New value for isrectified.
     **/
    public void setIsrectified(String isrectified) {
        this.isrectified = isrectified;
    }

    /**
     * Gets isarchived
     * 
     * @return Value for isarchived.
     **/
    public String getIsarchived() {
        return isarchived;
    }

    /**
     * Sets isarchived
     * 
     * @param isarchived New value for isarchived.
     **/
    public void setIsarchived(String isarchived) {
        this.isarchived = isarchived;
    }

    /**
     * Gets motifRectif
     * 
     * @return Value for motifRectif.
     **/
    public String getMotifRectif() {
        return motifRectif;
    }

    /**
     * Sets motifRectif
     * 
     * @param motifRectif New value for motifRectif.
     **/
    public void setMotifRectif(String motifRectif) {
        this.motifRectif = motifRectif;
    }

    /**
     * Gets isrectifiedafter
     * 
     * @return Value for isrectifiedafter.
     **/
    public String getIsrectifiedafter() {
        return isrectifiedafter;
    }

    /**
     * Sets isrectifiedafter
     * 
     * @param isrectifiedafter New value for isrectifiedafter.
     **/
    public void setIsrectifiedafter(String isrectifiedafter) {
        this.isrectifiedafter = isrectifiedafter;
    }

    /**
     * Gets poreferenceCh
     * 
     * @return Value for poreferenceCh.
     **/
    public String getPoreferenceCh() {
        return poreferenceCh;
    }

    /**
     * Sets poreferenceCh
     * 
     * @param poreferenceCh New value for poreferenceCh.
     **/
    public void setPoreferenceCh(String poreferenceCh) {
        this.poreferenceCh = poreferenceCh;
    }

    /**
     * Gets mWarehouseChId
     * 
     * @return Value for mWarehouseChId.
     **/
    public Long getMWarehouseChId() {
        return mWarehouseChId;
    }

    /**
     * Sets mWarehouseChId
     * 
     * @param mWarehouseChId New value for mWarehouseChId.
     **/
    public void setMWarehouseChId(Long mWarehouseChId) {
        this.mWarehouseChId = mWarehouseChId;
    }

    /**
     * Gets salesrepChId
     * 
     * @return Value for salesrepChId.
     **/
    public Long getSalesrepChId() {
        return salesrepChId;
    }

    /**
     * Sets salesrepChId
     * 
     * @param salesrepChId New value for salesrepChId.
     **/
    public void setSalesrepChId(Long salesrepChId) {
        this.salesrepChId = salesrepChId;
    }

    /**
     * Gets docactionCh
     * 
     * @return Value for docactionCh.
     **/
    public String getDocactionCh() {
        return docactionCh;
    }

    /**
     * Sets docactionCh
     * 
     * @param docactionCh New value for docactionCh.
     **/
    public void setDocactionCh(String docactionCh) {
        this.docactionCh = docactionCh;
    }

    /**
     * Gets isrectifiedafterCh
     * 
     * @return Value for isrectifiedafterCh.
     **/
    public String getIsrectifiedafterCh() {
        return isrectifiedafterCh;
    }

    /**
     * Sets isrectifiedafterCh
     * 
     * @param isrectifiedafterCh New value for isrectifiedafterCh.
     **/
    public void setIsrectifiedafterCh(String isrectifiedafterCh) {
        this.isrectifiedafterCh = isrectifiedafterCh;
    }

    /**
     * Gets isrectifiedCh
     * 
     * @return Value for isrectifiedCh.
     **/
    public String getIsrectifiedCh() {
        return isrectifiedCh;
    }

    /**
     * Sets isrectifiedCh
     * 
     * @param isrectifiedCh New value for isrectifiedCh.
     **/
    public void setIsrectifiedCh(String isrectifiedCh) {
        this.isrectifiedCh = isrectifiedCh;
    }

    /**
     * Gets isarchivedCh
     * 
     * @return Value for isarchivedCh.
     **/
    public String getIsarchivedCh() {
        return isarchivedCh;
    }

    /**
     * Sets isarchivedCh
     * 
     * @param isarchivedCh New value for isarchivedCh.
     **/
    public void setIsarchivedCh(String isarchivedCh) {
        this.isarchivedCh = isarchivedCh;
    }

    /**
     * Gets motifRectifCh
     * 
     * @return Value for motifRectifCh.
     **/
    public String getMotifRectifCh() {
        return motifRectifCh;
    }

    /**
     * Sets motifRectifCh
     * 
     * @param motifRectifCh New value for motifRectifCh.
     **/
    public void setMotifRectifCh(String motifRectifCh) {
        this.motifRectifCh = motifRectifCh;
    }

    /**
     * Gets xxIsdejaservi
     * 
     * @return Value for xxIsdejaservi.
     **/
    public String getXxIsdejaservi() {
        return xxIsdejaservi;
    }

    /**
     * Sets xxIsdejaservi
     * 
     * @param xxIsdejaservi New value for xxIsdejaservi.
     **/
    public void setXxIsdejaservi(String xxIsdejaservi) {
        this.xxIsdejaservi = xxIsdejaservi;
    }

    /**
     * Gets etiquete
     * 
     * @return Value for etiquete.
     **/
    public String getEtiquete() {
        return etiquete;
    }

    /**
     * Sets etiquete
     * 
     * @param etiquete New value for etiquete.
     **/
    public void setEtiquete(String etiquete) {
        this.etiquete = etiquete;
    }

    /**
     * Gets iscontrolormodified
     * 
     * @return Value for iscontrolormodified.
     **/
    public String getIscontrolormodified() {
        return iscontrolormodified;
    }

    /**
     * Sets iscontrolormodified
     * 
     * @param iscontrolormodified New value for iscontrolormodified.
     **/
    public void setIscontrolormodified(String iscontrolormodified) {
        this.iscontrolormodified = iscontrolormodified;
    }

    /**
     * Gets ispreparatormodified
     * 
     * @return Value for ispreparatormodified.
     **/
    public String getIspreparatormodified() {
        return ispreparatormodified;
    }

    /**
     * Sets ispreparatormodified
     * 
     * @param ispreparatormodified New value for ispreparatormodified.
     **/
    public void setIspreparatormodified(String ispreparatormodified) {
        this.ispreparatormodified = ispreparatormodified;
    }

    /**
     * Gets mPicktableId
     * 
     * @return Value for mPicktableId.
     **/
    public Long getMPicktableId() {
        return mPicktableId;
    }

    /**
     * Sets mPicktableId
     * 
     * @param mPicktableId New value for mPicktableId.
     **/
    public void setMPicktableId(Long mPicktableId) {
        this.mPicktableId = mPicktableId;
    }

    /**
     * Gets pickstatus
     * 
     * @return Value for pickstatus.
     **/
    public String getPickstatus() {
        return pickstatus;
    }

    /**
     * Sets pickstatus
     * 
     * @param pickstatus New value for pickstatus.
     **/
    public void setPickstatus(String pickstatus) {
        this.pickstatus = pickstatus;
    }

    /**
     * Gets xxControleur2ChId
     * 
     * @return Value for xxControleur2ChId.
     **/
    public Long getXxControleur2ChId() {
        return xxControleur2ChId;
    }

    /**
     * Sets xxControleur2ChId
     * 
     * @param xxControleur2ChId New value for xxControleur2ChId.
     **/
    public void setXxControleur2ChId(Long xxControleur2ChId) {
        this.xxControleur2ChId = xxControleur2ChId;
    }

    /**
     * Gets iscontrolor2modified
     * 
     * @return Value for iscontrolor2modified.
     **/
    public String getIscontrolor2modified() {
        return iscontrolor2modified;
    }

    /**
     * Sets iscontrolor2modified
     * 
     * @param iscontrolor2modified New value for iscontrolor2modified.
     **/
    public void setIscontrolor2modified(String iscontrolor2modified) {
        this.iscontrolor2modified = iscontrolor2modified;
    }

    /**
     * Gets modifNonDeclarer
     * 
     * @return Value for modifNonDeclarer.
     **/
    public String getModifNonDeclarer() {
        return modifNonDeclarer;
    }

    /**
     * Sets modifNonDeclarer
     * 
     * @param modifNonDeclarer New value for modifNonDeclarer.
     **/
    public void setModifNonDeclarer(String modifNonDeclarer) {
        this.modifNonDeclarer = modifNonDeclarer;
    }

    /**
     * Gets generatemovement
     * 
     * @return Value for generatemovement.
     **/
    public String getGeneratemovement() {
        return generatemovement;
    }

    /**
     * Sets generatemovement
     * 
     * @param generatemovement New value for generatemovement.
     **/
    public void setGeneratemovement(String generatemovement) {
        this.generatemovement = generatemovement;
    }

    /**
     * Gets xxCloseorder
     * 
     * @return Value for xxCloseorder.
     **/
    public String getXxCloseorder() {
        return xxCloseorder;
    }

    /**
     * Sets xxCloseorder
     * 
     * @param xxCloseorder New value for xxCloseorder.
     **/
    public void setXxCloseorder(String xxCloseorder) {
        this.xxCloseorder = xxCloseorder;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof MInout))
            return false;
        
        MInout that = (MInout)o;

        if (adClientId != that.adClientId)
            return false;
        

        if (adOrgId != that.adOrgId)
            return false;
        

        if (isactive != null ? !isactive.equals(that.isactive) : that.isactive != null)
            return false;
        

        if (created != null ? !created.equals(that.created) : that.created != null)
            return false;
        

        if (createdby != that.createdby)
            return false;
        

        if (updated != null ? !updated.equals(that.updated) : that.updated != null)
            return false;
        

        if (updatedby != that.updatedby)
            return false;
        

        if (issotrx != null ? !issotrx.equals(that.issotrx) : that.issotrx != null)
            return false;
        

        if (documentno != null ? !documentno.equals(that.documentno) : that.documentno != null)
            return false;
        

        if (docaction != null ? !docaction.equals(that.docaction) : that.docaction != null)
            return false;
        

        if (docstatus != null ? !docstatus.equals(that.docstatus) : that.docstatus != null)
            return false;
        

        if (posted != null ? !posted.equals(that.posted) : that.posted != null)
            return false;
        

        if (processing != null ? !processing.equals(that.processing) : that.processing != null)
            return false;
        

        if (processed != null ? !processed.equals(that.processed) : that.processed != null)
            return false;
        

        if (cDoctypeId != that.cDoctypeId)
            return false;
        

        if (description != null ? !description.equals(that.description) : that.description != null)
            return false;
        

        if (cOrderId != null ? !cOrderId.equals(that.cOrderId) : that.cOrderId != null)
            return false;
        

        if (dateordered != null ? !dateordered.equals(that.dateordered) : that.dateordered != null)
            return false;
        

        if (isprinted != null ? !isprinted.equals(that.isprinted) : that.isprinted != null)
            return false;
        

        if (movementtype != null ? !movementtype.equals(that.movementtype) : that.movementtype != null)
            return false;
        

        if (movementdate != null ? !movementdate.equals(that.movementdate) : that.movementdate != null)
            return false;
        

        if (dateacct != null ? !dateacct.equals(that.dateacct) : that.dateacct != null)
            return false;
        

        if (cBpartnerId != that.cBpartnerId)
            return false;
        

        if (cBpartnerLocationId != that.cBpartnerLocationId)
            return false;
        

        if (mWarehouseId != that.mWarehouseId)
            return false;
        

        if (poreference != null ? !poreference.equals(that.poreference) : that.poreference != null)
            return false;
        

        if (deliveryrule != null ? !deliveryrule.equals(that.deliveryrule) : that.deliveryrule != null)
            return false;
        

        if (freightcostrule != null ? !freightcostrule.equals(that.freightcostrule) : that.freightcostrule != null)
            return false;
        

        if (freightamt != null ? !freightamt.equals(that.freightamt) : that.freightamt != null)
            return false;
        

        if (deliveryviarule != null ? !deliveryviarule.equals(that.deliveryviarule) : that.deliveryviarule != null)
            return false;
        

        if (mShipperId != null ? !mShipperId.equals(that.mShipperId) : that.mShipperId != null)
            return false;
        

        if (cChargeId != null ? !cChargeId.equals(that.cChargeId) : that.cChargeId != null)
            return false;
        

        if (chargeamt != null ? !chargeamt.equals(that.chargeamt) : that.chargeamt != null)
            return false;
        

        if (priorityrule != null ? !priorityrule.equals(that.priorityrule) : that.priorityrule != null)
            return false;
        

        if (dateprinted != null ? !dateprinted.equals(that.dateprinted) : that.dateprinted != null)
            return false;
        

        if (cInvoiceId != null ? !cInvoiceId.equals(that.cInvoiceId) : that.cInvoiceId != null)
            return false;
        

        if (createfrom != null ? !createfrom.equals(that.createfrom) : that.createfrom != null)
            return false;
        

        if (generateto != null ? !generateto.equals(that.generateto) : that.generateto != null)
            return false;
        

        if (sendemail != null ? !sendemail.equals(that.sendemail) : that.sendemail != null)
            return false;
        

        if (adUserId != null ? !adUserId.equals(that.adUserId) : that.adUserId != null)
            return false;
        

        if (salesrepId != null ? !salesrepId.equals(that.salesrepId) : that.salesrepId != null)
            return false;
        

        if (nopackages != null ? !nopackages.equals(that.nopackages) : that.nopackages != null)
            return false;
        

        if (pickdate != null ? !pickdate.equals(that.pickdate) : that.pickdate != null)
            return false;
        

        if (shipdate != null ? !shipdate.equals(that.shipdate) : that.shipdate != null)
            return false;
        

        if (trackingno != null ? !trackingno.equals(that.trackingno) : that.trackingno != null)
            return false;
        

        if (adOrgtrxId != null ? !adOrgtrxId.equals(that.adOrgtrxId) : that.adOrgtrxId != null)
            return false;
        

        if (cProjectId != null ? !cProjectId.equals(that.cProjectId) : that.cProjectId != null)
            return false;
        

        if (cCampaignId != null ? !cCampaignId.equals(that.cCampaignId) : that.cCampaignId != null)
            return false;
        

        if (cActivityId != null ? !cActivityId.equals(that.cActivityId) : that.cActivityId != null)
            return false;
        

        if (user1Id != null ? !user1Id.equals(that.user1Id) : that.user1Id != null)
            return false;
        

        if (user2Id != null ? !user2Id.equals(that.user2Id) : that.user2Id != null)
            return false;
        

        if (datereceived != null ? !datereceived.equals(that.datereceived) : that.datereceived != null)
            return false;
        

        if (isintransit != null ? !isintransit.equals(that.isintransit) : that.isintransit != null)
            return false;
        

        if (refInoutId != null ? !refInoutId.equals(that.refInoutId) : that.refInoutId != null)
            return false;
        

        if (createconfirm != null ? !createconfirm.equals(that.createconfirm) : that.createconfirm != null)
            return false;
        

        if (createpackage != null ? !createpackage.equals(that.createpackage) : that.createpackage != null)
            return false;
        

        if (isapproved != null ? !isapproved.equals(that.isapproved) : that.isapproved != null)
            return false;
        

        if (isindispute != null ? !isindispute.equals(that.isindispute) : that.isindispute != null)
            return false;
        

        if (zNaturetrans != null ? !zNaturetrans.equals(that.zNaturetrans) : that.zNaturetrans != null)
            return false;
        

        if (zRegimetrans != null ? !zRegimetrans.equals(that.zRegimetrans) : that.zRegimetrans != null)
            return false;
        

        if (matchrequirementr != null ? !matchrequirementr.equals(that.matchrequirementr) : that.matchrequirementr != null)
            return false;
        

        if (volume != null ? !volume.equals(that.volume) : that.volume != null)
            return false;
        

        if (weight != null ? !weight.equals(that.weight) : that.weight != null)
            return false;
        

        if (isreturntrx != null ? !isreturntrx.equals(that.isreturntrx) : that.isreturntrx != null)
            return false;
        

        if (xxControleurId != null ? !xxControleurId.equals(that.xxControleurId) : that.xxControleurId != null)
            return false;
        

        if (xxPreparateurId != null ? !xxPreparateurId.equals(that.xxPreparateurId) : that.xxPreparateurId != null)
            return false;
        

        if (islivqr != null ? !islivqr.equals(that.islivqr) : that.islivqr != null)
            return false;
        

        if (xxEmbaleurId != null ? !xxEmbaleurId.equals(that.xxEmbaleurId) : that.xxEmbaleurId != null)
            return false;
        

        if (batchdocumentno != null ? !batchdocumentno.equals(that.batchdocumentno) : that.batchdocumentno != null)
            return false;
        

        if (xxSachet != null ? !xxSachet.equals(that.xxSachet) : that.xxSachet != null)
            return false;
        

        if (xxBag != null ? !xxBag.equals(that.xxBag) : that.xxBag != null)
            return false;
        

        if (isprintapproved != null ? !isprintapproved.equals(that.isprintapproved) : that.isprintapproved != null)
            return false;
        

        if (xxControleurChId != null ? !xxControleurChId.equals(that.xxControleurChId) : that.xxControleurChId != null)
            return false;
        

        if (xxEmbaleurChId != null ? !xxEmbaleurChId.equals(that.xxEmbaleurChId) : that.xxEmbaleurChId != null)
            return false;
        

        if (xxPreparateurChId != null ? !xxPreparateurChId.equals(that.xxPreparateurChId) : that.xxPreparateurChId != null)
            return false;
        

        if (xxCoCh != null ? !xxCoCh.equals(that.xxCoCh) : that.xxCoCh != null)
            return false;
        

        if (xxCvCh != null ? !xxCvCh.equals(that.xxCvCh) : that.xxCvCh != null)
            return false;
        

        if (xxSachetCh != null ? !xxSachetCh.equals(that.xxSachetCh) : that.xxSachetCh != null)
            return false;
        

        if (xxBacCh != null ? !xxBacCh.equals(that.xxBacCh) : that.xxBacCh != null)
            return false;
        

        if (isrectified != null ? !isrectified.equals(that.isrectified) : that.isrectified != null)
            return false;
        

        if (isarchived != null ? !isarchived.equals(that.isarchived) : that.isarchived != null)
            return false;
        

        if (motifRectif != null ? !motifRectif.equals(that.motifRectif) : that.motifRectif != null)
            return false;
        

        if (isrectifiedafter != null ? !isrectifiedafter.equals(that.isrectifiedafter) : that.isrectifiedafter != null)
            return false;
        

        if (poreferenceCh != null ? !poreferenceCh.equals(that.poreferenceCh) : that.poreferenceCh != null)
            return false;
        

        if (mWarehouseChId != null ? !mWarehouseChId.equals(that.mWarehouseChId) : that.mWarehouseChId != null)
            return false;
        

        if (salesrepChId != null ? !salesrepChId.equals(that.salesrepChId) : that.salesrepChId != null)
            return false;
        

        if (docactionCh != null ? !docactionCh.equals(that.docactionCh) : that.docactionCh != null)
            return false;
        

        if (isrectifiedafterCh != null ? !isrectifiedafterCh.equals(that.isrectifiedafterCh) : that.isrectifiedafterCh != null)
            return false;
        

        if (isrectifiedCh != null ? !isrectifiedCh.equals(that.isrectifiedCh) : that.isrectifiedCh != null)
            return false;
        

        if (isarchivedCh != null ? !isarchivedCh.equals(that.isarchivedCh) : that.isarchivedCh != null)
            return false;
        

        if (motifRectifCh != null ? !motifRectifCh.equals(that.motifRectifCh) : that.motifRectifCh != null)
            return false;
        

        if (xxIsdejaservi != null ? !xxIsdejaservi.equals(that.xxIsdejaservi) : that.xxIsdejaservi != null)
            return false;
        

        if (etiquete != null ? !etiquete.equals(that.etiquete) : that.etiquete != null)
            return false;
        

        if (iscontrolormodified != null ? !iscontrolormodified.equals(that.iscontrolormodified) : that.iscontrolormodified != null)
            return false;
        

        if (ispreparatormodified != null ? !ispreparatormodified.equals(that.ispreparatormodified) : that.ispreparatormodified != null)
            return false;
        

        if (mPicktableId != null ? !mPicktableId.equals(that.mPicktableId) : that.mPicktableId != null)
            return false;
        

        if (pickstatus != null ? !pickstatus.equals(that.pickstatus) : that.pickstatus != null)
            return false;
        

        if (xxControleur2ChId != null ? !xxControleur2ChId.equals(that.xxControleur2ChId) : that.xxControleur2ChId != null)
            return false;
        

        if (iscontrolor2modified != null ? !iscontrolor2modified.equals(that.iscontrolor2modified) : that.iscontrolor2modified != null)
            return false;
        

        if (modifNonDeclarer != null ? !modifNonDeclarer.equals(that.modifNonDeclarer) : that.modifNonDeclarer != null)
            return false;
        

        if (generatemovement != null ? !generatemovement.equals(that.generatemovement) : that.generatemovement != null)
            return false;
        

        if (xxCloseorder != null ? !xxCloseorder.equals(that.xxCloseorder) : that.xxCloseorder != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = (int)(adClientId ^ (adClientId >>> 32));

        res = 31 * res + (int)(adOrgId ^ (adOrgId >>> 32));

        res = 31 * res + (isactive != null ? isactive.hashCode() : 0);

        res = 31 * res + (created != null ? created.hashCode() : 0);

        res = 31 * res + (int)(createdby ^ (createdby >>> 32));

        res = 31 * res + (updated != null ? updated.hashCode() : 0);

        res = 31 * res + (int)(updatedby ^ (updatedby >>> 32));

        res = 31 * res + (issotrx != null ? issotrx.hashCode() : 0);

        res = 31 * res + (documentno != null ? documentno.hashCode() : 0);

        res = 31 * res + (docaction != null ? docaction.hashCode() : 0);

        res = 31 * res + (docstatus != null ? docstatus.hashCode() : 0);

        res = 31 * res + (posted != null ? posted.hashCode() : 0);

        res = 31 * res + (processing != null ? processing.hashCode() : 0);

        res = 31 * res + (processed != null ? processed.hashCode() : 0);

        res = 31 * res + (int)(cDoctypeId ^ (cDoctypeId >>> 32));

        res = 31 * res + (description != null ? description.hashCode() : 0);

        res = 31 * res + (cOrderId != null ? cOrderId.hashCode() : 0);

        res = 31 * res + (dateordered != null ? dateordered.hashCode() : 0);

        res = 31 * res + (isprinted != null ? isprinted.hashCode() : 0);

        res = 31 * res + (movementtype != null ? movementtype.hashCode() : 0);

        res = 31 * res + (movementdate != null ? movementdate.hashCode() : 0);

        res = 31 * res + (dateacct != null ? dateacct.hashCode() : 0);

        res = 31 * res + (int)(cBpartnerId ^ (cBpartnerId >>> 32));

        res = 31 * res + (int)(cBpartnerLocationId ^ (cBpartnerLocationId >>> 32));

        res = 31 * res + (int)(mWarehouseId ^ (mWarehouseId >>> 32));

        res = 31 * res + (poreference != null ? poreference.hashCode() : 0);

        res = 31 * res + (deliveryrule != null ? deliveryrule.hashCode() : 0);

        res = 31 * res + (freightcostrule != null ? freightcostrule.hashCode() : 0);

        res = 31 * res + (freightamt != null ? freightamt.hashCode() : 0);

        res = 31 * res + (deliveryviarule != null ? deliveryviarule.hashCode() : 0);

        res = 31 * res + (mShipperId != null ? mShipperId.hashCode() : 0);

        res = 31 * res + (cChargeId != null ? cChargeId.hashCode() : 0);

        res = 31 * res + (chargeamt != null ? chargeamt.hashCode() : 0);

        res = 31 * res + (priorityrule != null ? priorityrule.hashCode() : 0);

        res = 31 * res + (dateprinted != null ? dateprinted.hashCode() : 0);

        res = 31 * res + (cInvoiceId != null ? cInvoiceId.hashCode() : 0);

        res = 31 * res + (createfrom != null ? createfrom.hashCode() : 0);

        res = 31 * res + (generateto != null ? generateto.hashCode() : 0);

        res = 31 * res + (sendemail != null ? sendemail.hashCode() : 0);

        res = 31 * res + (adUserId != null ? adUserId.hashCode() : 0);

        res = 31 * res + (salesrepId != null ? salesrepId.hashCode() : 0);

        res = 31 * res + (nopackages != null ? nopackages.hashCode() : 0);

        res = 31 * res + (pickdate != null ? pickdate.hashCode() : 0);

        res = 31 * res + (shipdate != null ? shipdate.hashCode() : 0);

        res = 31 * res + (trackingno != null ? trackingno.hashCode() : 0);

        res = 31 * res + (adOrgtrxId != null ? adOrgtrxId.hashCode() : 0);

        res = 31 * res + (cProjectId != null ? cProjectId.hashCode() : 0);

        res = 31 * res + (cCampaignId != null ? cCampaignId.hashCode() : 0);

        res = 31 * res + (cActivityId != null ? cActivityId.hashCode() : 0);

        res = 31 * res + (user1Id != null ? user1Id.hashCode() : 0);

        res = 31 * res + (user2Id != null ? user2Id.hashCode() : 0);

        res = 31 * res + (datereceived != null ? datereceived.hashCode() : 0);

        res = 31 * res + (isintransit != null ? isintransit.hashCode() : 0);

        res = 31 * res + (refInoutId != null ? refInoutId.hashCode() : 0);

        res = 31 * res + (createconfirm != null ? createconfirm.hashCode() : 0);

        res = 31 * res + (createpackage != null ? createpackage.hashCode() : 0);

        res = 31 * res + (isapproved != null ? isapproved.hashCode() : 0);

        res = 31 * res + (isindispute != null ? isindispute.hashCode() : 0);

        res = 31 * res + (zNaturetrans != null ? zNaturetrans.hashCode() : 0);

        res = 31 * res + (zRegimetrans != null ? zRegimetrans.hashCode() : 0);

        res = 31 * res + (matchrequirementr != null ? matchrequirementr.hashCode() : 0);

        res = 31 * res + (volume != null ? volume.hashCode() : 0);

        res = 31 * res + (weight != null ? weight.hashCode() : 0);

        res = 31 * res + (isreturntrx != null ? isreturntrx.hashCode() : 0);

        res = 31 * res + (xxControleurId != null ? xxControleurId.hashCode() : 0);

        res = 31 * res + (xxPreparateurId != null ? xxPreparateurId.hashCode() : 0);

        res = 31 * res + (islivqr != null ? islivqr.hashCode() : 0);

        res = 31 * res + (xxEmbaleurId != null ? xxEmbaleurId.hashCode() : 0);

        res = 31 * res + (batchdocumentno != null ? batchdocumentno.hashCode() : 0);

        res = 31 * res + (xxSachet != null ? xxSachet.hashCode() : 0);

        res = 31 * res + (xxBag != null ? xxBag.hashCode() : 0);

        res = 31 * res + (isprintapproved != null ? isprintapproved.hashCode() : 0);

        res = 31 * res + (xxControleurChId != null ? xxControleurChId.hashCode() : 0);

        res = 31 * res + (xxEmbaleurChId != null ? xxEmbaleurChId.hashCode() : 0);

        res = 31 * res + (xxPreparateurChId != null ? xxPreparateurChId.hashCode() : 0);

        res = 31 * res + (xxCoCh != null ? xxCoCh.hashCode() : 0);

        res = 31 * res + (xxCvCh != null ? xxCvCh.hashCode() : 0);

        res = 31 * res + (xxSachetCh != null ? xxSachetCh.hashCode() : 0);

        res = 31 * res + (xxBacCh != null ? xxBacCh.hashCode() : 0);

        res = 31 * res + (isrectified != null ? isrectified.hashCode() : 0);

        res = 31 * res + (isarchived != null ? isarchived.hashCode() : 0);

        res = 31 * res + (motifRectif != null ? motifRectif.hashCode() : 0);

        res = 31 * res + (isrectifiedafter != null ? isrectifiedafter.hashCode() : 0);

        res = 31 * res + (poreferenceCh != null ? poreferenceCh.hashCode() : 0);

        res = 31 * res + (mWarehouseChId != null ? mWarehouseChId.hashCode() : 0);

        res = 31 * res + (salesrepChId != null ? salesrepChId.hashCode() : 0);

        res = 31 * res + (docactionCh != null ? docactionCh.hashCode() : 0);

        res = 31 * res + (isrectifiedafterCh != null ? isrectifiedafterCh.hashCode() : 0);

        res = 31 * res + (isrectifiedCh != null ? isrectifiedCh.hashCode() : 0);

        res = 31 * res + (isarchivedCh != null ? isarchivedCh.hashCode() : 0);

        res = 31 * res + (motifRectifCh != null ? motifRectifCh.hashCode() : 0);

        res = 31 * res + (xxIsdejaservi != null ? xxIsdejaservi.hashCode() : 0);

        res = 31 * res + (etiquete != null ? etiquete.hashCode() : 0);

        res = 31 * res + (iscontrolormodified != null ? iscontrolormodified.hashCode() : 0);

        res = 31 * res + (ispreparatormodified != null ? ispreparatormodified.hashCode() : 0);

        res = 31 * res + (mPicktableId != null ? mPicktableId.hashCode() : 0);

        res = 31 * res + (pickstatus != null ? pickstatus.hashCode() : 0);

        res = 31 * res + (xxControleur2ChId != null ? xxControleur2ChId.hashCode() : 0);

        res = 31 * res + (iscontrolor2modified != null ? iscontrolor2modified.hashCode() : 0);

        res = 31 * res + (modifNonDeclarer != null ? modifNonDeclarer.hashCode() : 0);

        res = 31 * res + (generatemovement != null ? generatemovement.hashCode() : 0);

        res = 31 * res + (xxCloseorder != null ? xxCloseorder.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "MInout [" + 
            "adClientId=" + adClientId + ", " + 
            "adOrgId=" + adOrgId + ", " + 
            "isactive=" + isactive + ", " + 
            "created=" + created + ", " + 
            "createdby=" + createdby + ", " + 
            "updated=" + updated + ", " + 
            "updatedby=" + updatedby + ", " + 
            "issotrx=" + issotrx + ", " + 
            "documentno=" + documentno + ", " + 
            "docaction=" + docaction + ", " + 
            "docstatus=" + docstatus + ", " + 
            "posted=" + posted + ", " + 
            "processing=" + processing + ", " + 
            "processed=" + processed + ", " + 
            "cDoctypeId=" + cDoctypeId + ", " + 
            "description=" + description + ", " + 
            "cOrderId=" + cOrderId + ", " + 
            "dateordered=" + dateordered + ", " + 
            "isprinted=" + isprinted + ", " + 
            "movementtype=" + movementtype + ", " + 
            "movementdate=" + movementdate + ", " + 
            "dateacct=" + dateacct + ", " + 
            "cBpartnerId=" + cBpartnerId + ", " + 
            "cBpartnerLocationId=" + cBpartnerLocationId + ", " + 
            "mWarehouseId=" + mWarehouseId + ", " + 
            "poreference=" + poreference + ", " + 
            "deliveryrule=" + deliveryrule + ", " + 
            "freightcostrule=" + freightcostrule + ", " + 
            "freightamt=" + freightamt + ", " + 
            "deliveryviarule=" + deliveryviarule + ", " + 
            "mShipperId=" + mShipperId + ", " + 
            "cChargeId=" + cChargeId + ", " + 
            "chargeamt=" + chargeamt + ", " + 
            "priorityrule=" + priorityrule + ", " + 
            "dateprinted=" + dateprinted + ", " + 
            "cInvoiceId=" + cInvoiceId + ", " + 
            "createfrom=" + createfrom + ", " + 
            "generateto=" + generateto + ", " + 
            "sendemail=" + sendemail + ", " + 
            "adUserId=" + adUserId + ", " + 
            "salesrepId=" + salesrepId + ", " + 
            "nopackages=" + nopackages + ", " + 
            "pickdate=" + pickdate + ", " + 
            "shipdate=" + shipdate + ", " + 
            "trackingno=" + trackingno + ", " + 
            "adOrgtrxId=" + adOrgtrxId + ", " + 
            "cProjectId=" + cProjectId + ", " + 
            "cCampaignId=" + cCampaignId + ", " + 
            "cActivityId=" + cActivityId + ", " + 
            "user1Id=" + user1Id + ", " + 
            "user2Id=" + user2Id + ", " + 
            "datereceived=" + datereceived + ", " + 
            "isintransit=" + isintransit + ", " + 
            "refInoutId=" + refInoutId + ", " + 
            "createconfirm=" + createconfirm + ", " + 
            "createpackage=" + createpackage + ", " + 
            "isapproved=" + isapproved + ", " + 
            "isindispute=" + isindispute + ", " + 
            "zNaturetrans=" + zNaturetrans + ", " + 
            "zRegimetrans=" + zRegimetrans + ", " + 
            "matchrequirementr=" + matchrequirementr + ", " + 
            "volume=" + volume + ", " + 
            "weight=" + weight + ", " + 
            "isreturntrx=" + isreturntrx + ", " + 
            "xxControleurId=" + xxControleurId + ", " + 
            "xxPreparateurId=" + xxPreparateurId + ", " + 
            "islivqr=" + islivqr + ", " + 
            "xxEmbaleurId=" + xxEmbaleurId + ", " + 
            "batchdocumentno=" + batchdocumentno + ", " + 
            "xxSachet=" + xxSachet + ", " + 
            "xxBag=" + xxBag + ", " + 
            "isprintapproved=" + isprintapproved + ", " + 
            "xxControleurChId=" + xxControleurChId + ", " + 
            "xxEmbaleurChId=" + xxEmbaleurChId + ", " + 
            "xxPreparateurChId=" + xxPreparateurChId + ", " + 
            "xxCoCh=" + xxCoCh + ", " + 
            "xxCvCh=" + xxCvCh + ", " + 
            "xxSachetCh=" + xxSachetCh + ", " + 
            "xxBacCh=" + xxBacCh + ", " + 
            "isrectified=" + isrectified + ", " + 
            "isarchived=" + isarchived + ", " + 
            "motifRectif=" + motifRectif + ", " + 
            "isrectifiedafter=" + isrectifiedafter + ", " + 
            "poreferenceCh=" + poreferenceCh + ", " + 
            "mWarehouseChId=" + mWarehouseChId + ", " + 
            "salesrepChId=" + salesrepChId + ", " + 
            "docactionCh=" + docactionCh + ", " + 
            "isrectifiedafterCh=" + isrectifiedafterCh + ", " + 
            "isrectifiedCh=" + isrectifiedCh + ", " + 
            "isarchivedCh=" + isarchivedCh + ", " + 
            "motifRectifCh=" + motifRectifCh + ", " + 
            "xxIsdejaservi=" + xxIsdejaservi + ", " + 
            "etiquete=" + etiquete + ", " + 
            "iscontrolormodified=" + iscontrolormodified + ", " + 
            "ispreparatormodified=" + ispreparatormodified + ", " + 
            "mPicktableId=" + mPicktableId + ", " + 
            "pickstatus=" + pickstatus + ", " + 
            "xxControleur2ChId=" + xxControleur2ChId + ", " + 
            "iscontrolor2modified=" + iscontrolor2modified + ", " + 
            "modifNonDeclarer=" + modifNonDeclarer + ", " + 
            "generatemovement=" + generatemovement + ", " + 
            "xxCloseorder=" + xxCloseorder +
        "]";
    }
}