package com.wanasis.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;

/**
 * MInoutline definition.
 * 
 * This file was generated by Ignite Web Console (11/21/2019, 08:54)
 **/
public class MInoutline implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for adClientId. */
    private long adClientId;

    /** Value for adOrgId. */
    private long adOrgId;

    /** Value for isactive. */
    private String isactive;

    /** Value for created. */
    private Date created;

    /** Value for createdby. */
    private long createdby;

    /** Value for updated. */
    private Date updated;

    /** Value for updatedby. */
    private long updatedby;

    /** Value for line. */
    private long line;

    /** Value for description. */
    private String description;

    /** Value for mInoutId. */
    private long mInoutId;

    /** Value for cOrderlineId. */
    private Long cOrderlineId;

    /** Value for mLocatorId. */
    private Long mLocatorId;

    /** Value for mProductId. */
    private Long mProductId;

    /** Value for cUomId. */
    private long cUomId;

    /** Value for movementqty. */
    private BigDecimal movementqty;

    /** Value for isinvoiced. */
    private String isinvoiced;

    /** Value for mAttributesetinstanceId. */
    private Long mAttributesetinstanceId;

    /** Value for isdescription. */
    private String isdescription;

    /** Value for confirmedqty. */
    private BigDecimal confirmedqty;

    /** Value for pickedqty. */
    private BigDecimal pickedqty;

    /** Value for scrappedqty. */
    private BigDecimal scrappedqty;

    /** Value for targetqty. */
    private BigDecimal targetqty;

    /** Value for refInoutlineId. */
    private Long refInoutlineId;

    /** Value for processed. */
    private String processed;

    /** Value for qtyentered. */
    private BigDecimal qtyentered;

    /** Value for cChargeId. */
    private Long cChargeId;

    /** Value for cProjectId. */
    private Long cProjectId;

    /** Value for adOrgtrxId. */
    private Long adOrgtrxId;

    /** Value for cActivityId. */
    private Long cActivityId;

    /** Value for cCampaignId. */
    private Long cCampaignId;

    /** Value for cProjectphaseId. */
    private Long cProjectphaseId;

    /** Value for cProjecttaskId. */
    private Long cProjecttaskId;

    /** Value for user1Id. */
    private Long user1Id;

    /** Value for user2Id. */
    private Long user2Id;

    /** Value for linedocstatus. */
    private String linedocstatus;

    /** Value for qtyallocated. */
    private BigDecimal qtyallocated;

    /** Value for xxContientug. */
    private String xxContientug;

    /** Value for xxLignegratuite. */
    private String xxLignegratuite;

    /** Value for xxLocatorsourceId. */
    private Long xxLocatorsourceId;

    /** Value for ismovemented. */
    private String ismovemented;

    /** Value for rCategoryId. */
    private Long rCategoryId;

    /** Value for prixvente. */
    private BigDecimal prixvente;

    /** Value for prixrevient. */
    private BigDecimal prixrevient;

    /** Value for createdfrominv. */
    private String createdfrominv;

    /** Value for mMovementlineId. */
    private Long mMovementlineId;

    /** Value for mInoutgrouplineId. */
    private Long mInoutgrouplineId;

    /** Value for origQtyentered. */
    private BigDecimal origQtyentered;

    /** Empty constructor. **/
    public MInoutline() {
        // No-op.
    }

    /** Full constructor. **/
    public MInoutline(long adClientId,
        long adOrgId,
        String isactive,
        Date created,
        long createdby,
        Date updated,
        long updatedby,
        long line,
        String description,
        long mInoutId,
        Long cOrderlineId,
        Long mLocatorId,
        Long mProductId,
        long cUomId,
        BigDecimal movementqty,
        String isinvoiced,
        Long mAttributesetinstanceId,
        String isdescription,
        BigDecimal confirmedqty,
        BigDecimal pickedqty,
        BigDecimal scrappedqty,
        BigDecimal targetqty,
        Long refInoutlineId,
        String processed,
        BigDecimal qtyentered,
        Long cChargeId,
        Long cProjectId,
        Long adOrgtrxId,
        Long cActivityId,
        Long cCampaignId,
        Long cProjectphaseId,
        Long cProjecttaskId,
        Long user1Id,
        Long user2Id,
        String linedocstatus,
        BigDecimal qtyallocated,
        String xxContientug,
        String xxLignegratuite,
        Long xxLocatorsourceId,
        String ismovemented,
        Long rCategoryId,
        BigDecimal prixvente,
        BigDecimal prixrevient,
        String createdfrominv,
        Long mMovementlineId,
        Long mInoutgrouplineId,
        BigDecimal origQtyentered) {
        this.adClientId = adClientId;
        this.adOrgId = adOrgId;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.line = line;
        this.description = description;
        this.mInoutId = mInoutId;
        this.cOrderlineId = cOrderlineId;
        this.mLocatorId = mLocatorId;
        this.mProductId = mProductId;
        this.cUomId = cUomId;
        this.movementqty = movementqty;
        this.isinvoiced = isinvoiced;
        this.mAttributesetinstanceId = mAttributesetinstanceId;
        this.isdescription = isdescription;
        this.confirmedqty = confirmedqty;
        this.pickedqty = pickedqty;
        this.scrappedqty = scrappedqty;
        this.targetqty = targetqty;
        this.refInoutlineId = refInoutlineId;
        this.processed = processed;
        this.qtyentered = qtyentered;
        this.cChargeId = cChargeId;
        this.cProjectId = cProjectId;
        this.adOrgtrxId = adOrgtrxId;
        this.cActivityId = cActivityId;
        this.cCampaignId = cCampaignId;
        this.cProjectphaseId = cProjectphaseId;
        this.cProjecttaskId = cProjecttaskId;
        this.user1Id = user1Id;
        this.user2Id = user2Id;
        this.linedocstatus = linedocstatus;
        this.qtyallocated = qtyallocated;
        this.xxContientug = xxContientug;
        this.xxLignegratuite = xxLignegratuite;
        this.xxLocatorsourceId = xxLocatorsourceId;
        this.ismovemented = ismovemented;
        this.rCategoryId = rCategoryId;
        this.prixvente = prixvente;
        this.prixrevient = prixrevient;
        this.createdfrominv = createdfrominv;
        this.mMovementlineId = mMovementlineId;
        this.mInoutgrouplineId = mInoutgrouplineId;
        this.origQtyentered = origQtyentered;
    }

    /**
     * Gets adClientId
     * 
     * @return Value for adClientId.
     **/
    public long getAdClientId() {
        return adClientId;
    }

    /**
     * Sets adClientId
     * 
     * @param adClientId New value for adClientId.
     **/
    public void setAdClientId(long adClientId) {
        this.adClientId = adClientId;
    }

    /**
     * Gets adOrgId
     * 
     * @return Value for adOrgId.
     **/
    public long getAdOrgId() {
        return adOrgId;
    }

    /**
     * Sets adOrgId
     * 
     * @param adOrgId New value for adOrgId.
     **/
    public void setAdOrgId(long adOrgId) {
        this.adOrgId = adOrgId;
    }

    /**
     * Gets isactive
     * 
     * @return Value for isactive.
     **/
    public String getIsactive() {
        return isactive;
    }

    /**
     * Sets isactive
     * 
     * @param isactive New value for isactive.
     **/
    public void setIsactive(String isactive) {
        this.isactive = isactive;
    }

    /**
     * Gets created
     * 
     * @return Value for created.
     **/
    public Date getCreated() {
        return created;
    }

    /**
     * Sets created
     * 
     * @param created New value for created.
     **/
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * Gets createdby
     * 
     * @return Value for createdby.
     **/
    public long getCreatedby() {
        return createdby;
    }

    /**
     * Sets createdby
     * 
     * @param createdby New value for createdby.
     **/
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }

    /**
     * Gets updated
     * 
     * @return Value for updated.
     **/
    public Date getUpdated() {
        return updated;
    }

    /**
     * Sets updated
     * 
     * @param updated New value for updated.
     **/
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * Gets updatedby
     * 
     * @return Value for updatedby.
     **/
    public long getUpdatedby() {
        return updatedby;
    }

    /**
     * Sets updatedby
     * 
     * @param updatedby New value for updatedby.
     **/
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }

    /**
     * Gets line
     * 
     * @return Value for line.
     **/
    public long getLine() {
        return line;
    }

    /**
     * Sets line
     * 
     * @param line New value for line.
     **/
    public void setLine(long line) {
        this.line = line;
    }

    /**
     * Gets description
     * 
     * @return Value for description.
     **/
    public String getDescription() {
        return description;
    }

    /**
     * Sets description
     * 
     * @param description New value for description.
     **/
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Gets mInoutId
     * 
     * @return Value for mInoutId.
     **/
    public long getMInoutId() {
        return mInoutId;
    }

    /**
     * Sets mInoutId
     * 
     * @param mInoutId New value for mInoutId.
     **/
    public void setMInoutId(long mInoutId) {
        this.mInoutId = mInoutId;
    }

    /**
     * Gets cOrderlineId
     * 
     * @return Value for cOrderlineId.
     **/
    public Long getCOrderlineId() {
        return cOrderlineId;
    }

    /**
     * Sets cOrderlineId
     * 
     * @param cOrderlineId New value for cOrderlineId.
     **/
    public void setCOrderlineId(Long cOrderlineId) {
        this.cOrderlineId = cOrderlineId;
    }

    /**
     * Gets mLocatorId
     * 
     * @return Value for mLocatorId.
     **/
    public Long getMLocatorId() {
        return mLocatorId;
    }

    /**
     * Sets mLocatorId
     * 
     * @param mLocatorId New value for mLocatorId.
     **/
    public void setMLocatorId(Long mLocatorId) {
        this.mLocatorId = mLocatorId;
    }

    /**
     * Gets mProductId
     * 
     * @return Value for mProductId.
     **/
    public Long getMProductId() {
        return mProductId;
    }

    /**
     * Sets mProductId
     * 
     * @param mProductId New value for mProductId.
     **/
    public void setMProductId(Long mProductId) {
        this.mProductId = mProductId;
    }

    /**
     * Gets cUomId
     * 
     * @return Value for cUomId.
     **/
    public long getCUomId() {
        return cUomId;
    }

    /**
     * Sets cUomId
     * 
     * @param cUomId New value for cUomId.
     **/
    public void setCUomId(long cUomId) {
        this.cUomId = cUomId;
    }

    /**
     * Gets movementqty
     * 
     * @return Value for movementqty.
     **/
    public BigDecimal getMovementqty() {
        return movementqty;
    }

    /**
     * Sets movementqty
     * 
     * @param movementqty New value for movementqty.
     **/
    public void setMovementqty(BigDecimal movementqty) {
        this.movementqty = movementqty;
    }

    /**
     * Gets isinvoiced
     * 
     * @return Value for isinvoiced.
     **/
    public String getIsinvoiced() {
        return isinvoiced;
    }

    /**
     * Sets isinvoiced
     * 
     * @param isinvoiced New value for isinvoiced.
     **/
    public void setIsinvoiced(String isinvoiced) {
        this.isinvoiced = isinvoiced;
    }

    /**
     * Gets mAttributesetinstanceId
     * 
     * @return Value for mAttributesetinstanceId.
     **/
    public Long getMAttributesetinstanceId() {
        return mAttributesetinstanceId;
    }

    /**
     * Sets mAttributesetinstanceId
     * 
     * @param mAttributesetinstanceId New value for mAttributesetinstanceId.
     **/
    public void setMAttributesetinstanceId(Long mAttributesetinstanceId) {
        this.mAttributesetinstanceId = mAttributesetinstanceId;
    }

    /**
     * Gets isdescription
     * 
     * @return Value for isdescription.
     **/
    public String getIsdescription() {
        return isdescription;
    }

    /**
     * Sets isdescription
     * 
     * @param isdescription New value for isdescription.
     **/
    public void setIsdescription(String isdescription) {
        this.isdescription = isdescription;
    }

    /**
     * Gets confirmedqty
     * 
     * @return Value for confirmedqty.
     **/
    public BigDecimal getConfirmedqty() {
        return confirmedqty;
    }

    /**
     * Sets confirmedqty
     * 
     * @param confirmedqty New value for confirmedqty.
     **/
    public void setConfirmedqty(BigDecimal confirmedqty) {
        this.confirmedqty = confirmedqty;
    }

    /**
     * Gets pickedqty
     * 
     * @return Value for pickedqty.
     **/
    public BigDecimal getPickedqty() {
        return pickedqty;
    }

    /**
     * Sets pickedqty
     * 
     * @param pickedqty New value for pickedqty.
     **/
    public void setPickedqty(BigDecimal pickedqty) {
        this.pickedqty = pickedqty;
    }

    /**
     * Gets scrappedqty
     * 
     * @return Value for scrappedqty.
     **/
    public BigDecimal getScrappedqty() {
        return scrappedqty;
    }

    /**
     * Sets scrappedqty
     * 
     * @param scrappedqty New value for scrappedqty.
     **/
    public void setScrappedqty(BigDecimal scrappedqty) {
        this.scrappedqty = scrappedqty;
    }

    /**
     * Gets targetqty
     * 
     * @return Value for targetqty.
     **/
    public BigDecimal getTargetqty() {
        return targetqty;
    }

    /**
     * Sets targetqty
     * 
     * @param targetqty New value for targetqty.
     **/
    public void setTargetqty(BigDecimal targetqty) {
        this.targetqty = targetqty;
    }

    /**
     * Gets refInoutlineId
     * 
     * @return Value for refInoutlineId.
     **/
    public Long getRefInoutlineId() {
        return refInoutlineId;
    }

    /**
     * Sets refInoutlineId
     * 
     * @param refInoutlineId New value for refInoutlineId.
     **/
    public void setRefInoutlineId(Long refInoutlineId) {
        this.refInoutlineId = refInoutlineId;
    }

    /**
     * Gets processed
     * 
     * @return Value for processed.
     **/
    public String getProcessed() {
        return processed;
    }

    /**
     * Sets processed
     * 
     * @param processed New value for processed.
     **/
    public void setProcessed(String processed) {
        this.processed = processed;
    }

    /**
     * Gets qtyentered
     * 
     * @return Value for qtyentered.
     **/
    public BigDecimal getQtyentered() {
        return qtyentered;
    }

    /**
     * Sets qtyentered
     * 
     * @param qtyentered New value for qtyentered.
     **/
    public void setQtyentered(BigDecimal qtyentered) {
        this.qtyentered = qtyentered;
    }

    /**
     * Gets cChargeId
     * 
     * @return Value for cChargeId.
     **/
    public Long getCChargeId() {
        return cChargeId;
    }

    /**
     * Sets cChargeId
     * 
     * @param cChargeId New value for cChargeId.
     **/
    public void setCChargeId(Long cChargeId) {
        this.cChargeId = cChargeId;
    }

    /**
     * Gets cProjectId
     * 
     * @return Value for cProjectId.
     **/
    public Long getCProjectId() {
        return cProjectId;
    }

    /**
     * Sets cProjectId
     * 
     * @param cProjectId New value for cProjectId.
     **/
    public void setCProjectId(Long cProjectId) {
        this.cProjectId = cProjectId;
    }

    /**
     * Gets adOrgtrxId
     * 
     * @return Value for adOrgtrxId.
     **/
    public Long getAdOrgtrxId() {
        return adOrgtrxId;
    }

    /**
     * Sets adOrgtrxId
     * 
     * @param adOrgtrxId New value for adOrgtrxId.
     **/
    public void setAdOrgtrxId(Long adOrgtrxId) {
        this.adOrgtrxId = adOrgtrxId;
    }

    /**
     * Gets cActivityId
     * 
     * @return Value for cActivityId.
     **/
    public Long getCActivityId() {
        return cActivityId;
    }

    /**
     * Sets cActivityId
     * 
     * @param cActivityId New value for cActivityId.
     **/
    public void setCActivityId(Long cActivityId) {
        this.cActivityId = cActivityId;
    }

    /**
     * Gets cCampaignId
     * 
     * @return Value for cCampaignId.
     **/
    public Long getCCampaignId() {
        return cCampaignId;
    }

    /**
     * Sets cCampaignId
     * 
     * @param cCampaignId New value for cCampaignId.
     **/
    public void setCCampaignId(Long cCampaignId) {
        this.cCampaignId = cCampaignId;
    }

    /**
     * Gets cProjectphaseId
     * 
     * @return Value for cProjectphaseId.
     **/
    public Long getCProjectphaseId() {
        return cProjectphaseId;
    }

    /**
     * Sets cProjectphaseId
     * 
     * @param cProjectphaseId New value for cProjectphaseId.
     **/
    public void setCProjectphaseId(Long cProjectphaseId) {
        this.cProjectphaseId = cProjectphaseId;
    }

    /**
     * Gets cProjecttaskId
     * 
     * @return Value for cProjecttaskId.
     **/
    public Long getCProjecttaskId() {
        return cProjecttaskId;
    }

    /**
     * Sets cProjecttaskId
     * 
     * @param cProjecttaskId New value for cProjecttaskId.
     **/
    public void setCProjecttaskId(Long cProjecttaskId) {
        this.cProjecttaskId = cProjecttaskId;
    }

    /**
     * Gets user1Id
     * 
     * @return Value for user1Id.
     **/
    public Long getUser1Id() {
        return user1Id;
    }

    /**
     * Sets user1Id
     * 
     * @param user1Id New value for user1Id.
     **/
    public void setUser1Id(Long user1Id) {
        this.user1Id = user1Id;
    }

    /**
     * Gets user2Id
     * 
     * @return Value for user2Id.
     **/
    public Long getUser2Id() {
        return user2Id;
    }

    /**
     * Sets user2Id
     * 
     * @param user2Id New value for user2Id.
     **/
    public void setUser2Id(Long user2Id) {
        this.user2Id = user2Id;
    }

    /**
     * Gets linedocstatus
     * 
     * @return Value for linedocstatus.
     **/
    public String getLinedocstatus() {
        return linedocstatus;
    }

    /**
     * Sets linedocstatus
     * 
     * @param linedocstatus New value for linedocstatus.
     **/
    public void setLinedocstatus(String linedocstatus) {
        this.linedocstatus = linedocstatus;
    }

    /**
     * Gets qtyallocated
     * 
     * @return Value for qtyallocated.
     **/
    public BigDecimal getQtyallocated() {
        return qtyallocated;
    }

    /**
     * Sets qtyallocated
     * 
     * @param qtyallocated New value for qtyallocated.
     **/
    public void setQtyallocated(BigDecimal qtyallocated) {
        this.qtyallocated = qtyallocated;
    }

    /**
     * Gets xxContientug
     * 
     * @return Value for xxContientug.
     **/
    public String getXxContientug() {
        return xxContientug;
    }

    /**
     * Sets xxContientug
     * 
     * @param xxContientug New value for xxContientug.
     **/
    public void setXxContientug(String xxContientug) {
        this.xxContientug = xxContientug;
    }

    /**
     * Gets xxLignegratuite
     * 
     * @return Value for xxLignegratuite.
     **/
    public String getXxLignegratuite() {
        return xxLignegratuite;
    }

    /**
     * Sets xxLignegratuite
     * 
     * @param xxLignegratuite New value for xxLignegratuite.
     **/
    public void setXxLignegratuite(String xxLignegratuite) {
        this.xxLignegratuite = xxLignegratuite;
    }

    /**
     * Gets xxLocatorsourceId
     * 
     * @return Value for xxLocatorsourceId.
     **/
    public Long getXxLocatorsourceId() {
        return xxLocatorsourceId;
    }

    /**
     * Sets xxLocatorsourceId
     * 
     * @param xxLocatorsourceId New value for xxLocatorsourceId.
     **/
    public void setXxLocatorsourceId(Long xxLocatorsourceId) {
        this.xxLocatorsourceId = xxLocatorsourceId;
    }

    /**
     * Gets ismovemented
     * 
     * @return Value for ismovemented.
     **/
    public String getIsmovemented() {
        return ismovemented;
    }

    /**
     * Sets ismovemented
     * 
     * @param ismovemented New value for ismovemented.
     **/
    public void setIsmovemented(String ismovemented) {
        this.ismovemented = ismovemented;
    }

    /**
     * Gets rCategoryId
     * 
     * @return Value for rCategoryId.
     **/
    public Long getRCategoryId() {
        return rCategoryId;
    }

    /**
     * Sets rCategoryId
     * 
     * @param rCategoryId New value for rCategoryId.
     **/
    public void setRCategoryId(Long rCategoryId) {
        this.rCategoryId = rCategoryId;
    }

    /**
     * Gets prixvente
     * 
     * @return Value for prixvente.
     **/
    public BigDecimal getPrixvente() {
        return prixvente;
    }

    /**
     * Sets prixvente
     * 
     * @param prixvente New value for prixvente.
     **/
    public void setPrixvente(BigDecimal prixvente) {
        this.prixvente = prixvente;
    }

    /**
     * Gets prixrevient
     * 
     * @return Value for prixrevient.
     **/
    public BigDecimal getPrixrevient() {
        return prixrevient;
    }

    /**
     * Sets prixrevient
     * 
     * @param prixrevient New value for prixrevient.
     **/
    public void setPrixrevient(BigDecimal prixrevient) {
        this.prixrevient = prixrevient;
    }

    /**
     * Gets createdfrominv
     * 
     * @return Value for createdfrominv.
     **/
    public String getCreatedfrominv() {
        return createdfrominv;
    }

    /**
     * Sets createdfrominv
     * 
     * @param createdfrominv New value for createdfrominv.
     **/
    public void setCreatedfrominv(String createdfrominv) {
        this.createdfrominv = createdfrominv;
    }

    /**
     * Gets mMovementlineId
     * 
     * @return Value for mMovementlineId.
     **/
    public Long getMMovementlineId() {
        return mMovementlineId;
    }

    /**
     * Sets mMovementlineId
     * 
     * @param mMovementlineId New value for mMovementlineId.
     **/
    public void setMMovementlineId(Long mMovementlineId) {
        this.mMovementlineId = mMovementlineId;
    }

    /**
     * Gets mInoutgrouplineId
     * 
     * @return Value for mInoutgrouplineId.
     **/
    public Long getMInoutgrouplineId() {
        return mInoutgrouplineId;
    }

    /**
     * Sets mInoutgrouplineId
     * 
     * @param mInoutgrouplineId New value for mInoutgrouplineId.
     **/
    public void setMInoutgrouplineId(Long mInoutgrouplineId) {
        this.mInoutgrouplineId = mInoutgrouplineId;
    }

    /**
     * Gets origQtyentered
     * 
     * @return Value for origQtyentered.
     **/
    public BigDecimal getOrigQtyentered() {
        return origQtyentered;
    }

    /**
     * Sets origQtyentered
     * 
     * @param origQtyentered New value for origQtyentered.
     **/
    public void setOrigQtyentered(BigDecimal origQtyentered) {
        this.origQtyentered = origQtyentered;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof MInoutline))
            return false;
        
        MInoutline that = (MInoutline)o;

        if (adClientId != that.adClientId)
            return false;
        

        if (adOrgId != that.adOrgId)
            return false;
        

        if (isactive != null ? !isactive.equals(that.isactive) : that.isactive != null)
            return false;
        

        if (created != null ? !created.equals(that.created) : that.created != null)
            return false;
        

        if (createdby != that.createdby)
            return false;
        

        if (updated != null ? !updated.equals(that.updated) : that.updated != null)
            return false;
        

        if (updatedby != that.updatedby)
            return false;
        

        if (line != that.line)
            return false;
        

        if (description != null ? !description.equals(that.description) : that.description != null)
            return false;
        

        if (mInoutId != that.mInoutId)
            return false;
        

        if (cOrderlineId != null ? !cOrderlineId.equals(that.cOrderlineId) : that.cOrderlineId != null)
            return false;
        

        if (mLocatorId != null ? !mLocatorId.equals(that.mLocatorId) : that.mLocatorId != null)
            return false;
        

        if (mProductId != null ? !mProductId.equals(that.mProductId) : that.mProductId != null)
            return false;
        

        if (cUomId != that.cUomId)
            return false;
        

        if (movementqty != null ? !movementqty.equals(that.movementqty) : that.movementqty != null)
            return false;
        

        if (isinvoiced != null ? !isinvoiced.equals(that.isinvoiced) : that.isinvoiced != null)
            return false;
        

        if (mAttributesetinstanceId != null ? !mAttributesetinstanceId.equals(that.mAttributesetinstanceId) : that.mAttributesetinstanceId != null)
            return false;
        

        if (isdescription != null ? !isdescription.equals(that.isdescription) : that.isdescription != null)
            return false;
        

        if (confirmedqty != null ? !confirmedqty.equals(that.confirmedqty) : that.confirmedqty != null)
            return false;
        

        if (pickedqty != null ? !pickedqty.equals(that.pickedqty) : that.pickedqty != null)
            return false;
        

        if (scrappedqty != null ? !scrappedqty.equals(that.scrappedqty) : that.scrappedqty != null)
            return false;
        

        if (targetqty != null ? !targetqty.equals(that.targetqty) : that.targetqty != null)
            return false;
        

        if (refInoutlineId != null ? !refInoutlineId.equals(that.refInoutlineId) : that.refInoutlineId != null)
            return false;
        

        if (processed != null ? !processed.equals(that.processed) : that.processed != null)
            return false;
        

        if (qtyentered != null ? !qtyentered.equals(that.qtyentered) : that.qtyentered != null)
            return false;
        

        if (cChargeId != null ? !cChargeId.equals(that.cChargeId) : that.cChargeId != null)
            return false;
        

        if (cProjectId != null ? !cProjectId.equals(that.cProjectId) : that.cProjectId != null)
            return false;
        

        if (adOrgtrxId != null ? !adOrgtrxId.equals(that.adOrgtrxId) : that.adOrgtrxId != null)
            return false;
        

        if (cActivityId != null ? !cActivityId.equals(that.cActivityId) : that.cActivityId != null)
            return false;
        

        if (cCampaignId != null ? !cCampaignId.equals(that.cCampaignId) : that.cCampaignId != null)
            return false;
        

        if (cProjectphaseId != null ? !cProjectphaseId.equals(that.cProjectphaseId) : that.cProjectphaseId != null)
            return false;
        

        if (cProjecttaskId != null ? !cProjecttaskId.equals(that.cProjecttaskId) : that.cProjecttaskId != null)
            return false;
        

        if (user1Id != null ? !user1Id.equals(that.user1Id) : that.user1Id != null)
            return false;
        

        if (user2Id != null ? !user2Id.equals(that.user2Id) : that.user2Id != null)
            return false;
        

        if (linedocstatus != null ? !linedocstatus.equals(that.linedocstatus) : that.linedocstatus != null)
            return false;
        

        if (qtyallocated != null ? !qtyallocated.equals(that.qtyallocated) : that.qtyallocated != null)
            return false;
        

        if (xxContientug != null ? !xxContientug.equals(that.xxContientug) : that.xxContientug != null)
            return false;
        

        if (xxLignegratuite != null ? !xxLignegratuite.equals(that.xxLignegratuite) : that.xxLignegratuite != null)
            return false;
        

        if (xxLocatorsourceId != null ? !xxLocatorsourceId.equals(that.xxLocatorsourceId) : that.xxLocatorsourceId != null)
            return false;
        

        if (ismovemented != null ? !ismovemented.equals(that.ismovemented) : that.ismovemented != null)
            return false;
        

        if (rCategoryId != null ? !rCategoryId.equals(that.rCategoryId) : that.rCategoryId != null)
            return false;
        

        if (prixvente != null ? !prixvente.equals(that.prixvente) : that.prixvente != null)
            return false;
        

        if (prixrevient != null ? !prixrevient.equals(that.prixrevient) : that.prixrevient != null)
            return false;
        

        if (createdfrominv != null ? !createdfrominv.equals(that.createdfrominv) : that.createdfrominv != null)
            return false;
        

        if (mMovementlineId != null ? !mMovementlineId.equals(that.mMovementlineId) : that.mMovementlineId != null)
            return false;
        

        if (mInoutgrouplineId != null ? !mInoutgrouplineId.equals(that.mInoutgrouplineId) : that.mInoutgrouplineId != null)
            return false;
        

        if (origQtyentered != null ? !origQtyentered.equals(that.origQtyentered) : that.origQtyentered != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = (int)(adClientId ^ (adClientId >>> 32));

        res = 31 * res + (int)(adOrgId ^ (adOrgId >>> 32));

        res = 31 * res + (isactive != null ? isactive.hashCode() : 0);

        res = 31 * res + (created != null ? created.hashCode() : 0);

        res = 31 * res + (int)(createdby ^ (createdby >>> 32));

        res = 31 * res + (updated != null ? updated.hashCode() : 0);

        res = 31 * res + (int)(updatedby ^ (updatedby >>> 32));

        res = 31 * res + (int)(line ^ (line >>> 32));

        res = 31 * res + (description != null ? description.hashCode() : 0);

        res = 31 * res + (int)(mInoutId ^ (mInoutId >>> 32));

        res = 31 * res + (cOrderlineId != null ? cOrderlineId.hashCode() : 0);

        res = 31 * res + (mLocatorId != null ? mLocatorId.hashCode() : 0);

        res = 31 * res + (mProductId != null ? mProductId.hashCode() : 0);

        res = 31 * res + (int)(cUomId ^ (cUomId >>> 32));

        res = 31 * res + (movementqty != null ? movementqty.hashCode() : 0);

        res = 31 * res + (isinvoiced != null ? isinvoiced.hashCode() : 0);

        res = 31 * res + (mAttributesetinstanceId != null ? mAttributesetinstanceId.hashCode() : 0);

        res = 31 * res + (isdescription != null ? isdescription.hashCode() : 0);

        res = 31 * res + (confirmedqty != null ? confirmedqty.hashCode() : 0);

        res = 31 * res + (pickedqty != null ? pickedqty.hashCode() : 0);

        res = 31 * res + (scrappedqty != null ? scrappedqty.hashCode() : 0);

        res = 31 * res + (targetqty != null ? targetqty.hashCode() : 0);

        res = 31 * res + (refInoutlineId != null ? refInoutlineId.hashCode() : 0);

        res = 31 * res + (processed != null ? processed.hashCode() : 0);

        res = 31 * res + (qtyentered != null ? qtyentered.hashCode() : 0);

        res = 31 * res + (cChargeId != null ? cChargeId.hashCode() : 0);

        res = 31 * res + (cProjectId != null ? cProjectId.hashCode() : 0);

        res = 31 * res + (adOrgtrxId != null ? adOrgtrxId.hashCode() : 0);

        res = 31 * res + (cActivityId != null ? cActivityId.hashCode() : 0);

        res = 31 * res + (cCampaignId != null ? cCampaignId.hashCode() : 0);

        res = 31 * res + (cProjectphaseId != null ? cProjectphaseId.hashCode() : 0);

        res = 31 * res + (cProjecttaskId != null ? cProjecttaskId.hashCode() : 0);

        res = 31 * res + (user1Id != null ? user1Id.hashCode() : 0);

        res = 31 * res + (user2Id != null ? user2Id.hashCode() : 0);

        res = 31 * res + (linedocstatus != null ? linedocstatus.hashCode() : 0);

        res = 31 * res + (qtyallocated != null ? qtyallocated.hashCode() : 0);

        res = 31 * res + (xxContientug != null ? xxContientug.hashCode() : 0);

        res = 31 * res + (xxLignegratuite != null ? xxLignegratuite.hashCode() : 0);

        res = 31 * res + (xxLocatorsourceId != null ? xxLocatorsourceId.hashCode() : 0);

        res = 31 * res + (ismovemented != null ? ismovemented.hashCode() : 0);

        res = 31 * res + (rCategoryId != null ? rCategoryId.hashCode() : 0);

        res = 31 * res + (prixvente != null ? prixvente.hashCode() : 0);

        res = 31 * res + (prixrevient != null ? prixrevient.hashCode() : 0);

        res = 31 * res + (createdfrominv != null ? createdfrominv.hashCode() : 0);

        res = 31 * res + (mMovementlineId != null ? mMovementlineId.hashCode() : 0);

        res = 31 * res + (mInoutgrouplineId != null ? mInoutgrouplineId.hashCode() : 0);

        res = 31 * res + (origQtyentered != null ? origQtyentered.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "MInoutline [" + 
            "adClientId=" + adClientId + ", " + 
            "adOrgId=" + adOrgId + ", " + 
            "isactive=" + isactive + ", " + 
            "created=" + created + ", " + 
            "createdby=" + createdby + ", " + 
            "updated=" + updated + ", " + 
            "updatedby=" + updatedby + ", " + 
            "line=" + line + ", " + 
            "description=" + description + ", " + 
            "mInoutId=" + mInoutId + ", " + 
            "cOrderlineId=" + cOrderlineId + ", " + 
            "mLocatorId=" + mLocatorId + ", " + 
            "mProductId=" + mProductId + ", " + 
            "cUomId=" + cUomId + ", " + 
            "movementqty=" + movementqty + ", " + 
            "isinvoiced=" + isinvoiced + ", " + 
            "mAttributesetinstanceId=" + mAttributesetinstanceId + ", " + 
            "isdescription=" + isdescription + ", " + 
            "confirmedqty=" + confirmedqty + ", " + 
            "pickedqty=" + pickedqty + ", " + 
            "scrappedqty=" + scrappedqty + ", " + 
            "targetqty=" + targetqty + ", " + 
            "refInoutlineId=" + refInoutlineId + ", " + 
            "processed=" + processed + ", " + 
            "qtyentered=" + qtyentered + ", " + 
            "cChargeId=" + cChargeId + ", " + 
            "cProjectId=" + cProjectId + ", " + 
            "adOrgtrxId=" + adOrgtrxId + ", " + 
            "cActivityId=" + cActivityId + ", " + 
            "cCampaignId=" + cCampaignId + ", " + 
            "cProjectphaseId=" + cProjectphaseId + ", " + 
            "cProjecttaskId=" + cProjecttaskId + ", " + 
            "user1Id=" + user1Id + ", " + 
            "user2Id=" + user2Id + ", " + 
            "linedocstatus=" + linedocstatus + ", " + 
            "qtyallocated=" + qtyallocated + ", " + 
            "xxContientug=" + xxContientug + ", " + 
            "xxLignegratuite=" + xxLignegratuite + ", " + 
            "xxLocatorsourceId=" + xxLocatorsourceId + ", " + 
            "ismovemented=" + ismovemented + ", " + 
            "rCategoryId=" + rCategoryId + ", " + 
            "prixvente=" + prixvente + ", " + 
            "prixrevient=" + prixrevient + ", " + 
            "createdfrominv=" + createdfrominv + ", " + 
            "mMovementlineId=" + mMovementlineId + ", " + 
            "mInoutgrouplineId=" + mInoutgrouplineId + ", " + 
            "origQtyentered=" + origQtyentered +
        "]";
    }
}