package com.wanasis.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;

/**
 * MProduct definition.
 * 
 * This file was generated by Ignite Web Console (11/21/2019, 08:54)
 **/
public class MProduct implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for adClientId. */
    private long adClientId;

    /** Value for adOrgId. */
    private long adOrgId;

    /** Value for isactive. */
    private String isactive;

    /** Value for created. */
    private Date created;

    /** Value for createdby. */
    private long createdby;

    /** Value for updated. */
    private Date updated;

    /** Value for updatedby. */
    private long updatedby;

    /** Value for value. */
    private String value;

    /** Value for name. */
    private String name;

    /** Value for description. */
    private String description;

    /** Value for documentnote. */
    private String documentnote;

    /** Value for help. */
    private String help;

    /** Value for upc. */
    private String upc;

    /** Value for sku. */
    private String sku;

    /** Value for cUomId. */
    private long cUomId;

    /** Value for salesrepId. */
    private Long salesrepId;

    /** Value for issummary. */
    private String issummary;

    /** Value for isstocked. */
    private String isstocked;

    /** Value for ispurchased. */
    private String ispurchased;

    /** Value for issold. */
    private String issold;

    /** Value for isbom. */
    private String isbom;

    /** Value for isinvoiceprintdetails. */
    private String isinvoiceprintdetails;

    /** Value for ispicklistprintdetails. */
    private String ispicklistprintdetails;

    /** Value for isverified. */
    private String isverified;

    /** Value for mProductCategoryId. */
    private long mProductCategoryId;

    /** Value for classification. */
    private String classification;

    /** Value for volume. */
    private BigDecimal volume;

    /** Value for weight. */
    private BigDecimal weight;

    /** Value for shelfwidth. */
    private Long shelfwidth;

    /** Value for shelfheight. */
    private Long shelfheight;

    /** Value for shelfdepth. */
    private Long shelfdepth;

    /** Value for unitsperpallet. */
    private Long unitsperpallet;

    /** Value for cTaxcategoryId. */
    private long cTaxcategoryId;

    /** Value for sResourceId. */
    private Long sResourceId;

    /** Value for discontinued. */
    private String discontinued;

    /** Value for discontinuedby. */
    private Date discontinuedby;

    /** Value for processing. */
    private String processing;

    /** Value for sExpensetypeId. */
    private Long sExpensetypeId;

    /** Value for producttype. */
    private String producttype;

    /** Value for imageurl. */
    private String imageurl;

    /** Value for descriptionurl. */
    private String descriptionurl;

    /** Value for guaranteedays. */
    private Long guaranteedays;

    /** Value for rMailtextId. */
    private Long rMailtextId;

    /** Value for versionno. */
    private String versionno;

    /** Value for mAttributesetId. */
    private Long mAttributesetId;

    /** Value for mAttributesetinstanceId. */
    private Long mAttributesetinstanceId;

    /** Value for downloadurl. */
    private String downloadurl;

    /** Value for mFreightcategoryId. */
    private Long mFreightcategoryId;

    /** Value for mLocatorId. */
    private Long mLocatorId;

    /** Value for guaranteedaysmin. */
    private Long guaranteedaysmin;

    /** Value for iswebstorefeatured. */
    private String iswebstorefeatured;

    /** Value for isselfservice. */
    private String isselfservice;

    /** Value for cSubscriptiontypeId. */
    private Long cSubscriptiontypeId;

    /** Value for isdropship. */
    private String isdropship;

    /** Value for zlasttransactiondate. */
    private Date zlasttransactiondate;

    /** Value for isexcludeautodelivery. */
    private String isexcludeautodelivery;

    /** Value for codedouanier. */
    private String codedouanier;

    /** Value for commoditycode. */
    private String commoditycode;

    /** Value for supportunits. */
    private Long supportunits;

    /** Value for ispurchasedtoorder. */
    private String ispurchasedtoorder;

    /** Value for licenseinfo. */
    private String licenseinfo;

    /** Value for rSourceId. */
    private Long rSourceId;

    /** Value for trialphasedays. */
    private Long trialphasedays;

    /** Value for zUomfId. */
    private Long zUomfId;

    /** Value for zPriceumf. */
    private BigDecimal zPriceumf;

    /** Value for zAttributeumfId. */
    private Long zAttributeumfId;

    /** Value for xxProductclass. */
    private String xxProductclass;

    /** Value for type. */
    private String type;

    /** Value for xxMarketingcategory. */
    private String xxMarketingcategory;

    /** Value for xxRank. */
    private Long xxRank;

    /** Value for xxPricelevel. */
    private BigDecimal xxPricelevel;

    /** Value for isotc. */
    private String isotc;

    /** Value for ischronical. */
    private String ischronical;

    /** Value for isaigue. */
    private String isaigue;

    /** Value for ispromu. */
    private String ispromu;

    /** Value for ispsychotrope. */
    private String ispsychotrope;

    /** Value for isprodnationale. */
    private String isprodnationale;

    /** Value for isagreement. */
    private String isagreement;

    /** Value for iscoldchain. */
    private String iscoldchain;

    /** Value for isrefundable. */
    private String isrefundable;

    /** Value for xxDriveragreement. */
    private String xxDriveragreement;

    /** Value for xxPresentation. */
    private String xxPresentation;

    /** Value for xxLaboratoryId. */
    private Long xxLaboratoryId;

    /** Value for xxUg. */
    private BigDecimal xxUg;

    /** Value for xxClassificationId. */
    private Long xxClassificationId;

    /** Value for quantity. */
    private Long quantity;

    /** Value for xxFormattributeId. */
    private Long xxFormattributeId;

    /** Value for xxAssayId. */
    private Long xxAssayId;

    /** Value for xxFormeId. */
    private Long xxFormeId;

    /** Value for xxMaxqty. */
    private BigDecimal xxMaxqty;

    /** Value for xxDistributequota. */
    private String xxDistributequota;

    /** Value for adColorId. */
    private Long adColorId;

    /** Value for adPrintcolorId. */
    private Long adPrintcolorId;

    /** Value for colortype. */
    private String colortype;

    /** Value for red. */
    private Long red;

    /** Value for green. */
    private Long green;

    /** Value for blue. */
    private Long blue;

    /** Value for xxSalescontextId. */
    private Long xxSalescontextId;

    /** Value for xxShp. */
    private BigDecimal xxShp;

    /** Value for xxTarifRef. */
    private BigDecimal xxTarifRef;

    /** Value for cCountryId. */
    private Long cCountryId;

    /** Value for xxListeProduct. */
    private String xxListeProduct;

    /** Value for dateenregistrement. */
    private Date dateenregistrement;

    /** Value for xxConditionnementId. */
    private Long xxConditionnementId;

    /** Value for isqr. */
    private String isqr;

    /** Value for xxProductlineId. */
    private Long xxProductlineId;

    /** Value for cPaymenttermId. */
    private Long cPaymenttermId;

    /** Value for xxCreateupdatesubstitut. */
    private String xxCreateupdatesubstitut;

    /** Value for ischer. */
    private String ischer;

    /** Value for xxLastugachat. */
    private BigDecimal xxLastugachat;

    /** Value for xxStartegicalproduct. */
    private String xxStartegicalproduct;

    /** Value for xxIsquotasystem. */
    private String xxIsquotasystem;

    /** Value for xxTauxvaleur. */
    private Long xxTauxvaleur;

    /** Value for xxProduitsurcommande. */
    private String xxProduitsurcommande;

    /** Value for xxTypecommande. */
    private String xxTypecommande;

    /** Value for xxListetauxvaleurId. */
    private Long xxListetauxvaleurId;

    /** Value for xxCorrespondancecapital. */
    private String xxCorrespondancecapital;

    /** Value for xxCriticalproduct. */
    private String xxCriticalproduct;

    /** Value for xxCapitalName. */
    private String xxCapitalName;

    /** Value for xxCapitalName2. */
    private String xxCapitalName2;

    /** Value for xxUgbylot. */
    private String xxUgbylot;

    /** Value for xxSoumiapprobation. */
    private String xxSoumiapprobation;

    /** Value for xxUpdatesalesctxmap. */
    private String xxUpdatesalesctxmap;

    /** Value for xxResteQuota. */
    private Long xxResteQuota;

    /** Value for xxUpdateprodcatctxvte. */
    private String xxUpdateprodcatctxvte;

    /** Value for generatesalesctx. */
    private String generatesalesctx;

    /** Empty constructor. **/
    public MProduct() {
        // No-op.
    }

    /** Full constructor. **/
    public MProduct(long adClientId,
        long adOrgId,
        String isactive,
        Date created,
        long createdby,
        Date updated,
        long updatedby,
        String value,
        String name,
        String description,
        String documentnote,
        String help,
        String upc,
        String sku,
        long cUomId,
        Long salesrepId,
        String issummary,
        String isstocked,
        String ispurchased,
        String issold,
        String isbom,
        String isinvoiceprintdetails,
        String ispicklistprintdetails,
        String isverified,
        long mProductCategoryId,
        String classification,
        BigDecimal volume,
        BigDecimal weight,
        Long shelfwidth,
        Long shelfheight,
        Long shelfdepth,
        Long unitsperpallet,
        long cTaxcategoryId,
        Long sResourceId,
        String discontinued,
        Date discontinuedby,
        String processing,
        Long sExpensetypeId,
        String producttype,
        String imageurl,
        String descriptionurl,
        Long guaranteedays,
        Long rMailtextId,
        String versionno,
        Long mAttributesetId,
        Long mAttributesetinstanceId,
        String downloadurl,
        Long mFreightcategoryId,
        Long mLocatorId,
        Long guaranteedaysmin,
        String iswebstorefeatured,
        String isselfservice,
        Long cSubscriptiontypeId,
        String isdropship,
        Date zlasttransactiondate,
        String isexcludeautodelivery,
        String codedouanier,
        String commoditycode,
        Long supportunits,
        String ispurchasedtoorder,
        String licenseinfo,
        Long rSourceId,
        Long trialphasedays,
        Long zUomfId,
        BigDecimal zPriceumf,
        Long zAttributeumfId,
        String xxProductclass,
        String type,
        String xxMarketingcategory,
        Long xxRank,
        BigDecimal xxPricelevel,
        String isotc,
        String ischronical,
        String isaigue,
        String ispromu,
        String ispsychotrope,
        String isprodnationale,
        String isagreement,
        String iscoldchain,
        String isrefundable,
        String xxDriveragreement,
        String xxPresentation,
        Long xxLaboratoryId,
        BigDecimal xxUg,
        Long xxClassificationId,
        Long quantity,
        Long xxFormattributeId,
        Long xxAssayId,
        Long xxFormeId,
        BigDecimal xxMaxqty,
        String xxDistributequota,
        Long adColorId,
        Long adPrintcolorId,
        String colortype,
        Long red,
        Long green,
        Long blue,
        Long xxSalescontextId,
        BigDecimal xxShp,
        BigDecimal xxTarifRef,
        Long cCountryId,
        String xxListeProduct,
        Date dateenregistrement,
        Long xxConditionnementId,
        String isqr,
        Long xxProductlineId,
        Long cPaymenttermId,
        String xxCreateupdatesubstitut,
        String ischer,
        BigDecimal xxLastugachat,
        String xxStartegicalproduct,
        String xxIsquotasystem,
        Long xxTauxvaleur,
        String xxProduitsurcommande,
        String xxTypecommande,
        Long xxListetauxvaleurId,
        String xxCorrespondancecapital,
        String xxCriticalproduct,
        String xxCapitalName,
        String xxCapitalName2,
        String xxUgbylot,
        String xxSoumiapprobation,
        String xxUpdatesalesctxmap,
        Long xxResteQuota,
        String xxUpdateprodcatctxvte,
        String generatesalesctx) {
        this.adClientId = adClientId;
        this.adOrgId = adOrgId;
        this.isactive = isactive;
        this.created = created;
        this.createdby = createdby;
        this.updated = updated;
        this.updatedby = updatedby;
        this.value = value;
        this.name = name;
        this.description = description;
        this.documentnote = documentnote;
        this.help = help;
        this.upc = upc;
        this.sku = sku;
        this.cUomId = cUomId;
        this.salesrepId = salesrepId;
        this.issummary = issummary;
        this.isstocked = isstocked;
        this.ispurchased = ispurchased;
        this.issold = issold;
        this.isbom = isbom;
        this.isinvoiceprintdetails = isinvoiceprintdetails;
        this.ispicklistprintdetails = ispicklistprintdetails;
        this.isverified = isverified;
        this.mProductCategoryId = mProductCategoryId;
        this.classification = classification;
        this.volume = volume;
        this.weight = weight;
        this.shelfwidth = shelfwidth;
        this.shelfheight = shelfheight;
        this.shelfdepth = shelfdepth;
        this.unitsperpallet = unitsperpallet;
        this.cTaxcategoryId = cTaxcategoryId;
        this.sResourceId = sResourceId;
        this.discontinued = discontinued;
        this.discontinuedby = discontinuedby;
        this.processing = processing;
        this.sExpensetypeId = sExpensetypeId;
        this.producttype = producttype;
        this.imageurl = imageurl;
        this.descriptionurl = descriptionurl;
        this.guaranteedays = guaranteedays;
        this.rMailtextId = rMailtextId;
        this.versionno = versionno;
        this.mAttributesetId = mAttributesetId;
        this.mAttributesetinstanceId = mAttributesetinstanceId;
        this.downloadurl = downloadurl;
        this.mFreightcategoryId = mFreightcategoryId;
        this.mLocatorId = mLocatorId;
        this.guaranteedaysmin = guaranteedaysmin;
        this.iswebstorefeatured = iswebstorefeatured;
        this.isselfservice = isselfservice;
        this.cSubscriptiontypeId = cSubscriptiontypeId;
        this.isdropship = isdropship;
        this.zlasttransactiondate = zlasttransactiondate;
        this.isexcludeautodelivery = isexcludeautodelivery;
        this.codedouanier = codedouanier;
        this.commoditycode = commoditycode;
        this.supportunits = supportunits;
        this.ispurchasedtoorder = ispurchasedtoorder;
        this.licenseinfo = licenseinfo;
        this.rSourceId = rSourceId;
        this.trialphasedays = trialphasedays;
        this.zUomfId = zUomfId;
        this.zPriceumf = zPriceumf;
        this.zAttributeumfId = zAttributeumfId;
        this.xxProductclass = xxProductclass;
        this.type = type;
        this.xxMarketingcategory = xxMarketingcategory;
        this.xxRank = xxRank;
        this.xxPricelevel = xxPricelevel;
        this.isotc = isotc;
        this.ischronical = ischronical;
        this.isaigue = isaigue;
        this.ispromu = ispromu;
        this.ispsychotrope = ispsychotrope;
        this.isprodnationale = isprodnationale;
        this.isagreement = isagreement;
        this.iscoldchain = iscoldchain;
        this.isrefundable = isrefundable;
        this.xxDriveragreement = xxDriveragreement;
        this.xxPresentation = xxPresentation;
        this.xxLaboratoryId = xxLaboratoryId;
        this.xxUg = xxUg;
        this.xxClassificationId = xxClassificationId;
        this.quantity = quantity;
        this.xxFormattributeId = xxFormattributeId;
        this.xxAssayId = xxAssayId;
        this.xxFormeId = xxFormeId;
        this.xxMaxqty = xxMaxqty;
        this.xxDistributequota = xxDistributequota;
        this.adColorId = adColorId;
        this.adPrintcolorId = adPrintcolorId;
        this.colortype = colortype;
        this.red = red;
        this.green = green;
        this.blue = blue;
        this.xxSalescontextId = xxSalescontextId;
        this.xxShp = xxShp;
        this.xxTarifRef = xxTarifRef;
        this.cCountryId = cCountryId;
        this.xxListeProduct = xxListeProduct;
        this.dateenregistrement = dateenregistrement;
        this.xxConditionnementId = xxConditionnementId;
        this.isqr = isqr;
        this.xxProductlineId = xxProductlineId;
        this.cPaymenttermId = cPaymenttermId;
        this.xxCreateupdatesubstitut = xxCreateupdatesubstitut;
        this.ischer = ischer;
        this.xxLastugachat = xxLastugachat;
        this.xxStartegicalproduct = xxStartegicalproduct;
        this.xxIsquotasystem = xxIsquotasystem;
        this.xxTauxvaleur = xxTauxvaleur;
        this.xxProduitsurcommande = xxProduitsurcommande;
        this.xxTypecommande = xxTypecommande;
        this.xxListetauxvaleurId = xxListetauxvaleurId;
        this.xxCorrespondancecapital = xxCorrespondancecapital;
        this.xxCriticalproduct = xxCriticalproduct;
        this.xxCapitalName = xxCapitalName;
        this.xxCapitalName2 = xxCapitalName2;
        this.xxUgbylot = xxUgbylot;
        this.xxSoumiapprobation = xxSoumiapprobation;
        this.xxUpdatesalesctxmap = xxUpdatesalesctxmap;
        this.xxResteQuota = xxResteQuota;
        this.xxUpdateprodcatctxvte = xxUpdateprodcatctxvte;
        this.generatesalesctx = generatesalesctx;
    }

    /**
     * Gets adClientId
     * 
     * @return Value for adClientId.
     **/
    public long getAdClientId() {
        return adClientId;
    }

    /**
     * Sets adClientId
     * 
     * @param adClientId New value for adClientId.
     **/
    public void setAdClientId(long adClientId) {
        this.adClientId = adClientId;
    }

    /**
     * Gets adOrgId
     * 
     * @return Value for adOrgId.
     **/
    public long getAdOrgId() {
        return adOrgId;
    }

    /**
     * Sets adOrgId
     * 
     * @param adOrgId New value for adOrgId.
     **/
    public void setAdOrgId(long adOrgId) {
        this.adOrgId = adOrgId;
    }

    /**
     * Gets isactive
     * 
     * @return Value for isactive.
     **/
    public String getIsactive() {
        return isactive;
    }

    /**
     * Sets isactive
     * 
     * @param isactive New value for isactive.
     **/
    public void setIsactive(String isactive) {
        this.isactive = isactive;
    }

    /**
     * Gets created
     * 
     * @return Value for created.
     **/
    public Date getCreated() {
        return created;
    }

    /**
     * Sets created
     * 
     * @param created New value for created.
     **/
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * Gets createdby
     * 
     * @return Value for createdby.
     **/
    public long getCreatedby() {
        return createdby;
    }

    /**
     * Sets createdby
     * 
     * @param createdby New value for createdby.
     **/
    public void setCreatedby(long createdby) {
        this.createdby = createdby;
    }

    /**
     * Gets updated
     * 
     * @return Value for updated.
     **/
    public Date getUpdated() {
        return updated;
    }

    /**
     * Sets updated
     * 
     * @param updated New value for updated.
     **/
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * Gets updatedby
     * 
     * @return Value for updatedby.
     **/
    public long getUpdatedby() {
        return updatedby;
    }

    /**
     * Sets updatedby
     * 
     * @param updatedby New value for updatedby.
     **/
    public void setUpdatedby(long updatedby) {
        this.updatedby = updatedby;
    }

    /**
     * Gets value
     * 
     * @return Value for value.
     **/
    public String getValue() {
        return value;
    }

    /**
     * Sets value
     * 
     * @param value New value for value.
     **/
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets name
     * 
     * @return Value for name.
     **/
    public String getName() {
        return name;
    }

    /**
     * Sets name
     * 
     * @param name New value for name.
     **/
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets description
     * 
     * @return Value for description.
     **/
    public String getDescription() {
        return description;
    }

    /**
     * Sets description
     * 
     * @param description New value for description.
     **/
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Gets documentnote
     * 
     * @return Value for documentnote.
     **/
    public String getDocumentnote() {
        return documentnote;
    }

    /**
     * Sets documentnote
     * 
     * @param documentnote New value for documentnote.
     **/
    public void setDocumentnote(String documentnote) {
        this.documentnote = documentnote;
    }

    /**
     * Gets help
     * 
     * @return Value for help.
     **/
    public String getHelp() {
        return help;
    }

    /**
     * Sets help
     * 
     * @param help New value for help.
     **/
    public void setHelp(String help) {
        this.help = help;
    }

    /**
     * Gets upc
     * 
     * @return Value for upc.
     **/
    public String getUpc() {
        return upc;
    }

    /**
     * Sets upc
     * 
     * @param upc New value for upc.
     **/
    public void setUpc(String upc) {
        this.upc = upc;
    }

    /**
     * Gets sku
     * 
     * @return Value for sku.
     **/
    public String getSku() {
        return sku;
    }

    /**
     * Sets sku
     * 
     * @param sku New value for sku.
     **/
    public void setSku(String sku) {
        this.sku = sku;
    }

    /**
     * Gets cUomId
     * 
     * @return Value for cUomId.
     **/
    public long getCUomId() {
        return cUomId;
    }

    /**
     * Sets cUomId
     * 
     * @param cUomId New value for cUomId.
     **/
    public void setCUomId(long cUomId) {
        this.cUomId = cUomId;
    }

    /**
     * Gets salesrepId
     * 
     * @return Value for salesrepId.
     **/
    public Long getSalesrepId() {
        return salesrepId;
    }

    /**
     * Sets salesrepId
     * 
     * @param salesrepId New value for salesrepId.
     **/
    public void setSalesrepId(Long salesrepId) {
        this.salesrepId = salesrepId;
    }

    /**
     * Gets issummary
     * 
     * @return Value for issummary.
     **/
    public String getIssummary() {
        return issummary;
    }

    /**
     * Sets issummary
     * 
     * @param issummary New value for issummary.
     **/
    public void setIssummary(String issummary) {
        this.issummary = issummary;
    }

    /**
     * Gets isstocked
     * 
     * @return Value for isstocked.
     **/
    public String getIsstocked() {
        return isstocked;
    }

    /**
     * Sets isstocked
     * 
     * @param isstocked New value for isstocked.
     **/
    public void setIsstocked(String isstocked) {
        this.isstocked = isstocked;
    }

    /**
     * Gets ispurchased
     * 
     * @return Value for ispurchased.
     **/
    public String getIspurchased() {
        return ispurchased;
    }

    /**
     * Sets ispurchased
     * 
     * @param ispurchased New value for ispurchased.
     **/
    public void setIspurchased(String ispurchased) {
        this.ispurchased = ispurchased;
    }

    /**
     * Gets issold
     * 
     * @return Value for issold.
     **/
    public String getIssold() {
        return issold;
    }

    /**
     * Sets issold
     * 
     * @param issold New value for issold.
     **/
    public void setIssold(String issold) {
        this.issold = issold;
    }

    /**
     * Gets isbom
     * 
     * @return Value for isbom.
     **/
    public String getIsbom() {
        return isbom;
    }

    /**
     * Sets isbom
     * 
     * @param isbom New value for isbom.
     **/
    public void setIsbom(String isbom) {
        this.isbom = isbom;
    }

    /**
     * Gets isinvoiceprintdetails
     * 
     * @return Value for isinvoiceprintdetails.
     **/
    public String getIsinvoiceprintdetails() {
        return isinvoiceprintdetails;
    }

    /**
     * Sets isinvoiceprintdetails
     * 
     * @param isinvoiceprintdetails New value for isinvoiceprintdetails.
     **/
    public void setIsinvoiceprintdetails(String isinvoiceprintdetails) {
        this.isinvoiceprintdetails = isinvoiceprintdetails;
    }

    /**
     * Gets ispicklistprintdetails
     * 
     * @return Value for ispicklistprintdetails.
     **/
    public String getIspicklistprintdetails() {
        return ispicklistprintdetails;
    }

    /**
     * Sets ispicklistprintdetails
     * 
     * @param ispicklistprintdetails New value for ispicklistprintdetails.
     **/
    public void setIspicklistprintdetails(String ispicklistprintdetails) {
        this.ispicklistprintdetails = ispicklistprintdetails;
    }

    /**
     * Gets isverified
     * 
     * @return Value for isverified.
     **/
    public String getIsverified() {
        return isverified;
    }

    /**
     * Sets isverified
     * 
     * @param isverified New value for isverified.
     **/
    public void setIsverified(String isverified) {
        this.isverified = isverified;
    }

    /**
     * Gets mProductCategoryId
     * 
     * @return Value for mProductCategoryId.
     **/
    public long getMProductCategoryId() {
        return mProductCategoryId;
    }

    /**
     * Sets mProductCategoryId
     * 
     * @param mProductCategoryId New value for mProductCategoryId.
     **/
    public void setMProductCategoryId(long mProductCategoryId) {
        this.mProductCategoryId = mProductCategoryId;
    }

    /**
     * Gets classification
     * 
     * @return Value for classification.
     **/
    public String getClassification() {
        return classification;
    }

    /**
     * Sets classification
     * 
     * @param classification New value for classification.
     **/
    public void setClassification(String classification) {
        this.classification = classification;
    }

    /**
     * Gets volume
     * 
     * @return Value for volume.
     **/
    public BigDecimal getVolume() {
        return volume;
    }

    /**
     * Sets volume
     * 
     * @param volume New value for volume.
     **/
    public void setVolume(BigDecimal volume) {
        this.volume = volume;
    }

    /**
     * Gets weight
     * 
     * @return Value for weight.
     **/
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * Sets weight
     * 
     * @param weight New value for weight.
     **/
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * Gets shelfwidth
     * 
     * @return Value for shelfwidth.
     **/
    public Long getShelfwidth() {
        return shelfwidth;
    }

    /**
     * Sets shelfwidth
     * 
     * @param shelfwidth New value for shelfwidth.
     **/
    public void setShelfwidth(Long shelfwidth) {
        this.shelfwidth = shelfwidth;
    }

    /**
     * Gets shelfheight
     * 
     * @return Value for shelfheight.
     **/
    public Long getShelfheight() {
        return shelfheight;
    }

    /**
     * Sets shelfheight
     * 
     * @param shelfheight New value for shelfheight.
     **/
    public void setShelfheight(Long shelfheight) {
        this.shelfheight = shelfheight;
    }

    /**
     * Gets shelfdepth
     * 
     * @return Value for shelfdepth.
     **/
    public Long getShelfdepth() {
        return shelfdepth;
    }

    /**
     * Sets shelfdepth
     * 
     * @param shelfdepth New value for shelfdepth.
     **/
    public void setShelfdepth(Long shelfdepth) {
        this.shelfdepth = shelfdepth;
    }

    /**
     * Gets unitsperpallet
     * 
     * @return Value for unitsperpallet.
     **/
    public Long getUnitsperpallet() {
        return unitsperpallet;
    }

    /**
     * Sets unitsperpallet
     * 
     * @param unitsperpallet New value for unitsperpallet.
     **/
    public void setUnitsperpallet(Long unitsperpallet) {
        this.unitsperpallet = unitsperpallet;
    }

    /**
     * Gets cTaxcategoryId
     * 
     * @return Value for cTaxcategoryId.
     **/
    public long getCTaxcategoryId() {
        return cTaxcategoryId;
    }

    /**
     * Sets cTaxcategoryId
     * 
     * @param cTaxcategoryId New value for cTaxcategoryId.
     **/
    public void setCTaxcategoryId(long cTaxcategoryId) {
        this.cTaxcategoryId = cTaxcategoryId;
    }

    /**
     * Gets sResourceId
     * 
     * @return Value for sResourceId.
     **/
    public Long getSResourceId() {
        return sResourceId;
    }

    /**
     * Sets sResourceId
     * 
     * @param sResourceId New value for sResourceId.
     **/
    public void setSResourceId(Long sResourceId) {
        this.sResourceId = sResourceId;
    }

    /**
     * Gets discontinued
     * 
     * @return Value for discontinued.
     **/
    public String getDiscontinued() {
        return discontinued;
    }

    /**
     * Sets discontinued
     * 
     * @param discontinued New value for discontinued.
     **/
    public void setDiscontinued(String discontinued) {
        this.discontinued = discontinued;
    }

    /**
     * Gets discontinuedby
     * 
     * @return Value for discontinuedby.
     **/
    public Date getDiscontinuedby() {
        return discontinuedby;
    }

    /**
     * Sets discontinuedby
     * 
     * @param discontinuedby New value for discontinuedby.
     **/
    public void setDiscontinuedby(Date discontinuedby) {
        this.discontinuedby = discontinuedby;
    }

    /**
     * Gets processing
     * 
     * @return Value for processing.
     **/
    public String getProcessing() {
        return processing;
    }

    /**
     * Sets processing
     * 
     * @param processing New value for processing.
     **/
    public void setProcessing(String processing) {
        this.processing = processing;
    }

    /**
     * Gets sExpensetypeId
     * 
     * @return Value for sExpensetypeId.
     **/
    public Long getSExpensetypeId() {
        return sExpensetypeId;
    }

    /**
     * Sets sExpensetypeId
     * 
     * @param sExpensetypeId New value for sExpensetypeId.
     **/
    public void setSExpensetypeId(Long sExpensetypeId) {
        this.sExpensetypeId = sExpensetypeId;
    }

    /**
     * Gets producttype
     * 
     * @return Value for producttype.
     **/
    public String getProducttype() {
        return producttype;
    }

    /**
     * Sets producttype
     * 
     * @param producttype New value for producttype.
     **/
    public void setProducttype(String producttype) {
        this.producttype = producttype;
    }

    /**
     * Gets imageurl
     * 
     * @return Value for imageurl.
     **/
    public String getImageurl() {
        return imageurl;
    }

    /**
     * Sets imageurl
     * 
     * @param imageurl New value for imageurl.
     **/
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }

    /**
     * Gets descriptionurl
     * 
     * @return Value for descriptionurl.
     **/
    public String getDescriptionurl() {
        return descriptionurl;
    }

    /**
     * Sets descriptionurl
     * 
     * @param descriptionurl New value for descriptionurl.
     **/
    public void setDescriptionurl(String descriptionurl) {
        this.descriptionurl = descriptionurl;
    }

    /**
     * Gets guaranteedays
     * 
     * @return Value for guaranteedays.
     **/
    public Long getGuaranteedays() {
        return guaranteedays;
    }

    /**
     * Sets guaranteedays
     * 
     * @param guaranteedays New value for guaranteedays.
     **/
    public void setGuaranteedays(Long guaranteedays) {
        this.guaranteedays = guaranteedays;
    }

    /**
     * Gets rMailtextId
     * 
     * @return Value for rMailtextId.
     **/
    public Long getRMailtextId() {
        return rMailtextId;
    }

    /**
     * Sets rMailtextId
     * 
     * @param rMailtextId New value for rMailtextId.
     **/
    public void setRMailtextId(Long rMailtextId) {
        this.rMailtextId = rMailtextId;
    }

    /**
     * Gets versionno
     * 
     * @return Value for versionno.
     **/
    public String getVersionno() {
        return versionno;
    }

    /**
     * Sets versionno
     * 
     * @param versionno New value for versionno.
     **/
    public void setVersionno(String versionno) {
        this.versionno = versionno;
    }

    /**
     * Gets mAttributesetId
     * 
     * @return Value for mAttributesetId.
     **/
    public Long getMAttributesetId() {
        return mAttributesetId;
    }

    /**
     * Sets mAttributesetId
     * 
     * @param mAttributesetId New value for mAttributesetId.
     **/
    public void setMAttributesetId(Long mAttributesetId) {
        this.mAttributesetId = mAttributesetId;
    }

    /**
     * Gets mAttributesetinstanceId
     * 
     * @return Value for mAttributesetinstanceId.
     **/
    public Long getMAttributesetinstanceId() {
        return mAttributesetinstanceId;
    }

    /**
     * Sets mAttributesetinstanceId
     * 
     * @param mAttributesetinstanceId New value for mAttributesetinstanceId.
     **/
    public void setMAttributesetinstanceId(Long mAttributesetinstanceId) {
        this.mAttributesetinstanceId = mAttributesetinstanceId;
    }

    /**
     * Gets downloadurl
     * 
     * @return Value for downloadurl.
     **/
    public String getDownloadurl() {
        return downloadurl;
    }

    /**
     * Sets downloadurl
     * 
     * @param downloadurl New value for downloadurl.
     **/
    public void setDownloadurl(String downloadurl) {
        this.downloadurl = downloadurl;
    }

    /**
     * Gets mFreightcategoryId
     * 
     * @return Value for mFreightcategoryId.
     **/
    public Long getMFreightcategoryId() {
        return mFreightcategoryId;
    }

    /**
     * Sets mFreightcategoryId
     * 
     * @param mFreightcategoryId New value for mFreightcategoryId.
     **/
    public void setMFreightcategoryId(Long mFreightcategoryId) {
        this.mFreightcategoryId = mFreightcategoryId;
    }

    /**
     * Gets mLocatorId
     * 
     * @return Value for mLocatorId.
     **/
    public Long getMLocatorId() {
        return mLocatorId;
    }

    /**
     * Sets mLocatorId
     * 
     * @param mLocatorId New value for mLocatorId.
     **/
    public void setMLocatorId(Long mLocatorId) {
        this.mLocatorId = mLocatorId;
    }

    /**
     * Gets guaranteedaysmin
     * 
     * @return Value for guaranteedaysmin.
     **/
    public Long getGuaranteedaysmin() {
        return guaranteedaysmin;
    }

    /**
     * Sets guaranteedaysmin
     * 
     * @param guaranteedaysmin New value for guaranteedaysmin.
     **/
    public void setGuaranteedaysmin(Long guaranteedaysmin) {
        this.guaranteedaysmin = guaranteedaysmin;
    }

    /**
     * Gets iswebstorefeatured
     * 
     * @return Value for iswebstorefeatured.
     **/
    public String getIswebstorefeatured() {
        return iswebstorefeatured;
    }

    /**
     * Sets iswebstorefeatured
     * 
     * @param iswebstorefeatured New value for iswebstorefeatured.
     **/
    public void setIswebstorefeatured(String iswebstorefeatured) {
        this.iswebstorefeatured = iswebstorefeatured;
    }

    /**
     * Gets isselfservice
     * 
     * @return Value for isselfservice.
     **/
    public String getIsselfservice() {
        return isselfservice;
    }

    /**
     * Sets isselfservice
     * 
     * @param isselfservice New value for isselfservice.
     **/
    public void setIsselfservice(String isselfservice) {
        this.isselfservice = isselfservice;
    }

    /**
     * Gets cSubscriptiontypeId
     * 
     * @return Value for cSubscriptiontypeId.
     **/
    public Long getCSubscriptiontypeId() {
        return cSubscriptiontypeId;
    }

    /**
     * Sets cSubscriptiontypeId
     * 
     * @param cSubscriptiontypeId New value for cSubscriptiontypeId.
     **/
    public void setCSubscriptiontypeId(Long cSubscriptiontypeId) {
        this.cSubscriptiontypeId = cSubscriptiontypeId;
    }

    /**
     * Gets isdropship
     * 
     * @return Value for isdropship.
     **/
    public String getIsdropship() {
        return isdropship;
    }

    /**
     * Sets isdropship
     * 
     * @param isdropship New value for isdropship.
     **/
    public void setIsdropship(String isdropship) {
        this.isdropship = isdropship;
    }

    /**
     * Gets zlasttransactiondate
     * 
     * @return Value for zlasttransactiondate.
     **/
    public Date getZlasttransactiondate() {
        return zlasttransactiondate;
    }

    /**
     * Sets zlasttransactiondate
     * 
     * @param zlasttransactiondate New value for zlasttransactiondate.
     **/
    public void setZlasttransactiondate(Date zlasttransactiondate) {
        this.zlasttransactiondate = zlasttransactiondate;
    }

    /**
     * Gets isexcludeautodelivery
     * 
     * @return Value for isexcludeautodelivery.
     **/
    public String getIsexcludeautodelivery() {
        return isexcludeautodelivery;
    }

    /**
     * Sets isexcludeautodelivery
     * 
     * @param isexcludeautodelivery New value for isexcludeautodelivery.
     **/
    public void setIsexcludeautodelivery(String isexcludeautodelivery) {
        this.isexcludeautodelivery = isexcludeautodelivery;
    }

    /**
     * Gets codedouanier
     * 
     * @return Value for codedouanier.
     **/
    public String getCodedouanier() {
        return codedouanier;
    }

    /**
     * Sets codedouanier
     * 
     * @param codedouanier New value for codedouanier.
     **/
    public void setCodedouanier(String codedouanier) {
        this.codedouanier = codedouanier;
    }

    /**
     * Gets commoditycode
     * 
     * @return Value for commoditycode.
     **/
    public String getCommoditycode() {
        return commoditycode;
    }

    /**
     * Sets commoditycode
     * 
     * @param commoditycode New value for commoditycode.
     **/
    public void setCommoditycode(String commoditycode) {
        this.commoditycode = commoditycode;
    }

    /**
     * Gets supportunits
     * 
     * @return Value for supportunits.
     **/
    public Long getSupportunits() {
        return supportunits;
    }

    /**
     * Sets supportunits
     * 
     * @param supportunits New value for supportunits.
     **/
    public void setSupportunits(Long supportunits) {
        this.supportunits = supportunits;
    }

    /**
     * Gets ispurchasedtoorder
     * 
     * @return Value for ispurchasedtoorder.
     **/
    public String getIspurchasedtoorder() {
        return ispurchasedtoorder;
    }

    /**
     * Sets ispurchasedtoorder
     * 
     * @param ispurchasedtoorder New value for ispurchasedtoorder.
     **/
    public void setIspurchasedtoorder(String ispurchasedtoorder) {
        this.ispurchasedtoorder = ispurchasedtoorder;
    }

    /**
     * Gets licenseinfo
     * 
     * @return Value for licenseinfo.
     **/
    public String getLicenseinfo() {
        return licenseinfo;
    }

    /**
     * Sets licenseinfo
     * 
     * @param licenseinfo New value for licenseinfo.
     **/
    public void setLicenseinfo(String licenseinfo) {
        this.licenseinfo = licenseinfo;
    }

    /**
     * Gets rSourceId
     * 
     * @return Value for rSourceId.
     **/
    public Long getRSourceId() {
        return rSourceId;
    }

    /**
     * Sets rSourceId
     * 
     * @param rSourceId New value for rSourceId.
     **/
    public void setRSourceId(Long rSourceId) {
        this.rSourceId = rSourceId;
    }

    /**
     * Gets trialphasedays
     * 
     * @return Value for trialphasedays.
     **/
    public Long getTrialphasedays() {
        return trialphasedays;
    }

    /**
     * Sets trialphasedays
     * 
     * @param trialphasedays New value for trialphasedays.
     **/
    public void setTrialphasedays(Long trialphasedays) {
        this.trialphasedays = trialphasedays;
    }

    /**
     * Gets zUomfId
     * 
     * @return Value for zUomfId.
     **/
    public Long getZUomfId() {
        return zUomfId;
    }

    /**
     * Sets zUomfId
     * 
     * @param zUomfId New value for zUomfId.
     **/
    public void setZUomfId(Long zUomfId) {
        this.zUomfId = zUomfId;
    }

    /**
     * Gets zPriceumf
     * 
     * @return Value for zPriceumf.
     **/
    public BigDecimal getZPriceumf() {
        return zPriceumf;
    }

    /**
     * Sets zPriceumf
     * 
     * @param zPriceumf New value for zPriceumf.
     **/
    public void setZPriceumf(BigDecimal zPriceumf) {
        this.zPriceumf = zPriceumf;
    }

    /**
     * Gets zAttributeumfId
     * 
     * @return Value for zAttributeumfId.
     **/
    public Long getZAttributeumfId() {
        return zAttributeumfId;
    }

    /**
     * Sets zAttributeumfId
     * 
     * @param zAttributeumfId New value for zAttributeumfId.
     **/
    public void setZAttributeumfId(Long zAttributeumfId) {
        this.zAttributeumfId = zAttributeumfId;
    }

    /**
     * Gets xxProductclass
     * 
     * @return Value for xxProductclass.
     **/
    public String getXxProductclass() {
        return xxProductclass;
    }

    /**
     * Sets xxProductclass
     * 
     * @param xxProductclass New value for xxProductclass.
     **/
    public void setXxProductclass(String xxProductclass) {
        this.xxProductclass = xxProductclass;
    }

    /**
     * Gets type
     * 
     * @return Value for type.
     **/
    public String getType() {
        return type;
    }

    /**
     * Sets type
     * 
     * @param type New value for type.
     **/
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Gets xxMarketingcategory
     * 
     * @return Value for xxMarketingcategory.
     **/
    public String getXxMarketingcategory() {
        return xxMarketingcategory;
    }

    /**
     * Sets xxMarketingcategory
     * 
     * @param xxMarketingcategory New value for xxMarketingcategory.
     **/
    public void setXxMarketingcategory(String xxMarketingcategory) {
        this.xxMarketingcategory = xxMarketingcategory;
    }

    /**
     * Gets xxRank
     * 
     * @return Value for xxRank.
     **/
    public Long getXxRank() {
        return xxRank;
    }

    /**
     * Sets xxRank
     * 
     * @param xxRank New value for xxRank.
     **/
    public void setXxRank(Long xxRank) {
        this.xxRank = xxRank;
    }

    /**
     * Gets xxPricelevel
     * 
     * @return Value for xxPricelevel.
     **/
    public BigDecimal getXxPricelevel() {
        return xxPricelevel;
    }

    /**
     * Sets xxPricelevel
     * 
     * @param xxPricelevel New value for xxPricelevel.
     **/
    public void setXxPricelevel(BigDecimal xxPricelevel) {
        this.xxPricelevel = xxPricelevel;
    }

    /**
     * Gets isotc
     * 
     * @return Value for isotc.
     **/
    public String getIsotc() {
        return isotc;
    }

    /**
     * Sets isotc
     * 
     * @param isotc New value for isotc.
     **/
    public void setIsotc(String isotc) {
        this.isotc = isotc;
    }

    /**
     * Gets ischronical
     * 
     * @return Value for ischronical.
     **/
    public String getIschronical() {
        return ischronical;
    }

    /**
     * Sets ischronical
     * 
     * @param ischronical New value for ischronical.
     **/
    public void setIschronical(String ischronical) {
        this.ischronical = ischronical;
    }

    /**
     * Gets isaigue
     * 
     * @return Value for isaigue.
     **/
    public String getIsaigue() {
        return isaigue;
    }

    /**
     * Sets isaigue
     * 
     * @param isaigue New value for isaigue.
     **/
    public void setIsaigue(String isaigue) {
        this.isaigue = isaigue;
    }

    /**
     * Gets ispromu
     * 
     * @return Value for ispromu.
     **/
    public String getIspromu() {
        return ispromu;
    }

    /**
     * Sets ispromu
     * 
     * @param ispromu New value for ispromu.
     **/
    public void setIspromu(String ispromu) {
        this.ispromu = ispromu;
    }

    /**
     * Gets ispsychotrope
     * 
     * @return Value for ispsychotrope.
     **/
    public String getIspsychotrope() {
        return ispsychotrope;
    }

    /**
     * Sets ispsychotrope
     * 
     * @param ispsychotrope New value for ispsychotrope.
     **/
    public void setIspsychotrope(String ispsychotrope) {
        this.ispsychotrope = ispsychotrope;
    }

    /**
     * Gets isprodnationale
     * 
     * @return Value for isprodnationale.
     **/
    public String getIsprodnationale() {
        return isprodnationale;
    }

    /**
     * Sets isprodnationale
     * 
     * @param isprodnationale New value for isprodnationale.
     **/
    public void setIsprodnationale(String isprodnationale) {
        this.isprodnationale = isprodnationale;
    }

    /**
     * Gets isagreement
     * 
     * @return Value for isagreement.
     **/
    public String getIsagreement() {
        return isagreement;
    }

    /**
     * Sets isagreement
     * 
     * @param isagreement New value for isagreement.
     **/
    public void setIsagreement(String isagreement) {
        this.isagreement = isagreement;
    }

    /**
     * Gets iscoldchain
     * 
     * @return Value for iscoldchain.
     **/
    public String getIscoldchain() {
        return iscoldchain;
    }

    /**
     * Sets iscoldchain
     * 
     * @param iscoldchain New value for iscoldchain.
     **/
    public void setIscoldchain(String iscoldchain) {
        this.iscoldchain = iscoldchain;
    }

    /**
     * Gets isrefundable
     * 
     * @return Value for isrefundable.
     **/
    public String getIsrefundable() {
        return isrefundable;
    }

    /**
     * Sets isrefundable
     * 
     * @param isrefundable New value for isrefundable.
     **/
    public void setIsrefundable(String isrefundable) {
        this.isrefundable = isrefundable;
    }

    /**
     * Gets xxDriveragreement
     * 
     * @return Value for xxDriveragreement.
     **/
    public String getXxDriveragreement() {
        return xxDriveragreement;
    }

    /**
     * Sets xxDriveragreement
     * 
     * @param xxDriveragreement New value for xxDriveragreement.
     **/
    public void setXxDriveragreement(String xxDriveragreement) {
        this.xxDriveragreement = xxDriveragreement;
    }

    /**
     * Gets xxPresentation
     * 
     * @return Value for xxPresentation.
     **/
    public String getXxPresentation() {
        return xxPresentation;
    }

    /**
     * Sets xxPresentation
     * 
     * @param xxPresentation New value for xxPresentation.
     **/
    public void setXxPresentation(String xxPresentation) {
        this.xxPresentation = xxPresentation;
    }

    /**
     * Gets xxLaboratoryId
     * 
     * @return Value for xxLaboratoryId.
     **/
    public Long getXxLaboratoryId() {
        return xxLaboratoryId;
    }

    /**
     * Sets xxLaboratoryId
     * 
     * @param xxLaboratoryId New value for xxLaboratoryId.
     **/
    public void setXxLaboratoryId(Long xxLaboratoryId) {
        this.xxLaboratoryId = xxLaboratoryId;
    }

    /**
     * Gets xxUg
     * 
     * @return Value for xxUg.
     **/
    public BigDecimal getXxUg() {
        return xxUg;
    }

    /**
     * Sets xxUg
     * 
     * @param xxUg New value for xxUg.
     **/
    public void setXxUg(BigDecimal xxUg) {
        this.xxUg = xxUg;
    }

    /**
     * Gets xxClassificationId
     * 
     * @return Value for xxClassificationId.
     **/
    public Long getXxClassificationId() {
        return xxClassificationId;
    }

    /**
     * Sets xxClassificationId
     * 
     * @param xxClassificationId New value for xxClassificationId.
     **/
    public void setXxClassificationId(Long xxClassificationId) {
        this.xxClassificationId = xxClassificationId;
    }

    /**
     * Gets quantity
     * 
     * @return Value for quantity.
     **/
    public Long getQuantity() {
        return quantity;
    }

    /**
     * Sets quantity
     * 
     * @param quantity New value for quantity.
     **/
    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }

    /**
     * Gets xxFormattributeId
     * 
     * @return Value for xxFormattributeId.
     **/
    public Long getXxFormattributeId() {
        return xxFormattributeId;
    }

    /**
     * Sets xxFormattributeId
     * 
     * @param xxFormattributeId New value for xxFormattributeId.
     **/
    public void setXxFormattributeId(Long xxFormattributeId) {
        this.xxFormattributeId = xxFormattributeId;
    }

    /**
     * Gets xxAssayId
     * 
     * @return Value for xxAssayId.
     **/
    public Long getXxAssayId() {
        return xxAssayId;
    }

    /**
     * Sets xxAssayId
     * 
     * @param xxAssayId New value for xxAssayId.
     **/
    public void setXxAssayId(Long xxAssayId) {
        this.xxAssayId = xxAssayId;
    }

    /**
     * Gets xxFormeId
     * 
     * @return Value for xxFormeId.
     **/
    public Long getXxFormeId() {
        return xxFormeId;
    }

    /**
     * Sets xxFormeId
     * 
     * @param xxFormeId New value for xxFormeId.
     **/
    public void setXxFormeId(Long xxFormeId) {
        this.xxFormeId = xxFormeId;
    }

    /**
     * Gets xxMaxqty
     * 
     * @return Value for xxMaxqty.
     **/
    public BigDecimal getXxMaxqty() {
        return xxMaxqty;
    }

    /**
     * Sets xxMaxqty
     * 
     * @param xxMaxqty New value for xxMaxqty.
     **/
    public void setXxMaxqty(BigDecimal xxMaxqty) {
        this.xxMaxqty = xxMaxqty;
    }

    /**
     * Gets xxDistributequota
     * 
     * @return Value for xxDistributequota.
     **/
    public String getXxDistributequota() {
        return xxDistributequota;
    }

    /**
     * Sets xxDistributequota
     * 
     * @param xxDistributequota New value for xxDistributequota.
     **/
    public void setXxDistributequota(String xxDistributequota) {
        this.xxDistributequota = xxDistributequota;
    }

    /**
     * Gets adColorId
     * 
     * @return Value for adColorId.
     **/
    public Long getAdColorId() {
        return adColorId;
    }

    /**
     * Sets adColorId
     * 
     * @param adColorId New value for adColorId.
     **/
    public void setAdColorId(Long adColorId) {
        this.adColorId = adColorId;
    }

    /**
     * Gets adPrintcolorId
     * 
     * @return Value for adPrintcolorId.
     **/
    public Long getAdPrintcolorId() {
        return adPrintcolorId;
    }

    /**
     * Sets adPrintcolorId
     * 
     * @param adPrintcolorId New value for adPrintcolorId.
     **/
    public void setAdPrintcolorId(Long adPrintcolorId) {
        this.adPrintcolorId = adPrintcolorId;
    }

    /**
     * Gets colortype
     * 
     * @return Value for colortype.
     **/
    public String getColortype() {
        return colortype;
    }

    /**
     * Sets colortype
     * 
     * @param colortype New value for colortype.
     **/
    public void setColortype(String colortype) {
        this.colortype = colortype;
    }

    /**
     * Gets red
     * 
     * @return Value for red.
     **/
    public Long getRed() {
        return red;
    }

    /**
     * Sets red
     * 
     * @param red New value for red.
     **/
    public void setRed(Long red) {
        this.red = red;
    }

    /**
     * Gets green
     * 
     * @return Value for green.
     **/
    public Long getGreen() {
        return green;
    }

    /**
     * Sets green
     * 
     * @param green New value for green.
     **/
    public void setGreen(Long green) {
        this.green = green;
    }

    /**
     * Gets blue
     * 
     * @return Value for blue.
     **/
    public Long getBlue() {
        return blue;
    }

    /**
     * Sets blue
     * 
     * @param blue New value for blue.
     **/
    public void setBlue(Long blue) {
        this.blue = blue;
    }

    /**
     * Gets xxSalescontextId
     * 
     * @return Value for xxSalescontextId.
     **/
    public Long getXxSalescontextId() {
        return xxSalescontextId;
    }

    /**
     * Sets xxSalescontextId
     * 
     * @param xxSalescontextId New value for xxSalescontextId.
     **/
    public void setXxSalescontextId(Long xxSalescontextId) {
        this.xxSalescontextId = xxSalescontextId;
    }

    /**
     * Gets xxShp
     * 
     * @return Value for xxShp.
     **/
    public BigDecimal getXxShp() {
        return xxShp;
    }

    /**
     * Sets xxShp
     * 
     * @param xxShp New value for xxShp.
     **/
    public void setXxShp(BigDecimal xxShp) {
        this.xxShp = xxShp;
    }

    /**
     * Gets xxTarifRef
     * 
     * @return Value for xxTarifRef.
     **/
    public BigDecimal getXxTarifRef() {
        return xxTarifRef;
    }

    /**
     * Sets xxTarifRef
     * 
     * @param xxTarifRef New value for xxTarifRef.
     **/
    public void setXxTarifRef(BigDecimal xxTarifRef) {
        this.xxTarifRef = xxTarifRef;
    }

    /**
     * Gets cCountryId
     * 
     * @return Value for cCountryId.
     **/
    public Long getCCountryId() {
        return cCountryId;
    }

    /**
     * Sets cCountryId
     * 
     * @param cCountryId New value for cCountryId.
     **/
    public void setCCountryId(Long cCountryId) {
        this.cCountryId = cCountryId;
    }

    /**
     * Gets xxListeProduct
     * 
     * @return Value for xxListeProduct.
     **/
    public String getXxListeProduct() {
        return xxListeProduct;
    }

    /**
     * Sets xxListeProduct
     * 
     * @param xxListeProduct New value for xxListeProduct.
     **/
    public void setXxListeProduct(String xxListeProduct) {
        this.xxListeProduct = xxListeProduct;
    }

    /**
     * Gets dateenregistrement
     * 
     * @return Value for dateenregistrement.
     **/
    public Date getDateenregistrement() {
        return dateenregistrement;
    }

    /**
     * Sets dateenregistrement
     * 
     * @param dateenregistrement New value for dateenregistrement.
     **/
    public void setDateenregistrement(Date dateenregistrement) {
        this.dateenregistrement = dateenregistrement;
    }

    /**
     * Gets xxConditionnementId
     * 
     * @return Value for xxConditionnementId.
     **/
    public Long getXxConditionnementId() {
        return xxConditionnementId;
    }

    /**
     * Sets xxConditionnementId
     * 
     * @param xxConditionnementId New value for xxConditionnementId.
     **/
    public void setXxConditionnementId(Long xxConditionnementId) {
        this.xxConditionnementId = xxConditionnementId;
    }

    /**
     * Gets isqr
     * 
     * @return Value for isqr.
     **/
    public String getIsqr() {
        return isqr;
    }

    /**
     * Sets isqr
     * 
     * @param isqr New value for isqr.
     **/
    public void setIsqr(String isqr) {
        this.isqr = isqr;
    }

    /**
     * Gets xxProductlineId
     * 
     * @return Value for xxProductlineId.
     **/
    public Long getXxProductlineId() {
        return xxProductlineId;
    }

    /**
     * Sets xxProductlineId
     * 
     * @param xxProductlineId New value for xxProductlineId.
     **/
    public void setXxProductlineId(Long xxProductlineId) {
        this.xxProductlineId = xxProductlineId;
    }

    /**
     * Gets cPaymenttermId
     * 
     * @return Value for cPaymenttermId.
     **/
    public Long getCPaymenttermId() {
        return cPaymenttermId;
    }

    /**
     * Sets cPaymenttermId
     * 
     * @param cPaymenttermId New value for cPaymenttermId.
     **/
    public void setCPaymenttermId(Long cPaymenttermId) {
        this.cPaymenttermId = cPaymenttermId;
    }

    /**
     * Gets xxCreateupdatesubstitut
     * 
     * @return Value for xxCreateupdatesubstitut.
     **/
    public String getXxCreateupdatesubstitut() {
        return xxCreateupdatesubstitut;
    }

    /**
     * Sets xxCreateupdatesubstitut
     * 
     * @param xxCreateupdatesubstitut New value for xxCreateupdatesubstitut.
     **/
    public void setXxCreateupdatesubstitut(String xxCreateupdatesubstitut) {
        this.xxCreateupdatesubstitut = xxCreateupdatesubstitut;
    }

    /**
     * Gets ischer
     * 
     * @return Value for ischer.
     **/
    public String getIscher() {
        return ischer;
    }

    /**
     * Sets ischer
     * 
     * @param ischer New value for ischer.
     **/
    public void setIscher(String ischer) {
        this.ischer = ischer;
    }

    /**
     * Gets xxLastugachat
     * 
     * @return Value for xxLastugachat.
     **/
    public BigDecimal getXxLastugachat() {
        return xxLastugachat;
    }

    /**
     * Sets xxLastugachat
     * 
     * @param xxLastugachat New value for xxLastugachat.
     **/
    public void setXxLastugachat(BigDecimal xxLastugachat) {
        this.xxLastugachat = xxLastugachat;
    }

    /**
     * Gets xxStartegicalproduct
     * 
     * @return Value for xxStartegicalproduct.
     **/
    public String getXxStartegicalproduct() {
        return xxStartegicalproduct;
    }

    /**
     * Sets xxStartegicalproduct
     * 
     * @param xxStartegicalproduct New value for xxStartegicalproduct.
     **/
    public void setXxStartegicalproduct(String xxStartegicalproduct) {
        this.xxStartegicalproduct = xxStartegicalproduct;
    }

    /**
     * Gets xxIsquotasystem
     * 
     * @return Value for xxIsquotasystem.
     **/
    public String getXxIsquotasystem() {
        return xxIsquotasystem;
    }

    /**
     * Sets xxIsquotasystem
     * 
     * @param xxIsquotasystem New value for xxIsquotasystem.
     **/
    public void setXxIsquotasystem(String xxIsquotasystem) {
        this.xxIsquotasystem = xxIsquotasystem;
    }

    /**
     * Gets xxTauxvaleur
     * 
     * @return Value for xxTauxvaleur.
     **/
    public Long getXxTauxvaleur() {
        return xxTauxvaleur;
    }

    /**
     * Sets xxTauxvaleur
     * 
     * @param xxTauxvaleur New value for xxTauxvaleur.
     **/
    public void setXxTauxvaleur(Long xxTauxvaleur) {
        this.xxTauxvaleur = xxTauxvaleur;
    }

    /**
     * Gets xxProduitsurcommande
     * 
     * @return Value for xxProduitsurcommande.
     **/
    public String getXxProduitsurcommande() {
        return xxProduitsurcommande;
    }

    /**
     * Sets xxProduitsurcommande
     * 
     * @param xxProduitsurcommande New value for xxProduitsurcommande.
     **/
    public void setXxProduitsurcommande(String xxProduitsurcommande) {
        this.xxProduitsurcommande = xxProduitsurcommande;
    }

    /**
     * Gets xxTypecommande
     * 
     * @return Value for xxTypecommande.
     **/
    public String getXxTypecommande() {
        return xxTypecommande;
    }

    /**
     * Sets xxTypecommande
     * 
     * @param xxTypecommande New value for xxTypecommande.
     **/
    public void setXxTypecommande(String xxTypecommande) {
        this.xxTypecommande = xxTypecommande;
    }

    /**
     * Gets xxListetauxvaleurId
     * 
     * @return Value for xxListetauxvaleurId.
     **/
    public Long getXxListetauxvaleurId() {
        return xxListetauxvaleurId;
    }

    /**
     * Sets xxListetauxvaleurId
     * 
     * @param xxListetauxvaleurId New value for xxListetauxvaleurId.
     **/
    public void setXxListetauxvaleurId(Long xxListetauxvaleurId) {
        this.xxListetauxvaleurId = xxListetauxvaleurId;
    }

    /**
     * Gets xxCorrespondancecapital
     * 
     * @return Value for xxCorrespondancecapital.
     **/
    public String getXxCorrespondancecapital() {
        return xxCorrespondancecapital;
    }

    /**
     * Sets xxCorrespondancecapital
     * 
     * @param xxCorrespondancecapital New value for xxCorrespondancecapital.
     **/
    public void setXxCorrespondancecapital(String xxCorrespondancecapital) {
        this.xxCorrespondancecapital = xxCorrespondancecapital;
    }

    /**
     * Gets xxCriticalproduct
     * 
     * @return Value for xxCriticalproduct.
     **/
    public String getXxCriticalproduct() {
        return xxCriticalproduct;
    }

    /**
     * Sets xxCriticalproduct
     * 
     * @param xxCriticalproduct New value for xxCriticalproduct.
     **/
    public void setXxCriticalproduct(String xxCriticalproduct) {
        this.xxCriticalproduct = xxCriticalproduct;
    }

    /**
     * Gets xxCapitalName
     * 
     * @return Value for xxCapitalName.
     **/
    public String getXxCapitalName() {
        return xxCapitalName;
    }

    /**
     * Sets xxCapitalName
     * 
     * @param xxCapitalName New value for xxCapitalName.
     **/
    public void setXxCapitalName(String xxCapitalName) {
        this.xxCapitalName = xxCapitalName;
    }

    /**
     * Gets xxCapitalName2
     * 
     * @return Value for xxCapitalName2.
     **/
    public String getXxCapitalName2() {
        return xxCapitalName2;
    }

    /**
     * Sets xxCapitalName2
     * 
     * @param xxCapitalName2 New value for xxCapitalName2.
     **/
    public void setXxCapitalName2(String xxCapitalName2) {
        this.xxCapitalName2 = xxCapitalName2;
    }

    /**
     * Gets xxUgbylot
     * 
     * @return Value for xxUgbylot.
     **/
    public String getXxUgbylot() {
        return xxUgbylot;
    }

    /**
     * Sets xxUgbylot
     * 
     * @param xxUgbylot New value for xxUgbylot.
     **/
    public void setXxUgbylot(String xxUgbylot) {
        this.xxUgbylot = xxUgbylot;
    }

    /**
     * Gets xxSoumiapprobation
     * 
     * @return Value for xxSoumiapprobation.
     **/
    public String getXxSoumiapprobation() {
        return xxSoumiapprobation;
    }

    /**
     * Sets xxSoumiapprobation
     * 
     * @param xxSoumiapprobation New value for xxSoumiapprobation.
     **/
    public void setXxSoumiapprobation(String xxSoumiapprobation) {
        this.xxSoumiapprobation = xxSoumiapprobation;
    }

    /**
     * Gets xxUpdatesalesctxmap
     * 
     * @return Value for xxUpdatesalesctxmap.
     **/
    public String getXxUpdatesalesctxmap() {
        return xxUpdatesalesctxmap;
    }

    /**
     * Sets xxUpdatesalesctxmap
     * 
     * @param xxUpdatesalesctxmap New value for xxUpdatesalesctxmap.
     **/
    public void setXxUpdatesalesctxmap(String xxUpdatesalesctxmap) {
        this.xxUpdatesalesctxmap = xxUpdatesalesctxmap;
    }

    /**
     * Gets xxResteQuota
     * 
     * @return Value for xxResteQuota.
     **/
    public Long getXxResteQuota() {
        return xxResteQuota;
    }

    /**
     * Sets xxResteQuota
     * 
     * @param xxResteQuota New value for xxResteQuota.
     **/
    public void setXxResteQuota(Long xxResteQuota) {
        this.xxResteQuota = xxResteQuota;
    }

    /**
     * Gets xxUpdateprodcatctxvte
     * 
     * @return Value for xxUpdateprodcatctxvte.
     **/
    public String getXxUpdateprodcatctxvte() {
        return xxUpdateprodcatctxvte;
    }

    /**
     * Sets xxUpdateprodcatctxvte
     * 
     * @param xxUpdateprodcatctxvte New value for xxUpdateprodcatctxvte.
     **/
    public void setXxUpdateprodcatctxvte(String xxUpdateprodcatctxvte) {
        this.xxUpdateprodcatctxvte = xxUpdateprodcatctxvte;
    }

    /**
     * Gets generatesalesctx
     * 
     * @return Value for generatesalesctx.
     **/
    public String getGeneratesalesctx() {
        return generatesalesctx;
    }

    /**
     * Sets generatesalesctx
     * 
     * @param generatesalesctx New value for generatesalesctx.
     **/
    public void setGeneratesalesctx(String generatesalesctx) {
        this.generatesalesctx = generatesalesctx;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof MProduct))
            return false;
        
        MProduct that = (MProduct)o;

        if (adClientId != that.adClientId)
            return false;
        

        if (adOrgId != that.adOrgId)
            return false;
        

        if (isactive != null ? !isactive.equals(that.isactive) : that.isactive != null)
            return false;
        

        if (created != null ? !created.equals(that.created) : that.created != null)
            return false;
        

        if (createdby != that.createdby)
            return false;
        

        if (updated != null ? !updated.equals(that.updated) : that.updated != null)
            return false;
        

        if (updatedby != that.updatedby)
            return false;
        

        if (value != null ? !value.equals(that.value) : that.value != null)
            return false;
        

        if (name != null ? !name.equals(that.name) : that.name != null)
            return false;
        

        if (description != null ? !description.equals(that.description) : that.description != null)
            return false;
        

        if (documentnote != null ? !documentnote.equals(that.documentnote) : that.documentnote != null)
            return false;
        

        if (help != null ? !help.equals(that.help) : that.help != null)
            return false;
        

        if (upc != null ? !upc.equals(that.upc) : that.upc != null)
            return false;
        

        if (sku != null ? !sku.equals(that.sku) : that.sku != null)
            return false;
        

        if (cUomId != that.cUomId)
            return false;
        

        if (salesrepId != null ? !salesrepId.equals(that.salesrepId) : that.salesrepId != null)
            return false;
        

        if (issummary != null ? !issummary.equals(that.issummary) : that.issummary != null)
            return false;
        

        if (isstocked != null ? !isstocked.equals(that.isstocked) : that.isstocked != null)
            return false;
        

        if (ispurchased != null ? !ispurchased.equals(that.ispurchased) : that.ispurchased != null)
            return false;
        

        if (issold != null ? !issold.equals(that.issold) : that.issold != null)
            return false;
        

        if (isbom != null ? !isbom.equals(that.isbom) : that.isbom != null)
            return false;
        

        if (isinvoiceprintdetails != null ? !isinvoiceprintdetails.equals(that.isinvoiceprintdetails) : that.isinvoiceprintdetails != null)
            return false;
        

        if (ispicklistprintdetails != null ? !ispicklistprintdetails.equals(that.ispicklistprintdetails) : that.ispicklistprintdetails != null)
            return false;
        

        if (isverified != null ? !isverified.equals(that.isverified) : that.isverified != null)
            return false;
        

        if (mProductCategoryId != that.mProductCategoryId)
            return false;
        

        if (classification != null ? !classification.equals(that.classification) : that.classification != null)
            return false;
        

        if (volume != null ? !volume.equals(that.volume) : that.volume != null)
            return false;
        

        if (weight != null ? !weight.equals(that.weight) : that.weight != null)
            return false;
        

        if (shelfwidth != null ? !shelfwidth.equals(that.shelfwidth) : that.shelfwidth != null)
            return false;
        

        if (shelfheight != null ? !shelfheight.equals(that.shelfheight) : that.shelfheight != null)
            return false;
        

        if (shelfdepth != null ? !shelfdepth.equals(that.shelfdepth) : that.shelfdepth != null)
            return false;
        

        if (unitsperpallet != null ? !unitsperpallet.equals(that.unitsperpallet) : that.unitsperpallet != null)
            return false;
        

        if (cTaxcategoryId != that.cTaxcategoryId)
            return false;
        

        if (sResourceId != null ? !sResourceId.equals(that.sResourceId) : that.sResourceId != null)
            return false;
        

        if (discontinued != null ? !discontinued.equals(that.discontinued) : that.discontinued != null)
            return false;
        

        if (discontinuedby != null ? !discontinuedby.equals(that.discontinuedby) : that.discontinuedby != null)
            return false;
        

        if (processing != null ? !processing.equals(that.processing) : that.processing != null)
            return false;
        

        if (sExpensetypeId != null ? !sExpensetypeId.equals(that.sExpensetypeId) : that.sExpensetypeId != null)
            return false;
        

        if (producttype != null ? !producttype.equals(that.producttype) : that.producttype != null)
            return false;
        

        if (imageurl != null ? !imageurl.equals(that.imageurl) : that.imageurl != null)
            return false;
        

        if (descriptionurl != null ? !descriptionurl.equals(that.descriptionurl) : that.descriptionurl != null)
            return false;
        

        if (guaranteedays != null ? !guaranteedays.equals(that.guaranteedays) : that.guaranteedays != null)
            return false;
        

        if (rMailtextId != null ? !rMailtextId.equals(that.rMailtextId) : that.rMailtextId != null)
            return false;
        

        if (versionno != null ? !versionno.equals(that.versionno) : that.versionno != null)
            return false;
        

        if (mAttributesetId != null ? !mAttributesetId.equals(that.mAttributesetId) : that.mAttributesetId != null)
            return false;
        

        if (mAttributesetinstanceId != null ? !mAttributesetinstanceId.equals(that.mAttributesetinstanceId) : that.mAttributesetinstanceId != null)
            return false;
        

        if (downloadurl != null ? !downloadurl.equals(that.downloadurl) : that.downloadurl != null)
            return false;
        

        if (mFreightcategoryId != null ? !mFreightcategoryId.equals(that.mFreightcategoryId) : that.mFreightcategoryId != null)
            return false;
        

        if (mLocatorId != null ? !mLocatorId.equals(that.mLocatorId) : that.mLocatorId != null)
            return false;
        

        if (guaranteedaysmin != null ? !guaranteedaysmin.equals(that.guaranteedaysmin) : that.guaranteedaysmin != null)
            return false;
        

        if (iswebstorefeatured != null ? !iswebstorefeatured.equals(that.iswebstorefeatured) : that.iswebstorefeatured != null)
            return false;
        

        if (isselfservice != null ? !isselfservice.equals(that.isselfservice) : that.isselfservice != null)
            return false;
        

        if (cSubscriptiontypeId != null ? !cSubscriptiontypeId.equals(that.cSubscriptiontypeId) : that.cSubscriptiontypeId != null)
            return false;
        

        if (isdropship != null ? !isdropship.equals(that.isdropship) : that.isdropship != null)
            return false;
        

        if (zlasttransactiondate != null ? !zlasttransactiondate.equals(that.zlasttransactiondate) : that.zlasttransactiondate != null)
            return false;
        

        if (isexcludeautodelivery != null ? !isexcludeautodelivery.equals(that.isexcludeautodelivery) : that.isexcludeautodelivery != null)
            return false;
        

        if (codedouanier != null ? !codedouanier.equals(that.codedouanier) : that.codedouanier != null)
            return false;
        

        if (commoditycode != null ? !commoditycode.equals(that.commoditycode) : that.commoditycode != null)
            return false;
        

        if (supportunits != null ? !supportunits.equals(that.supportunits) : that.supportunits != null)
            return false;
        

        if (ispurchasedtoorder != null ? !ispurchasedtoorder.equals(that.ispurchasedtoorder) : that.ispurchasedtoorder != null)
            return false;
        

        if (licenseinfo != null ? !licenseinfo.equals(that.licenseinfo) : that.licenseinfo != null)
            return false;
        

        if (rSourceId != null ? !rSourceId.equals(that.rSourceId) : that.rSourceId != null)
            return false;
        

        if (trialphasedays != null ? !trialphasedays.equals(that.trialphasedays) : that.trialphasedays != null)
            return false;
        

        if (zUomfId != null ? !zUomfId.equals(that.zUomfId) : that.zUomfId != null)
            return false;
        

        if (zPriceumf != null ? !zPriceumf.equals(that.zPriceumf) : that.zPriceumf != null)
            return false;
        

        if (zAttributeumfId != null ? !zAttributeumfId.equals(that.zAttributeumfId) : that.zAttributeumfId != null)
            return false;
        

        if (xxProductclass != null ? !xxProductclass.equals(that.xxProductclass) : that.xxProductclass != null)
            return false;
        

        if (type != null ? !type.equals(that.type) : that.type != null)
            return false;
        

        if (xxMarketingcategory != null ? !xxMarketingcategory.equals(that.xxMarketingcategory) : that.xxMarketingcategory != null)
            return false;
        

        if (xxRank != null ? !xxRank.equals(that.xxRank) : that.xxRank != null)
            return false;
        

        if (xxPricelevel != null ? !xxPricelevel.equals(that.xxPricelevel) : that.xxPricelevel != null)
            return false;
        

        if (isotc != null ? !isotc.equals(that.isotc) : that.isotc != null)
            return false;
        

        if (ischronical != null ? !ischronical.equals(that.ischronical) : that.ischronical != null)
            return false;
        

        if (isaigue != null ? !isaigue.equals(that.isaigue) : that.isaigue != null)
            return false;
        

        if (ispromu != null ? !ispromu.equals(that.ispromu) : that.ispromu != null)
            return false;
        

        if (ispsychotrope != null ? !ispsychotrope.equals(that.ispsychotrope) : that.ispsychotrope != null)
            return false;
        

        if (isprodnationale != null ? !isprodnationale.equals(that.isprodnationale) : that.isprodnationale != null)
            return false;
        

        if (isagreement != null ? !isagreement.equals(that.isagreement) : that.isagreement != null)
            return false;
        

        if (iscoldchain != null ? !iscoldchain.equals(that.iscoldchain) : that.iscoldchain != null)
            return false;
        

        if (isrefundable != null ? !isrefundable.equals(that.isrefundable) : that.isrefundable != null)
            return false;
        

        if (xxDriveragreement != null ? !xxDriveragreement.equals(that.xxDriveragreement) : that.xxDriveragreement != null)
            return false;
        

        if (xxPresentation != null ? !xxPresentation.equals(that.xxPresentation) : that.xxPresentation != null)
            return false;
        

        if (xxLaboratoryId != null ? !xxLaboratoryId.equals(that.xxLaboratoryId) : that.xxLaboratoryId != null)
            return false;
        

        if (xxUg != null ? !xxUg.equals(that.xxUg) : that.xxUg != null)
            return false;
        

        if (xxClassificationId != null ? !xxClassificationId.equals(that.xxClassificationId) : that.xxClassificationId != null)
            return false;
        

        if (quantity != null ? !quantity.equals(that.quantity) : that.quantity != null)
            return false;
        

        if (xxFormattributeId != null ? !xxFormattributeId.equals(that.xxFormattributeId) : that.xxFormattributeId != null)
            return false;
        

        if (xxAssayId != null ? !xxAssayId.equals(that.xxAssayId) : that.xxAssayId != null)
            return false;
        

        if (xxFormeId != null ? !xxFormeId.equals(that.xxFormeId) : that.xxFormeId != null)
            return false;
        

        if (xxMaxqty != null ? !xxMaxqty.equals(that.xxMaxqty) : that.xxMaxqty != null)
            return false;
        

        if (xxDistributequota != null ? !xxDistributequota.equals(that.xxDistributequota) : that.xxDistributequota != null)
            return false;
        

        if (adColorId != null ? !adColorId.equals(that.adColorId) : that.adColorId != null)
            return false;
        

        if (adPrintcolorId != null ? !adPrintcolorId.equals(that.adPrintcolorId) : that.adPrintcolorId != null)
            return false;
        

        if (colortype != null ? !colortype.equals(that.colortype) : that.colortype != null)
            return false;
        

        if (red != null ? !red.equals(that.red) : that.red != null)
            return false;
        

        if (green != null ? !green.equals(that.green) : that.green != null)
            return false;
        

        if (blue != null ? !blue.equals(that.blue) : that.blue != null)
            return false;
        

        if (xxSalescontextId != null ? !xxSalescontextId.equals(that.xxSalescontextId) : that.xxSalescontextId != null)
            return false;
        

        if (xxShp != null ? !xxShp.equals(that.xxShp) : that.xxShp != null)
            return false;
        

        if (xxTarifRef != null ? !xxTarifRef.equals(that.xxTarifRef) : that.xxTarifRef != null)
            return false;
        

        if (cCountryId != null ? !cCountryId.equals(that.cCountryId) : that.cCountryId != null)
            return false;
        

        if (xxListeProduct != null ? !xxListeProduct.equals(that.xxListeProduct) : that.xxListeProduct != null)
            return false;
        

        if (dateenregistrement != null ? !dateenregistrement.equals(that.dateenregistrement) : that.dateenregistrement != null)
            return false;
        

        if (xxConditionnementId != null ? !xxConditionnementId.equals(that.xxConditionnementId) : that.xxConditionnementId != null)
            return false;
        

        if (isqr != null ? !isqr.equals(that.isqr) : that.isqr != null)
            return false;
        

        if (xxProductlineId != null ? !xxProductlineId.equals(that.xxProductlineId) : that.xxProductlineId != null)
            return false;
        

        if (cPaymenttermId != null ? !cPaymenttermId.equals(that.cPaymenttermId) : that.cPaymenttermId != null)
            return false;
        

        if (xxCreateupdatesubstitut != null ? !xxCreateupdatesubstitut.equals(that.xxCreateupdatesubstitut) : that.xxCreateupdatesubstitut != null)
            return false;
        

        if (ischer != null ? !ischer.equals(that.ischer) : that.ischer != null)
            return false;
        

        if (xxLastugachat != null ? !xxLastugachat.equals(that.xxLastugachat) : that.xxLastugachat != null)
            return false;
        

        if (xxStartegicalproduct != null ? !xxStartegicalproduct.equals(that.xxStartegicalproduct) : that.xxStartegicalproduct != null)
            return false;
        

        if (xxIsquotasystem != null ? !xxIsquotasystem.equals(that.xxIsquotasystem) : that.xxIsquotasystem != null)
            return false;
        

        if (xxTauxvaleur != null ? !xxTauxvaleur.equals(that.xxTauxvaleur) : that.xxTauxvaleur != null)
            return false;
        

        if (xxProduitsurcommande != null ? !xxProduitsurcommande.equals(that.xxProduitsurcommande) : that.xxProduitsurcommande != null)
            return false;
        

        if (xxTypecommande != null ? !xxTypecommande.equals(that.xxTypecommande) : that.xxTypecommande != null)
            return false;
        

        if (xxListetauxvaleurId != null ? !xxListetauxvaleurId.equals(that.xxListetauxvaleurId) : that.xxListetauxvaleurId != null)
            return false;
        

        if (xxCorrespondancecapital != null ? !xxCorrespondancecapital.equals(that.xxCorrespondancecapital) : that.xxCorrespondancecapital != null)
            return false;
        

        if (xxCriticalproduct != null ? !xxCriticalproduct.equals(that.xxCriticalproduct) : that.xxCriticalproduct != null)
            return false;
        

        if (xxCapitalName != null ? !xxCapitalName.equals(that.xxCapitalName) : that.xxCapitalName != null)
            return false;
        

        if (xxCapitalName2 != null ? !xxCapitalName2.equals(that.xxCapitalName2) : that.xxCapitalName2 != null)
            return false;
        

        if (xxUgbylot != null ? !xxUgbylot.equals(that.xxUgbylot) : that.xxUgbylot != null)
            return false;
        

        if (xxSoumiapprobation != null ? !xxSoumiapprobation.equals(that.xxSoumiapprobation) : that.xxSoumiapprobation != null)
            return false;
        

        if (xxUpdatesalesctxmap != null ? !xxUpdatesalesctxmap.equals(that.xxUpdatesalesctxmap) : that.xxUpdatesalesctxmap != null)
            return false;
        

        if (xxResteQuota != null ? !xxResteQuota.equals(that.xxResteQuota) : that.xxResteQuota != null)
            return false;
        

        if (xxUpdateprodcatctxvte != null ? !xxUpdateprodcatctxvte.equals(that.xxUpdateprodcatctxvte) : that.xxUpdateprodcatctxvte != null)
            return false;
        

        if (generatesalesctx != null ? !generatesalesctx.equals(that.generatesalesctx) : that.generatesalesctx != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = (int)(adClientId ^ (adClientId >>> 32));

        res = 31 * res + (int)(adOrgId ^ (adOrgId >>> 32));

        res = 31 * res + (isactive != null ? isactive.hashCode() : 0);

        res = 31 * res + (created != null ? created.hashCode() : 0);

        res = 31 * res + (int)(createdby ^ (createdby >>> 32));

        res = 31 * res + (updated != null ? updated.hashCode() : 0);

        res = 31 * res + (int)(updatedby ^ (updatedby >>> 32));

        res = 31 * res + (value != null ? value.hashCode() : 0);

        res = 31 * res + (name != null ? name.hashCode() : 0);

        res = 31 * res + (description != null ? description.hashCode() : 0);

        res = 31 * res + (documentnote != null ? documentnote.hashCode() : 0);

        res = 31 * res + (help != null ? help.hashCode() : 0);

        res = 31 * res + (upc != null ? upc.hashCode() : 0);

        res = 31 * res + (sku != null ? sku.hashCode() : 0);

        res = 31 * res + (int)(cUomId ^ (cUomId >>> 32));

        res = 31 * res + (salesrepId != null ? salesrepId.hashCode() : 0);

        res = 31 * res + (issummary != null ? issummary.hashCode() : 0);

        res = 31 * res + (isstocked != null ? isstocked.hashCode() : 0);

        res = 31 * res + (ispurchased != null ? ispurchased.hashCode() : 0);

        res = 31 * res + (issold != null ? issold.hashCode() : 0);

        res = 31 * res + (isbom != null ? isbom.hashCode() : 0);

        res = 31 * res + (isinvoiceprintdetails != null ? isinvoiceprintdetails.hashCode() : 0);

        res = 31 * res + (ispicklistprintdetails != null ? ispicklistprintdetails.hashCode() : 0);

        res = 31 * res + (isverified != null ? isverified.hashCode() : 0);

        res = 31 * res + (int)(mProductCategoryId ^ (mProductCategoryId >>> 32));

        res = 31 * res + (classification != null ? classification.hashCode() : 0);

        res = 31 * res + (volume != null ? volume.hashCode() : 0);

        res = 31 * res + (weight != null ? weight.hashCode() : 0);

        res = 31 * res + (shelfwidth != null ? shelfwidth.hashCode() : 0);

        res = 31 * res + (shelfheight != null ? shelfheight.hashCode() : 0);

        res = 31 * res + (shelfdepth != null ? shelfdepth.hashCode() : 0);

        res = 31 * res + (unitsperpallet != null ? unitsperpallet.hashCode() : 0);

        res = 31 * res + (int)(cTaxcategoryId ^ (cTaxcategoryId >>> 32));

        res = 31 * res + (sResourceId != null ? sResourceId.hashCode() : 0);

        res = 31 * res + (discontinued != null ? discontinued.hashCode() : 0);

        res = 31 * res + (discontinuedby != null ? discontinuedby.hashCode() : 0);

        res = 31 * res + (processing != null ? processing.hashCode() : 0);

        res = 31 * res + (sExpensetypeId != null ? sExpensetypeId.hashCode() : 0);

        res = 31 * res + (producttype != null ? producttype.hashCode() : 0);

        res = 31 * res + (imageurl != null ? imageurl.hashCode() : 0);

        res = 31 * res + (descriptionurl != null ? descriptionurl.hashCode() : 0);

        res = 31 * res + (guaranteedays != null ? guaranteedays.hashCode() : 0);

        res = 31 * res + (rMailtextId != null ? rMailtextId.hashCode() : 0);

        res = 31 * res + (versionno != null ? versionno.hashCode() : 0);

        res = 31 * res + (mAttributesetId != null ? mAttributesetId.hashCode() : 0);

        res = 31 * res + (mAttributesetinstanceId != null ? mAttributesetinstanceId.hashCode() : 0);

        res = 31 * res + (downloadurl != null ? downloadurl.hashCode() : 0);

        res = 31 * res + (mFreightcategoryId != null ? mFreightcategoryId.hashCode() : 0);

        res = 31 * res + (mLocatorId != null ? mLocatorId.hashCode() : 0);

        res = 31 * res + (guaranteedaysmin != null ? guaranteedaysmin.hashCode() : 0);

        res = 31 * res + (iswebstorefeatured != null ? iswebstorefeatured.hashCode() : 0);

        res = 31 * res + (isselfservice != null ? isselfservice.hashCode() : 0);

        res = 31 * res + (cSubscriptiontypeId != null ? cSubscriptiontypeId.hashCode() : 0);

        res = 31 * res + (isdropship != null ? isdropship.hashCode() : 0);

        res = 31 * res + (zlasttransactiondate != null ? zlasttransactiondate.hashCode() : 0);

        res = 31 * res + (isexcludeautodelivery != null ? isexcludeautodelivery.hashCode() : 0);

        res = 31 * res + (codedouanier != null ? codedouanier.hashCode() : 0);

        res = 31 * res + (commoditycode != null ? commoditycode.hashCode() : 0);

        res = 31 * res + (supportunits != null ? supportunits.hashCode() : 0);

        res = 31 * res + (ispurchasedtoorder != null ? ispurchasedtoorder.hashCode() : 0);

        res = 31 * res + (licenseinfo != null ? licenseinfo.hashCode() : 0);

        res = 31 * res + (rSourceId != null ? rSourceId.hashCode() : 0);

        res = 31 * res + (trialphasedays != null ? trialphasedays.hashCode() : 0);

        res = 31 * res + (zUomfId != null ? zUomfId.hashCode() : 0);

        res = 31 * res + (zPriceumf != null ? zPriceumf.hashCode() : 0);

        res = 31 * res + (zAttributeumfId != null ? zAttributeumfId.hashCode() : 0);

        res = 31 * res + (xxProductclass != null ? xxProductclass.hashCode() : 0);

        res = 31 * res + (type != null ? type.hashCode() : 0);

        res = 31 * res + (xxMarketingcategory != null ? xxMarketingcategory.hashCode() : 0);

        res = 31 * res + (xxRank != null ? xxRank.hashCode() : 0);

        res = 31 * res + (xxPricelevel != null ? xxPricelevel.hashCode() : 0);

        res = 31 * res + (isotc != null ? isotc.hashCode() : 0);

        res = 31 * res + (ischronical != null ? ischronical.hashCode() : 0);

        res = 31 * res + (isaigue != null ? isaigue.hashCode() : 0);

        res = 31 * res + (ispromu != null ? ispromu.hashCode() : 0);

        res = 31 * res + (ispsychotrope != null ? ispsychotrope.hashCode() : 0);

        res = 31 * res + (isprodnationale != null ? isprodnationale.hashCode() : 0);

        res = 31 * res + (isagreement != null ? isagreement.hashCode() : 0);

        res = 31 * res + (iscoldchain != null ? iscoldchain.hashCode() : 0);

        res = 31 * res + (isrefundable != null ? isrefundable.hashCode() : 0);

        res = 31 * res + (xxDriveragreement != null ? xxDriveragreement.hashCode() : 0);

        res = 31 * res + (xxPresentation != null ? xxPresentation.hashCode() : 0);

        res = 31 * res + (xxLaboratoryId != null ? xxLaboratoryId.hashCode() : 0);

        res = 31 * res + (xxUg != null ? xxUg.hashCode() : 0);

        res = 31 * res + (xxClassificationId != null ? xxClassificationId.hashCode() : 0);

        res = 31 * res + (quantity != null ? quantity.hashCode() : 0);

        res = 31 * res + (xxFormattributeId != null ? xxFormattributeId.hashCode() : 0);

        res = 31 * res + (xxAssayId != null ? xxAssayId.hashCode() : 0);

        res = 31 * res + (xxFormeId != null ? xxFormeId.hashCode() : 0);

        res = 31 * res + (xxMaxqty != null ? xxMaxqty.hashCode() : 0);

        res = 31 * res + (xxDistributequota != null ? xxDistributequota.hashCode() : 0);

        res = 31 * res + (adColorId != null ? adColorId.hashCode() : 0);

        res = 31 * res + (adPrintcolorId != null ? adPrintcolorId.hashCode() : 0);

        res = 31 * res + (colortype != null ? colortype.hashCode() : 0);

        res = 31 * res + (red != null ? red.hashCode() : 0);

        res = 31 * res + (green != null ? green.hashCode() : 0);

        res = 31 * res + (blue != null ? blue.hashCode() : 0);

        res = 31 * res + (xxSalescontextId != null ? xxSalescontextId.hashCode() : 0);

        res = 31 * res + (xxShp != null ? xxShp.hashCode() : 0);

        res = 31 * res + (xxTarifRef != null ? xxTarifRef.hashCode() : 0);

        res = 31 * res + (cCountryId != null ? cCountryId.hashCode() : 0);

        res = 31 * res + (xxListeProduct != null ? xxListeProduct.hashCode() : 0);

        res = 31 * res + (dateenregistrement != null ? dateenregistrement.hashCode() : 0);

        res = 31 * res + (xxConditionnementId != null ? xxConditionnementId.hashCode() : 0);

        res = 31 * res + (isqr != null ? isqr.hashCode() : 0);

        res = 31 * res + (xxProductlineId != null ? xxProductlineId.hashCode() : 0);

        res = 31 * res + (cPaymenttermId != null ? cPaymenttermId.hashCode() : 0);

        res = 31 * res + (xxCreateupdatesubstitut != null ? xxCreateupdatesubstitut.hashCode() : 0);

        res = 31 * res + (ischer != null ? ischer.hashCode() : 0);

        res = 31 * res + (xxLastugachat != null ? xxLastugachat.hashCode() : 0);

        res = 31 * res + (xxStartegicalproduct != null ? xxStartegicalproduct.hashCode() : 0);

        res = 31 * res + (xxIsquotasystem != null ? xxIsquotasystem.hashCode() : 0);

        res = 31 * res + (xxTauxvaleur != null ? xxTauxvaleur.hashCode() : 0);

        res = 31 * res + (xxProduitsurcommande != null ? xxProduitsurcommande.hashCode() : 0);

        res = 31 * res + (xxTypecommande != null ? xxTypecommande.hashCode() : 0);

        res = 31 * res + (xxListetauxvaleurId != null ? xxListetauxvaleurId.hashCode() : 0);

        res = 31 * res + (xxCorrespondancecapital != null ? xxCorrespondancecapital.hashCode() : 0);

        res = 31 * res + (xxCriticalproduct != null ? xxCriticalproduct.hashCode() : 0);

        res = 31 * res + (xxCapitalName != null ? xxCapitalName.hashCode() : 0);

        res = 31 * res + (xxCapitalName2 != null ? xxCapitalName2.hashCode() : 0);

        res = 31 * res + (xxUgbylot != null ? xxUgbylot.hashCode() : 0);

        res = 31 * res + (xxSoumiapprobation != null ? xxSoumiapprobation.hashCode() : 0);

        res = 31 * res + (xxUpdatesalesctxmap != null ? xxUpdatesalesctxmap.hashCode() : 0);

        res = 31 * res + (xxResteQuota != null ? xxResteQuota.hashCode() : 0);

        res = 31 * res + (xxUpdateprodcatctxvte != null ? xxUpdateprodcatctxvte.hashCode() : 0);

        res = 31 * res + (generatesalesctx != null ? generatesalesctx.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "MProduct [" + 
            "adClientId=" + adClientId + ", " + 
            "adOrgId=" + adOrgId + ", " + 
            "isactive=" + isactive + ", " + 
            "created=" + created + ", " + 
            "createdby=" + createdby + ", " + 
            "updated=" + updated + ", " + 
            "updatedby=" + updatedby + ", " + 
            "value=" + value + ", " + 
            "name=" + name + ", " + 
            "description=" + description + ", " + 
            "documentnote=" + documentnote + ", " + 
            "help=" + help + ", " + 
            "upc=" + upc + ", " + 
            "sku=" + sku + ", " + 
            "cUomId=" + cUomId + ", " + 
            "salesrepId=" + salesrepId + ", " + 
            "issummary=" + issummary + ", " + 
            "isstocked=" + isstocked + ", " + 
            "ispurchased=" + ispurchased + ", " + 
            "issold=" + issold + ", " + 
            "isbom=" + isbom + ", " + 
            "isinvoiceprintdetails=" + isinvoiceprintdetails + ", " + 
            "ispicklistprintdetails=" + ispicklistprintdetails + ", " + 
            "isverified=" + isverified + ", " + 
            "mProductCategoryId=" + mProductCategoryId + ", " + 
            "classification=" + classification + ", " + 
            "volume=" + volume + ", " + 
            "weight=" + weight + ", " + 
            "shelfwidth=" + shelfwidth + ", " + 
            "shelfheight=" + shelfheight + ", " + 
            "shelfdepth=" + shelfdepth + ", " + 
            "unitsperpallet=" + unitsperpallet + ", " + 
            "cTaxcategoryId=" + cTaxcategoryId + ", " + 
            "sResourceId=" + sResourceId + ", " + 
            "discontinued=" + discontinued + ", " + 
            "discontinuedby=" + discontinuedby + ", " + 
            "processing=" + processing + ", " + 
            "sExpensetypeId=" + sExpensetypeId + ", " + 
            "producttype=" + producttype + ", " + 
            "imageurl=" + imageurl + ", " + 
            "descriptionurl=" + descriptionurl + ", " + 
            "guaranteedays=" + guaranteedays + ", " + 
            "rMailtextId=" + rMailtextId + ", " + 
            "versionno=" + versionno + ", " + 
            "mAttributesetId=" + mAttributesetId + ", " + 
            "mAttributesetinstanceId=" + mAttributesetinstanceId + ", " + 
            "downloadurl=" + downloadurl + ", " + 
            "mFreightcategoryId=" + mFreightcategoryId + ", " + 
            "mLocatorId=" + mLocatorId + ", " + 
            "guaranteedaysmin=" + guaranteedaysmin + ", " + 
            "iswebstorefeatured=" + iswebstorefeatured + ", " + 
            "isselfservice=" + isselfservice + ", " + 
            "cSubscriptiontypeId=" + cSubscriptiontypeId + ", " + 
            "isdropship=" + isdropship + ", " + 
            "zlasttransactiondate=" + zlasttransactiondate + ", " + 
            "isexcludeautodelivery=" + isexcludeautodelivery + ", " + 
            "codedouanier=" + codedouanier + ", " + 
            "commoditycode=" + commoditycode + ", " + 
            "supportunits=" + supportunits + ", " + 
            "ispurchasedtoorder=" + ispurchasedtoorder + ", " + 
            "licenseinfo=" + licenseinfo + ", " + 
            "rSourceId=" + rSourceId + ", " + 
            "trialphasedays=" + trialphasedays + ", " + 
            "zUomfId=" + zUomfId + ", " + 
            "zPriceumf=" + zPriceumf + ", " + 
            "zAttributeumfId=" + zAttributeumfId + ", " + 
            "xxProductclass=" + xxProductclass + ", " + 
            "type=" + type + ", " + 
            "xxMarketingcategory=" + xxMarketingcategory + ", " + 
            "xxRank=" + xxRank + ", " + 
            "xxPricelevel=" + xxPricelevel + ", " + 
            "isotc=" + isotc + ", " + 
            "ischronical=" + ischronical + ", " + 
            "isaigue=" + isaigue + ", " + 
            "ispromu=" + ispromu + ", " + 
            "ispsychotrope=" + ispsychotrope + ", " + 
            "isprodnationale=" + isprodnationale + ", " + 
            "isagreement=" + isagreement + ", " + 
            "iscoldchain=" + iscoldchain + ", " + 
            "isrefundable=" + isrefundable + ", " + 
            "xxDriveragreement=" + xxDriveragreement + ", " + 
            "xxPresentation=" + xxPresentation + ", " + 
            "xxLaboratoryId=" + xxLaboratoryId + ", " + 
            "xxUg=" + xxUg + ", " + 
            "xxClassificationId=" + xxClassificationId + ", " + 
            "quantity=" + quantity + ", " + 
            "xxFormattributeId=" + xxFormattributeId + ", " + 
            "xxAssayId=" + xxAssayId + ", " + 
            "xxFormeId=" + xxFormeId + ", " + 
            "xxMaxqty=" + xxMaxqty + ", " + 
            "xxDistributequota=" + xxDistributequota + ", " + 
            "adColorId=" + adColorId + ", " + 
            "adPrintcolorId=" + adPrintcolorId + ", " + 
            "colortype=" + colortype + ", " + 
            "red=" + red + ", " + 
            "green=" + green + ", " + 
            "blue=" + blue + ", " + 
            "xxSalescontextId=" + xxSalescontextId + ", " + 
            "xxShp=" + xxShp + ", " + 
            "xxTarifRef=" + xxTarifRef + ", " + 
            "cCountryId=" + cCountryId + ", " + 
            "xxListeProduct=" + xxListeProduct + ", " + 
            "dateenregistrement=" + dateenregistrement + ", " + 
            "xxConditionnementId=" + xxConditionnementId + ", " + 
            "isqr=" + isqr + ", " + 
            "xxProductlineId=" + xxProductlineId + ", " + 
            "cPaymenttermId=" + cPaymenttermId + ", " + 
            "xxCreateupdatesubstitut=" + xxCreateupdatesubstitut + ", " + 
            "ischer=" + ischer + ", " + 
            "xxLastugachat=" + xxLastugachat + ", " + 
            "xxStartegicalproduct=" + xxStartegicalproduct + ", " + 
            "xxIsquotasystem=" + xxIsquotasystem + ", " + 
            "xxTauxvaleur=" + xxTauxvaleur + ", " + 
            "xxProduitsurcommande=" + xxProduitsurcommande + ", " + 
            "xxTypecommande=" + xxTypecommande + ", " + 
            "xxListetauxvaleurId=" + xxListetauxvaleurId + ", " + 
            "xxCorrespondancecapital=" + xxCorrespondancecapital + ", " + 
            "xxCriticalproduct=" + xxCriticalproduct + ", " + 
            "xxCapitalName=" + xxCapitalName + ", " + 
            "xxCapitalName2=" + xxCapitalName2 + ", " + 
            "xxUgbylot=" + xxUgbylot + ", " + 
            "xxSoumiapprobation=" + xxSoumiapprobation + ", " + 
            "xxUpdatesalesctxmap=" + xxUpdatesalesctxmap + ", " + 
            "xxResteQuota=" + xxResteQuota + ", " + 
            "xxUpdateprodcatctxvte=" + xxUpdateprodcatctxvte + ", " + 
            "generatesalesctx=" + generatesalesctx +
        "]";
    }
}